// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_NATIVE_SELECTABLE_TEXT_G_H_
#define PIGEON_NATIVE_SELECTABLE_TEXT_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace oh_my_flutter {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class NativeSelectableTextMenuHostApi;
  friend class NativeSelectableTextMenuFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Carries a Flutter logical-pixel rectangle to a native menu host.
//
// Generated class from Pigeon that represents data sent in messages.
class NativeSelectableTextRectangleMessage {
 public:
  // Constructs an object setting all fields.
  explicit NativeSelectableTextRectangleMessage(
    double left,
    double top,
    double right,
    double bottom);

  // The horizontal coordinate of the leading edge.
  double left() const;
  void set_left(double value_arg);

  // The vertical coordinate of the upper edge.
  double top() const;
  void set_top(double value_arg);

  // The horizontal coordinate of the trailing edge.
  double right() const;
  void set_right(double value_arg);

  // The vertical coordinate of the lower edge.
  double bottom() const;
  void set_bottom(double value_arg);

  bool operator==(const NativeSelectableTextRectangleMessage& other) const;
  bool operator!=(const NativeSelectableTextRectangleMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const NativeSelectableTextRectangleMessage& obj);
 private:
  static NativeSelectableTextRectangleMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class NativeSelectableTextMenuRequestMessage;
  friend class NativeSelectableTextMenuHostApi;
  friend class NativeSelectableTextMenuFlutterApi;
  friend class PigeonInternalCodecSerializer;
  double left_;
  double top_;
  double right_;
  double bottom_;
};


// Carries a Flutter logical-pixel point to a native menu host.
//
// Generated class from Pigeon that represents data sent in messages.
class NativeSelectableTextPointMessage {
 public:
  // Constructs an object setting all fields.
  explicit NativeSelectableTextPointMessage(
    double dx,
    double dy);

  // The horizontal coordinate.
  double dx() const;
  void set_dx(double value_arg);

  // The vertical coordinate.
  double dy() const;
  void set_dy(double value_arg);

  bool operator==(const NativeSelectableTextPointMessage& other) const;
  bool operator!=(const NativeSelectableTextPointMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const NativeSelectableTextPointMessage& obj);
 private:
  static NativeSelectableTextPointMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class NativeSelectableTextMenuRequestMessage;
  friend class NativeSelectableTextMenuHostApi;
  friend class NativeSelectableTextMenuFlutterApi;
  friend class PigeonInternalCodecSerializer;
  double dx_;
  double dy_;
};


// Describes one labeled native selection-menu command.
//
// Generated class from Pigeon that represents data sent in messages.
class NativeSelectableTextMenuItemMessage {
 public:
  // Constructs an object setting all fields.
  explicit NativeSelectableTextMenuItemMessage(
    int64_t identifier,
    const std::string& label);

  // The identifier returned when the person chooses this item.
  int64_t identifier() const;
  void set_identifier(int64_t value_arg);

  // The localized label displayed by the platform menu.
  const std::string& label() const;
  void set_label(std::string_view value_arg);

  bool operator==(const NativeSelectableTextMenuItemMessage& other) const;
  bool operator!=(const NativeSelectableTextMenuItemMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const NativeSelectableTextMenuItemMessage& obj);
 private:
  static NativeSelectableTextMenuItemMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class NativeSelectableTextMenuHostApi;
  friend class NativeSelectableTextMenuFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t identifier_;
  std::string label_;
};


// Describes one native selection-menu presentation.
//
// Generated class from Pigeon that represents data sent in messages.
class NativeSelectableTextMenuRequestMessage {
 public:
  // Constructs an object setting all fields.
  explicit NativeSelectableTextMenuRequestMessage(
    int64_t session_identifier,
    const NativeSelectableTextRectangleMessage& selection_rectangle,
    const NativeSelectableTextPointMessage& primary_anchor,
    const ::flutter::EncodableList& items);

  ~NativeSelectableTextMenuRequestMessage() = default;
  NativeSelectableTextMenuRequestMessage(const NativeSelectableTextMenuRequestMessage& other);
  NativeSelectableTextMenuRequestMessage& operator=(const NativeSelectableTextMenuRequestMessage& other);
  NativeSelectableTextMenuRequestMessage(NativeSelectableTextMenuRequestMessage&& other) = default;
  NativeSelectableTextMenuRequestMessage& operator=(NativeSelectableTextMenuRequestMessage&& other) noexcept = default;
  // Identifies this presentation and rejects callbacks from older menus.
  int64_t session_identifier() const;
  void set_session_identifier(int64_t value_arg);

  // The selected glyph bounds in Flutter global logical pixels.
  const NativeSelectableTextRectangleMessage& selection_rectangle() const;
  void set_selection_rectangle(const NativeSelectableTextRectangleMessage& value_arg);

  // The preferred pointer or keyboard anchor in global logical pixels.
  const NativeSelectableTextPointMessage& primary_anchor() const;
  void set_primary_anchor(const NativeSelectableTextPointMessage& value_arg);

  // The ordered commands shown by the menu.
  const ::flutter::EncodableList& items() const;
  void set_items(const ::flutter::EncodableList& value_arg);

  bool operator==(const NativeSelectableTextMenuRequestMessage& other) const;
  bool operator!=(const NativeSelectableTextMenuRequestMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const NativeSelectableTextMenuRequestMessage& obj);
 private:
  static NativeSelectableTextMenuRequestMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class NativeSelectableTextMenuHostApi;
  friend class NativeSelectableTextMenuFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t session_identifier_;
  std::unique_ptr<NativeSelectableTextRectangleMessage> selection_rectangle_;
  std::unique_ptr<NativeSelectableTextPointMessage> primary_anchor_;
  ::flutter::EncodableList items_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Presents selection commands through the current native host.
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class NativeSelectableTextMenuHostApi {
 public:
  NativeSelectableTextMenuHostApi(const NativeSelectableTextMenuHostApi&) = delete;
  NativeSelectableTextMenuHostApi& operator=(const NativeSelectableTextMenuHostApi&) = delete;
  virtual ~NativeSelectableTextMenuHostApi() {}
  // Shows a native menu and reports whether presentation was accepted.
  virtual ErrorOr<bool> Show(const NativeSelectableTextMenuRequestMessage& request) = 0;
  // Updates an already visible native menu.
  virtual ErrorOr<bool> Update(const NativeSelectableTextMenuRequestMessage& request) = 0;
  // Updates only the current selection rectangle and primary anchor.
  //
  // [geometry] contains left, top, right, bottom, anchor dx, and anchor dy in
  // Flutter global logical pixels, in that order.
  virtual ErrorOr<bool> UpdateGeometry(
    int64_t session_identifier,
    const std::vector<double>& geometry) = 0;
  // Hides the menu for [sessionIdentifier] when it is still current.
  virtual std::optional<FlutterError> Hide(int64_t session_identifier) = 0;

  // The codec used by NativeSelectableTextMenuHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `NativeSelectableTextMenuHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    NativeSelectableTextMenuHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    NativeSelectableTextMenuHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  NativeSelectableTextMenuHostApi() = default;
};
// Delivers native selection-menu events to Flutter.
//
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class NativeSelectableTextMenuFlutterApi {
 public:
  NativeSelectableTextMenuFlutterApi(::flutter::BinaryMessenger* binary_messenger);
  NativeSelectableTextMenuFlutterApi(
    ::flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Invokes a command previously sent for [sessionIdentifier].
  void OnAction(
    int64_t session_identifier,
    int64_t action_identifier,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // Reports that a menu closed and whether a command caused the dismissal.
  void OnDismissed(
    int64_t session_identifier,
    bool action_invoked,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
 private:
  ::flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace oh_my_flutter
#endif  // PIGEON_NATIVE_SELECTABLE_TEXT_G_H_
