part of '../device_display_model.dart';

final class _DeviceDisplayModelCollector {
  Map<String, Object?> validateSourceManifests() {
    final androidDirectory = Directory(
      '${Directory.current.path}/tool/device_display_model/android_collector',
    );
    final iosDirectory = Directory(
      '${Directory.current.path}/tool/device_display_model/ios_device_collector',
    );
    final androidSourceHash = _collectorSourceHash(androidDirectory);
    final iosSourceHash = _collectorSourceHash(iosDirectory);
    final iosHeader = File('${iosDirectory.path}/collector_source_hash.h');
    final expectedIosHeader =
        '// Generated by generate_ios_device_collector_provenance.sh.\n'
        '#define OMF_DEVICE_DISPLAY_COLLECTOR_SOURCE_HASH @"$iosSourceHash"\n';
    return <String, Object?>{
      'androidCollectorSourceHash': androidSourceHash,
      'iosCollectorSourceHash': iosSourceHash,
      'iosCollectorSourceManifestFresh': iosHeader.existsSync() && iosHeader.readAsStringSync() == expectedIosHeader,
    };
  }

  Future<Map<String, Object?>> validateTooling() async {
    final android = await _androidCollectorApk();
    final sources = validateSourceManifests();
    return <String, Object?>{
      'androidCollectorBuiltAndLinted': android != null,
      'androidCollectorSourceHash': android?.sourceHash,
      'iosCollectorSourceManifestFresh': sources['iosCollectorSourceManifestFresh'],
      'iosCollectorSourceHash': sources['iosCollectorSourceHash'],
    };
  }

  Future<Map<String, Object?>> collect({
    List<String> iosRecordPaths = const [],
    String? iosDeviceAppPath,
  }) async {
    final android = await _collectAndroid();
    final apple = await _collectApple(
      iosDeviceAppPath: iosDeviceAppPath,
    );
    final connectedIosRecords = (apple.remove('connectedRecords')! as List<Object?>).cast<Map<String, Object?>>();
    final iosRecords = <Map<String, Object?>>[];
    for (final path in iosRecordPaths) {
      final decoded = jsonDecode(File(path).readAsStringSync());
      final importedRecords = switch (decoded) {
        final Map<String, Object?> record => <Map<String, Object?>>[record],
        final List<Object?> records => records.map((value) => value! as Map<String, Object?>).toList(),
        _ => throw const FormatException(
          'An iOS record input must be a JSON object or array.',
        ),
      };
      for (final imported in importedRecords) {
        final record = _importIosRecord(imported);
        if (record != null) {
          iosRecords.add(record);
        }
      }
    }
    apple['exactLabelCount'] = iosRecords.length + connectedIosRecords.length;
    final collectedRecords = <Map<String, Object?>>[
      ...(android['records']! as List<Map<String, Object?>>),
      ...iosRecords,
      ...connectedIosRecords,
    ];
    final recordByObservation = <String, Map<String, Object?>>{};
    for (final record in collectedRecords) {
      final observationHash = record['sourceObservationHash']! as String;
      final existing = recordByObservation[observationHash];
      if (existing == null ||
          (existing['maskCollisionGroupHash'] == null && record['maskCollisionGroupHash'] != null)) {
        recordByObservation[observationHash] = record;
      }
    }
    final records = recordByObservation.values.toList()..sort(_compareRecords);

    return <String, Object?>{
      'schemaVersion': 1,
      'inventory': <String, Object?>{
        'android': android['inventory'],
        'apple': apple,
      },
      'records': records,
    };
  }

  Map<String, Object?>? _importIosRecord(Map<String, Object?> imported) {
    if (imported['platform'] != 'ios' ||
        (imported['sourceKind'] != 'ios26_public_uikit_concentric_corner' &&
            imported['sourceKind'] != 'ios_legacy_private_display_corner_selector')) {
      return null;
    }
    final width = imported['physicalWidth'];
    final height = imported['physicalHeight'];
    final topRadius = imported['topRadiusPhysical'];
    final bottomRadius = imported['bottomRadiusPhysical'];
    final density = imported['devicePixelRatio'];
    if (width is! num ||
        height is! num ||
        topRadius is! num ||
        bottomRadius is! num ||
        density is! num ||
        width <= 0 ||
        height <= 0 ||
        topRadius < 0 ||
        bottomRadius < 0 ||
        !width.toDouble().isFinite ||
        !height.toDouble().isFinite ||
        !topRadius.toDouble().isFinite ||
        !bottomRadius.toDouble().isFinite ||
        !density.toDouble().isFinite ||
        topRadius > math.min(width.toDouble(), height.toDouble()) / 2 ||
        bottomRadius > math.min(width.toDouble(), height.toDouble()) / 2 ||
        !_hasPhoneGeometry(
          physicalWidth: width.toDouble(),
          physicalHeight: height.toDouble(),
          devicePixelRatio: density.toDouble(),
        )) {
      return null;
    }
    final viewWidth = imported['viewPhysicalWidth'];
    final viewHeight = imported['viewPhysicalHeight'];
    if ((viewWidth == null) != (viewHeight == null) ||
        !_isValidOptionalDimension(viewWidth, maximum: width.toDouble()) ||
        !_isValidOptionalDimension(viewHeight, maximum: height.toDouble())) {
      return null;
    }
    for (final entry in <String, double>{
      'viewPaddingLeftPhysical': width.toDouble(),
      'viewPaddingTopPhysical': height.toDouble(),
      'viewPaddingRightPhysical': width.toDouble(),
      'viewPaddingBottomPhysical': height.toDouble(),
    }.entries) {
      if (!_isValidOptionalInset(imported[entry.key], maximum: entry.value)) {
        return null;
      }
    }
    for (final key in const <String>[
      'familyGroupHash',
      'generationGroupHash',
      'oemGroupHash',
      'maskCollisionGroupHash',
    ]) {
      final value = imported[key];
      if (value != null &&
          (value is! String ||
              !RegExp(
                r'^sha256:(?:[0-9a-f]{16}|[0-9a-f]{64})$',
              ).hasMatch(value))) {
        return null;
      }
    }
    final chronologyRank = imported['chronologyRank'];
    if (chronologyRank != null && (chronologyRank is! int || chronologyRank < 0)) {
      return null;
    }
    return _record(
      platform: 'ios',
      sourceKind: imported['sourceKind']! as String,
      physicalWidth: width,
      physicalHeight: height,
      viewPhysicalWidth: viewWidth as num?,
      viewPhysicalHeight: viewHeight as num?,
      devicePixelRatio: density,
      viewPaddingLeftPhysical: imported['viewPaddingLeftPhysical'] as num?,
      viewPaddingTopPhysical: imported['viewPaddingTopPhysical'] as num?,
      viewPaddingRightPhysical: imported['viewPaddingRightPhysical'] as num?,
      viewPaddingBottomPhysical: imported['viewPaddingBottomPhysical'] as num?,
      topRadiusPhysical: topRadius,
      bottomRadiusPhysical: bottomRadius,
      provenance: <String, Object?>{
        for (final key in const [
          'familyGroupHash',
          'generationGroupHash',
          'oemGroupHash',
          'maskCollisionGroupHash',
          'chronologyRank',
        ])
          if (imported[key] != null) key: imported[key],
      },
      labelAuthority: imported['sourceKind'] == 'ios26_public_uikit_concentric_corner'
          ? 'ios26_public_uikit_concentric_corner'
          : 'ios_tool_only_private_selector',
      cornerClassification: topRadius == 0 && bottomRadius == 0 ? 'square' : 'rounded',
    );
  }

  Future<Map<String, Object?>> _collectAndroid() async {
    final sdkPath = Platform.environment['ANDROID_HOME'] ?? Platform.environment['ANDROID_SDK_ROOT'];
    final records = <Map<String, Object?>>[];
    var skinCount = 0;
    var skinLabelCount = 0;
    var avdCount = 0;
    var connectedDeviceCount = 0;
    var connectedEmulatorDeviceCount = 0;
    var connectedEligibleDeviceCount = 0;
    var connectedCollectorAttemptCount = 0;
    var connectedLabelCount = 0;
    var connectedExactLabelCount = 0;
    var connectedLegacyLabelCount = 0;
    var connectedCollectorFailureCount = 0;
    String? connectedCollectorSourceHash;
    var avdDensityJoinCount = 0;

    if (sdkPath != null) {
      final skinsDirectory = Directory('$sdkPath/skins');
      final skinDirectories = skinsDirectory.existsSync()
          ? (skinsDirectory.listSync().whereType<Directory>().toList()
              ..sort((left, right) => left.path.compareTo(right.path)))
          : <Directory>[];
      final skinNames = <String>{
        for (final directory in skinDirectories) directory.path.split('/').last,
      };
      final skinGeometry = <String, ({int width, int height})>{};
      for (final directory in skinDirectories) {
        final geometry = _androidSkinGeometry(directory);
        if (geometry != null) {
          skinGeometry[directory.path.split('/').last] = geometry;
        }
      }
      final avdInventory = await _readAvdInventory(
        sdkPath,
        availableSkinNames: skinNames,
        skinGeometry: skinGeometry,
      );
      avdCount = avdInventory.count;
      if (skinsDirectory.existsSync()) {
        skinCount = skinDirectories.length;
        for (final directory in skinDirectories) {
          final skinName = directory.path.split('/').last;
          final record = _readAndroidSkin(
            directory,
            devicePixelRatio: avdInventory.densityBySkin[skinName],
            apiLevel: avdInventory.apiBySkin[skinName],
          );
          if (record != null) {
            records.add(record);
            skinLabelCount += 1;
            if (record['devicePixelRatio'] != null) {
              avdDensityJoinCount += 1;
            }
          }
        }
      }

      final adb = File('$sdkPath/platform-tools/adb');
      if (adb.existsSync()) {
        final connected = await _collectConnectedAndroid(adb.path);
        connectedDeviceCount = connected.deviceCount;
        connectedEmulatorDeviceCount = connected.emulatorDeviceCount;
        connectedEligibleDeviceCount = connected.eligibleDeviceCount;
        connectedCollectorAttemptCount = connected.attemptedDeviceCount;
        connectedLabelCount = connected.records.length;
        connectedExactLabelCount = connected.records
            .where(
              (record) => record['sourceKind'] == 'android_api31_window_insets',
            )
            .length;
        connectedLegacyLabelCount = connected.records
            .where(
              (record) => record['sourceKind'] == 'android_legacy_default_display_resource',
            )
            .length;
        connectedCollectorFailureCount = connected.failureCount;
        connectedCollectorSourceHash = connected.collectorSourceHash;
        records.addAll(connected.records);
      }
    }

    return <String, Object?>{
      'inventory': <String, Object?>{
        'sdkFound': sdkPath != null,
        'skinCount': skinCount,
        'skinLabelCount': skinLabelCount,
        'avdCount': avdCount,
        'avdDensityJoinCount': avdDensityJoinCount,
        'connectedDeviceCount': connectedDeviceCount,
        'connectedEmulatorDeviceCount': connectedEmulatorDeviceCount,
        'connectedEligibleDeviceCount': connectedEligibleDeviceCount,
        'connectedCollectorAttemptCount': connectedCollectorAttemptCount,
        'connectedLabelCount': connectedLabelCount,
        'connectedExactLabelCount': connectedExactLabelCount,
        'connectedLegacyLabelCount': connectedLegacyLabelCount,
        'connectedCollectorFailureCount': connectedCollectorFailureCount,
        'collectorSourceHash': connectedCollectorSourceHash,
      },
      'records': records,
    };
  }

  Map<String, Object?>? _readAndroidSkin(
    Directory directory, {
    required double? devicePixelRatio,
    required int? apiLevel,
  }) {
    final layout = File('${directory.path}/layout');
    if (!layout.existsSync()) {
      return null;
    }
    final contents = layout.readAsStringSync();
    final displayMatch = RegExp(
      r'display\s*\{([^}]*)\}',
      dotAll: true,
    ).firstMatch(contents);
    if (displayMatch == null) {
      return null;
    }
    final display = displayMatch.group(1)!;
    final width = _integer(display, 'width');
    final height = _integer(display, 'height');
    final radius = _integer(display, 'corner_radius');
    if (width == null ||
        height == null ||
        radius == null ||
        radius <= 0 ||
        devicePixelRatio == null ||
        !_hasPhoneGeometry(
          physicalWidth: width.toDouble(),
          physicalHeight: height.toDouble(),
          devicePixelRatio: devicePixelRatio,
        )) {
      return null;
    }
    return _record(
      sourceKind: 'android_sdk_skin_avd_join',
      physicalWidth: width,
      physicalHeight: height,
      devicePixelRatio: devicePixelRatio,
      viewPaddingTopPhysical: null,
      viewPaddingBottomPhysical: null,
      topRadiusPhysical: radius,
      bottomRadiusPhysical: radius,
      provenance: _anonymousProvenance(directory.path.split('/').last),
      sourceApiLevel: apiLevel,
      labelAuthority: 'android_emulator_skin_resource',
      cornerClassification: 'rounded',
    );
  }

  ({int width, int height})? _androidSkinGeometry(Directory directory) {
    final layout = File('${directory.path}/layout');
    if (!layout.existsSync()) {
      return null;
    }
    final display = RegExp(
      r'display\s*\{([^}]*)\}',
      dotAll: true,
    ).firstMatch(layout.readAsStringSync())?.group(1);
    if (display == null) {
      return null;
    }
    final width = _integer(display, 'width');
    final height = _integer(display, 'height');
    return width == null || height == null ? null : (width: width, height: height);
  }

  Future<
    ({
      int count,
      Map<String, double> densityBySkin,
      Map<String, int> apiBySkin,
    })
  >
  _readAvdInventory(
    String sdkPath, {
    required Set<String> availableSkinNames,
    required Map<String, ({int width, int height})> skinGeometry,
  }) async {
    final avdManager = File('$sdkPath/cmdline-tools/latest/bin/avdmanager');
    if (!avdManager.existsSync()) {
      return (
        count: 0,
        densityBySkin: <String, double>{},
        apiBySkin: <String, int>{},
      );
    }
    final result = await _runBounded(
      avdManager.path,
      const ['list', 'avd'],
    );
    if (result == null || result.exitCode != 0) {
      return (
        count: 0,
        densityBySkin: <String, double>{},
        apiBySkin: <String, int>{},
      );
    }
    final output = result.stdout;
    final avdCount = RegExp(
      r'^\s*Name:\s*.+$',
      multiLine: true,
    ).allMatches(output).length;
    final densities = <String, Set<double>>{};
    final apis = <String, Set<int>>{};
    for (final pathMatch in RegExp(
      r'^\s*Path:\s*(.+\.avd)\s*$',
      multiLine: true,
    ).allMatches(output)) {
      final config = File('${pathMatch.group(1)!}/config.ini');
      if (!config.existsSync()) {
        continue;
      }
      final properties = <String, String>{};
      for (final line in config.readAsLinesSync()) {
        final separator = line.indexOf('=');
        if (separator <= 0) {
          continue;
        }
        properties[line.substring(0, separator)] = line.substring(separator + 1);
      }
      final density = double.tryParse(properties['hw.lcd.density'] ?? '');
      final width = int.tryParse(properties['hw.lcd.width'] ?? '');
      final height = int.tryParse(properties['hw.lcd.height'] ?? '');
      final exactSkins = <String>{
        for (final key in const <String>['skin.name', 'hw.device.name'])
          if (properties[key] case final value?)
            if (availableSkinNames.contains(value)) value,
      };
      if (exactSkins.length != 1 || density == null || density <= 0 || width == null || height == null) {
        continue;
      }
      final skin = exactSkins.single;
      final expected = skinGeometry[skin];
      if (expected == null ||
          math.min(width, height) != math.min(expected.width, expected.height) ||
          math.max(width, height) != math.max(expected.width, expected.height)) {
        continue;
      }
      densities.putIfAbsent(skin, () => <double>{}).add(density / 160);
      final imagePath = properties['image.sysdir.1'];
      final api = imagePath == null
          ? null
          : int.tryParse(
              RegExp(r'android-(\d+)').firstMatch(imagePath)?.group(1) ?? '',
            );
      if (api != null) {
        apis.putIfAbsent(skin, () => <int>{}).add(api);
      }
    }
    return (
      count: avdCount,
      densityBySkin: <String, double>{
        for (final entry in densities.entries)
          if (entry.value.length == 1) entry.key: entry.value.single,
      },
      apiBySkin: <String, int>{
        for (final entry in apis.entries)
          if (entry.value.length == 1) entry.key: entry.value.single,
      },
    );
  }

  Future<
    ({
      int deviceCount,
      int emulatorDeviceCount,
      int eligibleDeviceCount,
      int attemptedDeviceCount,
      int failureCount,
      String? collectorSourceHash,
      List<Map<String, Object?>> records,
    })
  >
  _collectConnectedAndroid(String adbPath) async {
    final devicesResult = await _runBounded(adbPath, const ['devices']);
    if (devicesResult == null || devicesResult.exitCode != 0) {
      return (
        deviceCount: 0,
        emulatorDeviceCount: 0,
        eligibleDeviceCount: 0,
        attemptedDeviceCount: 0,
        failureCount: 0,
        collectorSourceHash: null,
        records: <Map<String, Object?>>[],
      );
    }
    final serials = <String>[];
    for (final line in devicesResult.stdout.split('\n')) {
      final match = RegExp(r'^(\S+)\s+device(?:\s|$)').firstMatch(line);
      if (match != null) {
        serials.add(match.group(1)!);
      }
    }
    serials.sort();

    final eligible = <({String serial, int sdkLevel})>[];
    var emulatorDeviceCount = 0;
    for (final serial in serials) {
      final emulatorResult = await _runBounded(adbPath, <String>[
        '-s',
        serial,
        'shell',
        'getprop',
        'ro.kernel.qemu',
      ]);
      if (emulatorResult == null || emulatorResult.exitCode != 0) {
        continue;
      }
      final emulatorMarker = emulatorResult.stdout.trim();
      if (emulatorMarker == '1') {
        emulatorDeviceCount += 1;
        continue;
      }
      // Android hardware normally exposes this property as either `0` or an
      // empty value. Any other successful value is not affirmative hardware
      // evidence, so keep the transport out of the physical-device corpus.
      if (emulatorMarker.isNotEmpty && emulatorMarker != '0') {
        continue;
      }
      final sdkResult = await _runBounded(adbPath, <String>[
        '-s',
        serial,
        'shell',
        'getprop',
        'ro.build.version.sdk',
      ]);
      final sdkLevel = sdkResult?.exitCode == 0 ? int.tryParse(sdkResult!.stdout.trim()) : null;
      if (sdkLevel != null && sdkLevel >= 24) {
        eligible.add((serial: serial, sdkLevel: sdkLevel));
      }
    }
    if (eligible.isEmpty) {
      return (
        deviceCount: serials.length,
        emulatorDeviceCount: emulatorDeviceCount,
        eligibleDeviceCount: 0,
        attemptedDeviceCount: 0,
        failureCount: 0,
        collectorSourceHash: null,
        records: <Map<String, Object?>>[],
      );
    }

    final collector = await _androidCollectorApk();
    if (collector == null) {
      return (
        deviceCount: serials.length,
        emulatorDeviceCount: emulatorDeviceCount,
        eligibleDeviceCount: eligible.length,
        attemptedDeviceCount: 0,
        failureCount: eligible.length,
        collectorSourceHash: null,
        records: <Map<String, Object?>>[],
      );
    }

    final records = <Map<String, Object?>>[];
    var attemptedDeviceCount = 0;
    var failureCount = 0;
    for (var index = 0; index < eligible.length; index += 1) {
      final device = eligible[index];
      attemptedDeviceCount += 1;
      final nonce = DeviceDisplayModelEncoding.fingerprint(
        <String, Object?>{
          'serial': device.serial,
          'process': pid,
          'index': index,
          'time': DateTime.now().microsecondsSinceEpoch,
        },
      );
      var installAttempted = false;
      try {
        installAttempted = true;
        final install = await _runBounded(adbPath, <String>[
          '-s',
          device.serial,
          'install',
          '-r',
          collector.path,
        ]);
        if (install == null || install.exitCode != 0) {
          failureCount += 1;
          continue;
        }
        await _runBounded(adbPath, <String>[
          '-s',
          device.serial,
          'shell',
          'am',
          'force-stop',
          _androidCollectorPackage,
        ]);
        final launch = await _runBounded(adbPath, <String>[
          '-s',
          device.serial,
          'shell',
          'am',
          'start',
          '-W',
          '-n',
          '$_androidCollectorPackage/.CornerRadiusCollectorActivity',
          '--es',
          'nonce',
          nonce,
        ]);
        if (launch == null || launch.exitCode != 0) {
          failureCount += 1;
          continue;
        }
        Map<String, Object?>? payload;
        for (var attempt = 0; attempt < 20; attempt += 1) {
          final pulled = await _runBounded(adbPath, <String>[
            '-s',
            device.serial,
            'exec-out',
            'run-as',
            _androidCollectorPackage,
            'cat',
            'files/device_display_record.json',
          ]);
          if (pulled?.exitCode == 0) {
            try {
              payload = jsonDecode(pulled!.stdout) as Map<String, Object?>;
            } on FormatException {
              payload = null;
            }
          }
          if (payload?['nonce'] == nonce) {
            break;
          }
          payload = null;
          await Future<void>.delayed(const Duration(milliseconds: 250));
        }
        final record = payload == null
            ? null
            : _importAndroidWindowInsetsRecord(
                payload,
                expectedNonce: nonce,
                sdkLevel: device.sdkLevel,
                expectedSourceHash: collector.sourceHash,
              );
        if (record == null) {
          failureCount += 1;
          continue;
        }
        record.addAll(
          await _connectedAndroidProvenance(adbPath, device.serial),
        );
        _updateSourceObservationHash(record);
        records.add(record);
      } finally {
        if (installAttempted) {
          await _runBounded(adbPath, <String>[
            '-s',
            device.serial,
            'uninstall',
            _androidCollectorPackage,
          ]);
        }
      }
    }
    return (
      deviceCount: serials.length,
      emulatorDeviceCount: emulatorDeviceCount,
      eligibleDeviceCount: eligible.length,
      attemptedDeviceCount: attemptedDeviceCount,
      failureCount: failureCount,
      collectorSourceHash: collector.sourceHash,
      records: records,
    );
  }

  static const _androidCollectorPackage = 'dev.ventairy.oh_my_flutter.device_display_model_collector';

  Future<({String path, String sourceHash})?> _androidCollectorApk() async {
    final configured = Platform.environment['OMF_DEVICE_DISPLAY_ANDROID_COLLECTOR_TEST_APK'];
    if (configured != null && Platform.environment['OMF_DEVICE_DISPLAY_ALLOW_TEST_COLLECTOR'] == '1') {
      final sourceHash = Platform.environment['OMF_DEVICE_DISPLAY_ANDROID_COLLECTOR_TEST_SOURCE_HASH'];
      final file = File(configured);
      if (!file.isAbsolute ||
          !file.existsSync() ||
          sourceHash == null ||
          !RegExp(r'^sha256:[0-9a-f]{64}$').hasMatch(sourceHash)) {
        return null;
      }
      return await _apkContainsAndroidCollectorSource(
            file.path,
            sourceHash,
          )
          ? (path: file.path, sourceHash: sourceHash)
          : null;
    }
    final collectorDirectory = Directory(
      '${Directory.current.path}/tool/device_display_model/android_collector',
    );
    final apk = File(
      '${collectorDirectory.path}/app/build/outputs/apk/debug/app-debug.apk',
    );
    final wrapper = File('${Directory.current.path}/example/android/gradlew');
    if (!wrapper.existsSync()) {
      return null;
    }
    final sourceHash = _androidCollectorSourceHash(collectorDirectory);
    final build = await _runBounded(
      wrapper.path,
      <String>[
        '-p',
        collectorDirectory.path,
        ':app:assembleDebug',
        ':app:lintDebug',
        '--rerun-tasks',
        '--console=plain',
      ],
      timeout: const Duration(minutes: 5),
    );
    if (build == null || build.exitCode != 0) {
      return null;
    }
    if (!apk.existsSync()) {
      return null;
    }
    return await _apkContainsAndroidCollectorSource(apk.path, sourceHash)
        ? (path: apk.path, sourceHash: sourceHash)
        : null;
  }

  String _androidCollectorSourceHash(Directory collectorDirectory) {
    return _collectorSourceHash(collectorDirectory);
  }

  String _collectorSourceHash(Directory collectorDirectory) {
    final manifest = File('${collectorDirectory.path}/source_manifest.txt');
    if (!manifest.existsSync()) {
      throw const FormatException('Collector source manifest is missing.');
    }
    final listedPaths = manifest
        .readAsLinesSync()
        .map((value) => value.trim())
        .where((value) => value.isNotEmpty)
        .toList();
    final sortedPaths = listedPaths.toList()..sort();
    if (listedPaths.toSet().length != listedPaths.length ||
        !_listsEqual(listedPaths, sortedPaths) ||
        listedPaths.any(
          (path) =>
              path.startsWith('/') ||
              path.contains(r'\') ||
              path
                  .split('/')
                  .any(
                    (segment) => segment.isEmpty || segment == '.' || segment == '..',
                  ),
        )) {
      throw const FormatException(
        'Collector source manifest must contain unique, sorted, safe relative paths.',
      );
    }
    final isAndroid = collectorDirectory.path.endsWith('android_collector');
    final actualPaths =
        collectorDirectory
            .listSync(recursive: true, followLinks: false)
            .whereType<File>()
            .map(
              (file) => file.path.substring(collectorDirectory.path.length + 1).replaceAll(Platform.pathSeparator, '/'),
            )
            .where(
              (path) => isAndroid
                  ? path == 'source_manifest.txt' ||
                        path == 'build.gradle.kts' ||
                        path == 'settings.gradle.kts' ||
                        path == 'protocol.json' ||
                        path == 'app/build.gradle.kts' ||
                        path.startsWith('app/src/')
                  : path != 'collector_source_hash.h',
            )
            .toList()
          ..sort();
    final expectedPaths = <String>['source_manifest.txt', ...listedPaths]..sort();
    if (!_listsEqual(actualPaths, expectedPaths)) {
      throw const FormatException(
        'Collector source manifest does not match the canonical source tree.',
      );
    }
    final relativePaths = <String>['source_manifest.txt', ...listedPaths];
    final canonical = <int>[];
    for (final relative in relativePaths) {
      final file = File('${collectorDirectory.path}/$relative');
      if (!file.existsSync()) {
        throw FormatException(
          'Collector source manifest references missing file: $relative',
        );
      }
      canonical
        ..addAll(utf8.encode(relative))
        ..add(0)
        ..addAll(file.readAsBytesSync())
        ..add(0);
    }
    return DeviceDisplayModelEncoding.sha256Fingerprint(canonical);
  }

  bool _listsEqual(List<String> left, List<String> right) {
    if (left.length != right.length) {
      return false;
    }
    for (var index = 0; index < left.length; index += 1) {
      if (left[index] != right[index]) {
        return false;
      }
    }
    return true;
  }

  Future<bool> _apkContainsAndroidCollectorSource(
    String path,
    String sourceHash,
  ) async {
    final apkAnalyzer = _androidApkAnalyzerExecutable();
    if (apkAnalyzer == null) {
      return false;
    }
    const buildConfigClass = '$_androidCollectorPackage.BuildConfig';
    final dex = await _runBounded(apkAnalyzer, <String>[
      'dex',
      'code',
      '--class',
      buildConfigClass,
      path,
    ]);
    if (dex == null || dex.exitCode != 0) {
      return false;
    }
    final classDescriptor = buildConfigClass.replaceAll('.', '/');
    final declaresExpectedClass = RegExp(
      '^\\.class[^\\r\\n]*L${RegExp.escape(classDescriptor)};\\s*\$',
      multiLine: true,
    ).hasMatch(dex.stdout);
    final sourceHashFields = RegExp(
      r'^\.field public static final '
      r'COLLECTOR_SOURCE_HASH:Ljava/lang/String; = "([^"]+)"\s*$',
      multiLine: true,
    ).allMatches(dex.stdout).toList();
    return declaresExpectedClass && sourceHashFields.length == 1 && sourceHashFields.single.group(1) == sourceHash;
  }

  String? _androidApkAnalyzerExecutable() {
    final configured = Platform.environment['OMF_DEVICE_DISPLAY_APKANALYZER'];
    if (configured != null) {
      final executable = File(configured);
      final testCollectorAllowed = Platform.environment['OMF_DEVICE_DISPLAY_ALLOW_TEST_COLLECTOR'] == '1';
      return testCollectorAllowed && executable.isAbsolute && executable.existsSync() ? executable.path : null;
    }

    final sdkPath = Platform.environment['ANDROID_HOME'] ?? Platform.environment['ANDROID_SDK_ROOT'];
    if (sdkPath == null) {
      return 'apkanalyzer';
    }
    final executableName = Platform.isWindows ? 'apkanalyzer.bat' : 'apkanalyzer';
    final commandLineTools = Directory('$sdkPath/cmdline-tools');
    if (!commandLineTools.existsSync()) {
      return 'apkanalyzer';
    }
    final candidates =
        commandLineTools
            .listSync(followLinks: false)
            .whereType<Directory>()
            .map((directory) => File('${directory.path}/bin/$executableName'))
            .where((file) => file.existsSync())
            .toList()
          ..sort((left, right) => right.path.compareTo(left.path));
    final latest = File(
      '${commandLineTools.path}/latest/bin/$executableName',
    );
    if (latest.existsSync()) {
      return latest.path;
    }
    return candidates.isEmpty ? 'apkanalyzer' : candidates.first.path;
  }

  Map<String, Object?>? _importAndroidWindowInsetsRecord(
    Map<String, Object?> payload, {
    required String expectedNonce,
    required int sdkLevel,
    required String expectedSourceHash,
  }) {
    if (payload['protocolVersion'] != 1 ||
        payload['protocolSourceHash'] != expectedSourceHash ||
        payload['nonce'] != expectedNonce ||
        payload['rotation'] != 0 ||
        payload['hasFoldOrHinge'] != false ||
        sdkLevel < 24) {
      return null;
    }
    if (payload['sourceKind'] == 'android_legacy_default_display_resource') {
      return _importAndroidLegacyRecord(payload, sdkLevel: sdkLevel);
    }
    if (payload['sourceKind'] != 'android_api31_window_insets' || sdkLevel < 31) {
      return null;
    }
    const positiveKeys = <String>[
      'physicalWidth',
      'physicalHeight',
      'viewPhysicalWidth',
      'viewPhysicalHeight',
      'devicePixelRatio',
    ];
    const nonNegativeKeys = <String>[
      'viewPaddingLeftPhysical',
      'viewPaddingTopPhysical',
      'viewPaddingRightPhysical',
      'viewPaddingBottomPhysical',
      'systemGestureInsetLeftPhysical',
      'systemGestureInsetTopPhysical',
      'systemGestureInsetRightPhysical',
      'systemGestureInsetBottomPhysical',
      'displayCutoutWidthPhysical',
      'displayCutoutHeightPhysical',
      'displayCutoutCount',
      'topLeftRadiusPhysical',
      'topRightRadiusPhysical',
      'bottomRightRadiusPhysical',
      'bottomLeftRadiusPhysical',
    ];
    if (positiveKeys.any(
          (key) => !_isFiniteNumber(payload[key], positive: true),
        ) ||
        nonNegativeKeys.any(
          (key) => !_isFiniteNumber(payload[key], positive: false),
        )) {
      return null;
    }
    final width = (payload['physicalWidth']! as num).toDouble();
    final height = (payload['physicalHeight']! as num).toDouble();
    final viewWidth = (payload['viewPhysicalWidth']! as num).toDouble();
    final viewHeight = (payload['viewPhysicalHeight']! as num).toDouble();
    final cutoutCount = (payload['displayCutoutCount']! as num).toDouble();
    final radii = <double>[
      for (final key in const <String>[
        'topLeftRadiusPhysical',
        'topRightRadiusPhysical',
        'bottomRightRadiusPhysical',
        'bottomLeftRadiusPhysical',
      ])
        (payload[key]! as num).toDouble(),
    ];
    final maximumDimension = math.max(width, height);
    if (!_hasPhoneGeometry(
          physicalWidth: width,
          physicalHeight: height,
          devicePixelRatio: (payload['devicePixelRatio']! as num).toDouble(),
        ) ||
        viewWidth > width ||
        viewHeight > height ||
        cutoutCount != cutoutCount.truncateToDouble() ||
        cutoutCount > 4 ||
        radii.any((radius) => radius > math.min(width, height) / 2) ||
        nonNegativeKeys
            .where((key) => !key.contains('Radius') && key != 'displayCutoutCount')
            .any(
              (key) => (payload[key]! as num).toDouble() > maximumDimension,
            )) {
      return null;
    }
    final isSquare = radii.every((radius) => radius == 0);
    return _record(
      sourceKind: 'android_api31_window_insets',
      physicalWidth: width,
      physicalHeight: height,
      viewPhysicalWidth: viewWidth,
      viewPhysicalHeight: viewHeight,
      devicePixelRatio: payload['devicePixelRatio']! as num,
      viewPaddingLeftPhysical: payload['viewPaddingLeftPhysical']! as num,
      viewPaddingTopPhysical: payload['viewPaddingTopPhysical']! as num,
      viewPaddingRightPhysical: payload['viewPaddingRightPhysical']! as num,
      viewPaddingBottomPhysical: payload['viewPaddingBottomPhysical']! as num,
      systemGestureInsetLeftPhysical: payload['systemGestureInsetLeftPhysical']! as num,
      systemGestureInsetTopPhysical: payload['systemGestureInsetTopPhysical']! as num,
      systemGestureInsetRightPhysical: payload['systemGestureInsetRightPhysical']! as num,
      systemGestureInsetBottomPhysical: payload['systemGestureInsetBottomPhysical']! as num,
      displayCutoutWidthPhysical: payload['displayCutoutWidthPhysical']! as num,
      displayCutoutHeightPhysical: payload['displayCutoutHeightPhysical']! as num,
      displayCutoutCount: payload['displayCutoutCount']! as num,
      topRadiusPhysical: (radii[0] + radii[1]) / 2,
      bottomRadiusPhysical: (radii[2] + radii[3]) / 2,
      sourceApiLevel: sdkLevel,
      labelAuthority: 'android_api31_window_insets',
      cornerClassification: isSquare ? 'square' : 'rounded',
    );
  }

  Map<String, Object?>? _importAndroidLegacyRecord(
    Map<String, Object?> payload, {
    required int sdkLevel,
  }) {
    if (sdkLevel >= 31) {
      return null;
    }
    const keys = <String>[
      'physicalWidth',
      'physicalHeight',
      'devicePixelRatio',
      'topRadiusPhysical',
      'bottomRadiusPhysical',
    ];
    if (keys.any(
      (key) => !_isFiniteNumber(payload[key], positive: true),
    )) {
      return null;
    }
    final width = (payload['physicalWidth']! as num).toDouble();
    final height = (payload['physicalHeight']! as num).toDouble();
    final density = (payload['devicePixelRatio']! as num).toDouble();
    final topRadius = (payload['topRadiusPhysical']! as num).toDouble();
    final bottomRadius = (payload['bottomRadiusPhysical']! as num).toDouble();
    if (!_hasPhoneGeometry(
          physicalWidth: width,
          physicalHeight: height,
          devicePixelRatio: density,
        ) ||
        topRadius > math.min(width, height) / 2 ||
        bottomRadius > math.min(width, height) / 2) {
      return null;
    }
    return _record(
      sourceKind: 'android_legacy_default_display_resource',
      physicalWidth: width,
      physicalHeight: height,
      devicePixelRatio: density,
      viewPaddingTopPhysical: null,
      viewPaddingBottomPhysical: null,
      topRadiusPhysical: topRadius,
      bottomRadiusPhysical: bottomRadius,
      sourceApiLevel: sdkLevel,
      labelAuthority: 'android_legacy_default_display_resource',
      cornerClassification: 'rounded',
    );
  }

  bool _hasPhoneGeometry({
    required double physicalWidth,
    required double physicalHeight,
    required double devicePixelRatio,
  }) {
    final logicalShort = math.min(physicalWidth, physicalHeight) / devicePixelRatio;
    final aspect = math.max(physicalWidth, physicalHeight) / math.min(physicalWidth, physicalHeight);
    return logicalShort >= 240 && logicalShort < 600 && aspect >= 4 / 3 && aspect <= 3;
  }

  bool _isValidOptionalDimension(Object? value, {required double maximum}) =>
      value == null || (value is num && value.toDouble().isFinite && value > 0 && value <= maximum);

  bool _isValidOptionalInset(Object? value, {required double maximum}) =>
      value == null || (value is num && value.toDouble().isFinite && value >= 0 && value <= maximum);

  bool _isFiniteNumber(Object? value, {required bool positive}) =>
      value is num && value.toDouble().isFinite && (positive ? value > 0 : value >= 0);

  Future<({int exitCode, String stdout, String stderr})?> _runBounded(
    String executable,
    List<String> arguments, {
    Duration? timeout,
  }) async {
    try {
      final process = await Process.start(executable, arguments);
      final stdoutBuffer = StringBuffer();
      final stderrBuffer = StringBuffer();
      final stdoutDone = Completer<void>();
      final stderrDone = Completer<void>();
      final stdoutSubscription =
          const Utf8Decoder(
                allowMalformed: true,
              )
              .bind(process.stdout)
              .listen(
                stdoutBuffer.write,
                onError: (_) => _complete(stdoutDone),
                onDone: () => _complete(stdoutDone),
              );
      final stderrSubscription =
          const Utf8Decoder(
                allowMalformed: true,
              )
              .bind(process.stderr)
              .listen(
                stderrBuffer.write,
                onError: (_) => _complete(stderrDone),
                onDone: () => _complete(stderrDone),
              );
      const grace = Duration(milliseconds: 500);
      final effectiveTimeout = timeout ?? _defaultProcessTimeout;
      int exitCode;
      try {
        exitCode = await process.exitCode.timeout(effectiveTimeout);
      } on TimeoutException {
        await _terminateProcess(process, grace: grace);
        await _finishProcessStream(
          stdoutSubscription,
          stdoutDone.future,
          grace: grace,
        );
        await _finishProcessStream(
          stderrSubscription,
          stderrDone.future,
          grace: grace,
        );
        return null;
      }
      final stdoutComplete = await _finishProcessStream(
        stdoutSubscription,
        stdoutDone.future,
        grace: grace,
      );
      final stderrComplete = await _finishProcessStream(
        stderrSubscription,
        stderrDone.future,
        grace: grace,
      );
      if (!stdoutComplete || !stderrComplete) {
        return null;
      }
      return (
        exitCode: exitCode,
        stdout: stdoutBuffer.toString(),
        stderr: stderrBuffer.toString(),
      );
    } on ProcessException {
      return null;
    }
  }

  Duration get _defaultProcessTimeout {
    if (Platform.environment['OMF_DEVICE_DISPLAY_ALLOW_TEST_COLLECTOR'] == '1') {
      final milliseconds = int.tryParse(
        Platform.environment['OMF_DEVICE_DISPLAY_PROCESS_TIMEOUT_MS'] ?? '',
      );
      if (milliseconds != null && milliseconds > 0) {
        return Duration(milliseconds: milliseconds);
      }
    }
    return const Duration(seconds: 15);
  }

  void _complete(Completer<void> completer) {
    if (!completer.isCompleted) {
      completer.complete();
    }
  }

  Future<void> _terminateProcess(
    Process process, {
    required Duration grace,
  }) async {
    if (Platform.isWindows) {
      final descendants = await _windowsDescendantProcessIds(
        process.pid,
        timeout: grace,
      );
      var taskkillSucceeded = false;
      try {
        final taskkill = await Process.run('taskkill', <String>[
          '/PID',
          '${process.pid}',
          '/T',
          '/F',
        ]).timeout(grace);
        taskkillSucceeded = taskkill.exitCode == 0;
      } on Object {
        taskkillSucceeded = false;
      }
      if (!taskkillSucceeded) {
        descendants.reversed.forEach(Process.killPid);
        process.kill();
      }
      try {
        await process.exitCode.timeout(grace);
      } on TimeoutException {
        process.kill();
      }
      return;
    }

    final descendants = await _descendantProcessIds(
      process.pid,
      timeout: grace,
    );
    process.kill(ProcessSignal.sigterm);
    for (final processId in descendants.reversed) {
      Process.killPid(processId, ProcessSignal.sigterm);
    }

    var parentExited = false;
    try {
      await process.exitCode.timeout(grace);
      parentExited = true;
    } on TimeoutException {
      // The hard-stop pass below handles a command that ignores termination.
    }
    for (final processId in descendants.reversed) {
      Process.killPid(processId, ProcessSignal.sigkill);
    }
    if (!parentExited) {
      process.kill(ProcessSignal.sigkill);
      try {
        await process.exitCode.timeout(grace);
      } on TimeoutException {
        return;
      }
    }
  }

  Future<List<int>> _descendantProcessIds(
    int parentProcessId, {
    required Duration timeout,
  }) async {
    try {
      final processTable = await Process.run(
        '/bin/ps',
        const <String>['-eo', 'pid=,ppid='],
      ).timeout(timeout);
      if (processTable.exitCode != 0) return const <int>[];
      return _descendantProcessIdsFromTable(
        processTable.stdout as String,
        parentProcessId,
      );
    } on Object {
      return const <int>[];
    }
  }

  Future<List<int>> _windowsDescendantProcessIds(
    int parentProcessId, {
    required Duration timeout,
  }) async {
    try {
      final processTable = await Process.run(
        'powershell.exe',
        const <String>[
          '-NoProfile',
          '-NonInteractive',
          '-Command',
          r'Get-CimInstance Win32_Process | ForEach-Object { "$($_.ProcessId) $($_.ParentProcessId)" }',
        ],
      ).timeout(timeout);
      if (processTable.exitCode != 0) return const <int>[];
      return _descendantProcessIdsFromTable(
        processTable.stdout as String,
        parentProcessId,
      );
    } on Object {
      return const <int>[];
    }
  }

  List<int> _descendantProcessIdsFromTable(
    String processTable,
    int parentProcessId,
  ) {
    final childrenByParent = <int, List<int>>{};
    for (final line in processTable.split('\n')) {
      final columns = line.trim().split(RegExp(r'\s+'));
      if (columns.length != 2) continue;

      final processId = int.tryParse(columns[0]);
      final parentId = int.tryParse(columns[1]);
      if (processId == null || parentId == null) continue;
      childrenByParent.putIfAbsent(parentId, () => <int>[]).add(processId);
    }

    final descendants = <int>[];
    final pendingParents = <int>[parentProcessId];
    while (pendingParents.isNotEmpty) {
      final children = childrenByParent[pendingParents.removeLast()];
      if (children == null) continue;
      descendants.addAll(children);
      pendingParents.addAll(children);
    }
    return descendants;
  }

  Future<bool> _finishProcessStream(
    StreamSubscription<String> subscription,
    Future<void> completed, {
    required Duration grace,
  }) async {
    try {
      await completed.timeout(grace);
      return true;
    } on TimeoutException {
      try {
        await subscription.cancel().timeout(grace);
      } on TimeoutException {
        // Cancellation is best effort after the bounded drain expires.
      }
      return false;
    }
  }

  Future<Map<String, Object?>> _collectApple({
    required String? iosDeviceAppPath,
  }) async {
    final deviceTypesResult = await _runXcrun(
      const ['simctl', 'list', 'devicetypes', '--json'],
    );
    final devicesResult = await _runXcrun(
      const ['simctl', 'list', 'devices', 'available', '--json'],
    );
    var deviceTypeCount = 0;
    var mobileDeviceTypeCount = 0;
    var framebufferMaskCount = 0;
    var framebufferCollisionCount = 0;
    var availableSimulatorCount = 0;
    var bootedSimulatorCount = 0;
    final chronologyRanksByProductType = <String, Set<int>>{};

    if (deviceTypesResult case final text?) {
      final root = jsonDecode(text) as Map<String, Object?>;
      final types = root['devicetypes']! as List<Object?>;
      deviceTypeCount = types.length;
      final masksByGeometry = <String, Set<String>>{};
      for (final value in types) {
        final type = value! as Map<String, Object?>;
        final family = type['productFamily'];
        if (family != 'iPhone' && family != 'iPad') {
          continue;
        }
        mobileDeviceTypeCount += 1;
        final bundlePath = type['bundlePath'];
        final profile = bundlePath is String
            ? await _readPlist(
                '$bundlePath/Contents/Resources/profile.plist',
              )
            : null;
        final modelIdentifier = type['modelIdentifier'] ?? profile?['modelIdentifier'];
        final minimumRuntimeVersion = type['minRuntimeVersion'];
        if (family == 'iPhone' &&
            modelIdentifier is String &&
            modelIdentifier.isNotEmpty &&
            minimumRuntimeVersion is int &&
            minimumRuntimeVersion >= 0) {
          chronologyRanksByProductType.putIfAbsent(modelIdentifier, () => <int>{}).add(minimumRuntimeVersion);
        }
        final mask = profile?['framebufferMask'];
        if (mask is! String || mask.isEmpty) {
          continue;
        }
        framebufferMaskCount += 1;
        final geometry = <String, Object?>{
          'width': profile?['mainScreenWidth'],
          'height': profile?['mainScreenHeight'],
          'scale': profile?['mainScreenScale'],
        };
        final signature = DeviceDisplayModelEncoding.fingerprint(geometry);
        masksByGeometry.putIfAbsent(signature, () => <String>{}).add(mask);
      }
      framebufferCollisionCount = masksByGeometry.values.where((masks) => masks.length > 1).length;
    }

    if (devicesResult case final text?) {
      final root = jsonDecode(text) as Map<String, Object?>;
      final runtimes = root['devices']! as Map<String, Object?>;
      for (final value in runtimes.values) {
        final devices = value! as List<Object?>;
        availableSimulatorCount += devices.length;
        for (final deviceValue in devices) {
          final device = deviceValue! as Map<String, Object?>;
          if (device['state'] == 'Booted') {
            bootedSimulatorCount += 1;
          }
        }
      }
    }

    final deviceTypeProvenanceByProductType = <String, ({String generationGroupHash, int chronologyRank})>{
      for (final entry in chronologyRanksByProductType.entries)
        if (entry.value.length == 1)
          entry.key: (
            generationGroupHash: DeviceDisplayModelEncoding.groupFingerprint(
              'generation-min-runtime:${entry.value.single}',
            ),
            chronologyRank: entry.value.single,
          ),
    };
    final connected = await _collectConnectedApple(
      iosDeviceAppPath: iosDeviceAppPath,
      deviceTypeProvenanceByProductType: deviceTypeProvenanceByProductType,
    );

    return <String, Object?>{
      'xcrunFound': deviceTypesResult != null,
      'deviceTypeCount': deviceTypeCount,
      'mobileDeviceTypeCount': mobileDeviceTypeCount,
      'framebufferMaskCount': framebufferMaskCount,
      'framebufferGeometryCollisionCount': framebufferCollisionCount,
      'availableSimulatorCount': availableSimulatorCount,
      'bootedSimulatorCount': bootedSimulatorCount,
      'exactLabelCount': 0,
      'maskLabelsUsedForTraining': false,
      'connectedDeviceCount': connected.deviceCount,
      'connectedEligibleDeviceCount': connected.eligibleDeviceCount,
      'connectedCollectorAppSupplied': iosDeviceAppPath != null,
      'connectedCollectorAttemptCount': connected.attemptedDeviceCount,
      'connectedLabelCount': connected.records.length,
      'connectedCollectorFailureCount': connected.failureCount,
      'connectedCollectorSourceHash': connected.collectorSourceHash,
      'connectedRecords': connected.records,
    };
  }

  Future<
    ({
      int deviceCount,
      int eligibleDeviceCount,
      int attemptedDeviceCount,
      int failureCount,
      String? collectorSourceHash,
      List<Map<String, Object?>> records,
    })
  >
  _collectConnectedApple({
    required String? iosDeviceAppPath,
    required Map<String, ({String generationGroupHash, int chronologyRank})> deviceTypeProvenanceByProductType,
  }) async {
    final temporaryDirectory = Directory.systemTemp.createTempSync(
      'omf-device-display-ios-',
    );
    final permissions = await _runBounded(
      'chmod',
      <String>['700', temporaryDirectory.path],
    );
    if (permissions?.exitCode != 0) {
      temporaryDirectory.deleteSync(recursive: true);
      return (
        deviceCount: 0,
        eligibleDeviceCount: 0,
        attemptedDeviceCount: 0,
        failureCount: 1,
        collectorSourceHash: null,
        records: <Map<String, Object?>>[],
      );
    }
    try {
      final inventory = await _runDevicectlJson(
        const <String>['list', 'devices'],
        temporaryDirectory: temporaryDirectory,
        outputName: 'inventory',
      );
      final values = inventory?['result'] is Map<String, Object?>
          ? ((inventory!['result']! as Map<String, Object?>)['devices'] as List<Object?>? ?? const <Object?>[])
          : const <Object?>[];
      final devices = <Map<String, Object?>>[];
      for (final value in values) {
        if (value is! Map<String, Object?>) {
          continue;
        }
        final hardware = value['hardwareProperties'];
        if (hardware is! Map<String, Object?>) {
          continue;
        }
        final platform = (hardware['platform'] as String?)?.toLowerCase();
        final reality = (hardware['reality'] as String?)?.toLowerCase();
        final productType = hardware['productType'] as String?;
        if (platform == 'ios' && reality == 'physical' && productType?.startsWith('iPhone') == true) {
          devices.add(value);
        }
      }
      final eligible = devices.where(_isEligibleConnectedAppleDevice).toList();
      if (iosDeviceAppPath == null) {
        return (
          deviceCount: devices.length,
          eligibleDeviceCount: eligible.length,
          attemptedDeviceCount: 0,
          failureCount: 0,
          collectorSourceHash: null,
          records: <Map<String, Object?>>[],
        );
      }
      final app = await _validatedIosDeviceApp(iosDeviceAppPath);
      if (app == null) {
        return (
          deviceCount: devices.length,
          eligibleDeviceCount: eligible.length,
          attemptedDeviceCount: 0,
          failureCount: eligible.length,
          collectorSourceHash: null,
          records: <Map<String, Object?>>[],
        );
      }

      final records = <Map<String, Object?>>[];
      var failureCount = 0;
      for (var index = 0; index < eligible.length; index += 1) {
        final device = eligible[index];
        final identifier = device['identifier'];
        if (identifier is! String || identifier.isEmpty) {
          failureCount += 1;
          continue;
        }
        final hardware = device['hardwareProperties']! as Map<String, Object?>;
        final deviceUdid = hardware['udid'];
        if (!app.provisionsAllDevices &&
            (deviceUdid is! String || !app.provisionedDeviceIdentifiers.contains(deviceUdid))) {
          failureCount += 1;
          continue;
        }
        final nonce = base64Url.encode(
          List<int>.generate(24, (_) => math.Random.secure().nextInt(256)),
        );
        var installAttempted = false;
        try {
          installAttempted = true;
          final install = await _runDevicectlJson(
            <String>[
              'device',
              'install',
              'app',
              '--device',
              identifier,
              app.path,
            ],
            temporaryDirectory: temporaryDirectory,
            outputName: 'install-$index',
          );
          if (install == null) {
            failureCount += 1;
            continue;
          }
          final launch = await _runDevicectlJson(
            <String>[
              'device',
              'process',
              'launch',
              '--device',
              identifier,
              '--terminate-existing',
              '--environment-variables',
              jsonEncode(<String, String>{
                'OMF_DEVICE_DISPLAY_COLLECTOR_NONCE': nonce,
              }),
              app.bundleIdentifier,
            ],
            temporaryDirectory: temporaryDirectory,
            outputName: 'launch-$index',
          );
          if (launch == null) {
            failureCount += 1;
            continue;
          }
          Map<String, Object?>? payload;
          for (var attempt = 0; attempt < 10; attempt += 1) {
            final destination = Directory(
              '${temporaryDirectory.path}/copy-$index-$attempt',
            )..createSync();
            final copied = await _runDevicectlJson(
              <String>[
                'device',
                'copy',
                'from',
                '--device',
                identifier,
                '--source',
                'Documents/record.json',
                '--destination',
                destination.path,
                '--domain-type',
                'appDataContainer',
                '--domain-identifier',
                app.bundleIdentifier,
              ],
              temporaryDirectory: temporaryDirectory,
              outputName: 'copy-$index-$attempt',
            );
            if (copied != null) {
              final files = destination
                  .listSync(recursive: true)
                  .whereType<File>()
                  .where((file) => file.path.endsWith('record.json'))
                  .toList();
              if (files.length == 1) {
                try {
                  payload = jsonDecode(files.single.readAsStringSync()) as Map<String, Object?>;
                } on FormatException {
                  payload = null;
                }
              }
            }
            if (payload?['nonce'] == nonce) {
              break;
            }
            payload = null;
            await Future<void>.delayed(const Duration(milliseconds: 500));
          }
          final record = payload == null
              ? null
              : _importConnectedIosRecord(
                  payload,
                  expectedNonce: nonce,
                  expectedSourceHash: app.sourceHash,
                  device: device,
                  deviceTypeProvenanceByProductType: deviceTypeProvenanceByProductType,
                );
          if (record == null) {
            failureCount += 1;
          } else {
            records.add(record);
          }
        } finally {
          if (installAttempted) {
            await _runDevicectlJson(
              <String>[
                'device',
                'uninstall',
                'app',
                '--device',
                identifier,
                app.bundleIdentifier,
              ],
              temporaryDirectory: temporaryDirectory,
              outputName: 'uninstall-$index',
            );
          }
        }
      }
      return (
        deviceCount: devices.length,
        eligibleDeviceCount: eligible.length,
        attemptedDeviceCount: eligible.length,
        failureCount: failureCount,
        collectorSourceHash: app.sourceHash,
        records: records,
      );
    } finally {
      temporaryDirectory.deleteSync(recursive: true);
    }
  }

  bool _isEligibleConnectedAppleDevice(Map<String, Object?> device) {
    final properties = device['deviceProperties'];
    final connection = device['connectionProperties'];
    if (properties is! Map<String, Object?> || connection is! Map<String, Object?>) {
      return false;
    }
    final version = properties['osVersionNumber'] as String?;
    final major = int.tryParse(version?.split('.').first ?? '');
    final pairing = (connection['pairingState'] as String?)?.toLowerCase();
    final developerMode = (properties['developerModeStatus'] as String?)?.toLowerCase();
    final bootState = (properties['bootState'] as String?)?.toLowerCase();
    final transport = (connection['transportType'] as String?)?.toLowerCase();
    final tunnelState = (connection['tunnelState'] as String?)?.toLowerCase();
    final allowNetwork = Platform.environment['OMF_DEVICE_DISPLAY_ALLOW_NETWORK_IOS_DEVICES'] == '1';
    return major != null &&
        major >= 26 &&
        pairing != null &&
        pairing.contains('paired') &&
        !pairing.contains('unpaired') &&
        developerMode == 'enabled' &&
        properties['ddiServicesAvailable'] == true &&
        bootState == 'booted' &&
        tunnelState == 'connected' &&
        (transport == 'wired' || (allowNetwork && transport == 'localnetwork'));
  }

  Future<
    ({
      String path,
      String bundleIdentifier,
      String sourceHash,
      bool provisionsAllDevices,
      Set<String> provisionedDeviceIdentifiers,
    })?
  >
  _validatedIosDeviceApp(String rawPath) async {
    final directory = Directory(rawPath);
    if (!directory.isAbsolute || !directory.path.endsWith('.app') || !directory.existsSync()) {
      return null;
    }
    final info = await _readPlist('${directory.path}/Info.plist');
    final bundleIdentifier = info?['CFBundleIdentifier'];
    final executableName = info?['CFBundleExecutable'];
    final minimumVersion = info?['MinimumOSVersion'];
    if (bundleIdentifier is! String ||
        bundleIdentifier.isEmpty ||
        executableName is! String ||
        executableName.isEmpty ||
        minimumVersion is! String ||
        (int.tryParse(minimumVersion.split('.').first) ?? 0) < 26) {
      return null;
    }
    final executable = File('${directory.path}/$executableName');
    final profile = File('${directory.path}/embedded.mobileprovision');
    if (!executable.existsSync() || !profile.existsSync()) {
      return null;
    }
    final collectorDirectory = Directory(
      '${Directory.current.path}/tool/device_display_model/ios_device_collector',
    );
    final sourceHash = _collectorSourceHash(collectorDirectory);
    final generatedHeader = File(
      '${collectorDirectory.path}/collector_source_hash.h',
    );
    final expectedHeader =
        '// Generated by generate_ios_device_collector_provenance.sh.\n'
        '#define OMF_DEVICE_DISPLAY_COLLECTOR_SOURCE_HASH @"$sourceHash"\n';
    if (!generatedHeader.existsSync() || generatedHeader.readAsStringSync() != expectedHeader) {
      return null;
    }
    final forbidden = RegExp(
      'NSSelectorFromString|_displayCornerRadius|legacyDisplayCornerRadius',
      caseSensitive: false,
    );
    final executableText = utf8.decode(
      executable.readAsBytesSync(),
      allowMalformed: true,
    );
    if (!executableText.contains(sourceHash)) {
      return null;
    }
    for (final entity in directory.listSync(recursive: true).whereType<File>()) {
      final text = utf8.decode(entity.readAsBytesSync(), allowMalformed: true);
      if (forbidden.hasMatch(text)) {
        return null;
      }
    }
    final signature = await _runBounded(
      'codesign',
      <String>['--verify', '--deep', '--strict', directory.path],
    );
    final provisioning = await _runBounded(
      'security',
      <String>['cms', '-D', '-i', profile.path],
    );
    if (signature?.exitCode != 0 || provisioning?.exitCode != 0 || provisioning!.stdout.isEmpty) {
      return null;
    }
    final applicationIdentifier = RegExp(
      r'<key>application-identifier</key>\s*<string>([^<]+)</string>',
      dotAll: true,
    ).firstMatch(provisioning.stdout)?.group(1);
    if (applicationIdentifier == null || !applicationIdentifier.endsWith('.$bundleIdentifier')) {
      return null;
    }
    final provisionsAllDevices = RegExp(
      r'<key>ProvisionsAllDevices</key>\s*<true\s*/>',
      dotAll: true,
    ).hasMatch(provisioning.stdout);
    final devicesBlock = RegExp(
      r'<key>ProvisionedDevices</key>\s*<array>(.*?)</array>',
      dotAll: true,
    ).firstMatch(provisioning.stdout)?.group(1);
    final provisionedDeviceIdentifiers = <String>{
      if (devicesBlock != null)
        for (final match in RegExp('<string>([^<]+)</string>').allMatches(devicesBlock)) match.group(1)!,
    };
    if (!provisionsAllDevices && provisionedDeviceIdentifiers.isEmpty) {
      return null;
    }
    return (
      path: directory.path,
      bundleIdentifier: bundleIdentifier,
      sourceHash: sourceHash,
      provisionsAllDevices: provisionsAllDevices,
      provisionedDeviceIdentifiers: provisionedDeviceIdentifiers,
    );
  }

  Future<Map<String, Object?>?> _runDevicectlJson(
    List<String> arguments, {
    required Directory temporaryDirectory,
    required String outputName,
  }) async {
    final output = File('${temporaryDirectory.path}/$outputName.json');
    final executable = Platform.environment['OMF_DEVICE_DISPLAY_DEVICETL'] ?? 'xcrun';
    final prefix = Platform.environment['OMF_DEVICE_DISPLAY_DEVICETL'] == null
        ? const <String>['devicectl']
        : const <String>[];
    final result = await _runBounded(
      executable,
      <String>[
        ...prefix,
        ...arguments,
        '--timeout',
        '30',
        '--json-output',
        output.path,
        '--quiet',
      ],
      timeout: const Duration(seconds: 40),
    );
    if (result == null || result.exitCode != 0 || !output.existsSync()) {
      return null;
    }
    try {
      final decoded = jsonDecode(output.readAsStringSync()) as Map<String, Object?>;
      final info = decoded['info'];
      if (info is! Map<String, Object?> || info['outcome'] != 'success' || info['jsonVersion'] != 3) {
        return null;
      }
      return decoded;
    } on FormatException {
      return null;
    }
  }

  Map<String, Object?>? _importConnectedIosRecord(
    Map<String, Object?> payload, {
    required String expectedNonce,
    required String expectedSourceHash,
    required Map<String, Object?> device,
    required Map<String, ({String generationGroupHash, int chronologyRank})> deviceTypeProvenanceByProductType,
  }) {
    if (payload['protocolVersion'] != 1 ||
        payload['protocolSourceHash'] != expectedSourceHash ||
        payload['platform'] != 'ios' ||
        payload['sourceKind'] != 'ios26_connected_public_uikit_concentric_corner' ||
        payload['nonce'] != expectedNonce) {
      return null;
    }
    const positiveKeys = <String>[
      'physicalWidth',
      'physicalHeight',
      'viewPhysicalWidth',
      'viewPhysicalHeight',
      'devicePixelRatio',
    ];
    const nonNegativeKeys = <String>[
      'viewPaddingLeftPhysical',
      'viewPaddingTopPhysical',
      'viewPaddingRightPhysical',
      'viewPaddingBottomPhysical',
      'topLeftRadiusPhysical',
      'topRightRadiusPhysical',
      'bottomRightRadiusPhysical',
      'bottomLeftRadiusPhysical',
    ];
    if (positiveKeys.any(
          (key) => !_isFiniteNumber(payload[key], positive: true),
        ) ||
        nonNegativeKeys.any(
          (key) => !_isFiniteNumber(payload[key], positive: false),
        )) {
      return null;
    }
    final width = (payload['physicalWidth']! as num).toDouble();
    final height = (payload['physicalHeight']! as num).toDouble();
    final density = (payload['devicePixelRatio']! as num).toDouble();
    final viewWidth = (payload['viewPhysicalWidth']! as num).toDouble();
    final viewHeight = (payload['viewPhysicalHeight']! as num).toDouble();
    final radii = <double>[
      for (final key in const <String>[
        'topLeftRadiusPhysical',
        'topRightRadiusPhysical',
        'bottomRightRadiusPhysical',
        'bottomLeftRadiusPhysical',
      ])
        (payload[key]! as num).toDouble(),
    ];
    if (!_hasPhoneGeometry(
          physicalWidth: width,
          physicalHeight: height,
          devicePixelRatio: density,
        ) ||
        width > height ||
        viewWidth > width ||
        viewHeight > height ||
        radii.any((radius) => radius > math.min(width, height) / 2)) {
      return null;
    }
    final hardware = device['hardwareProperties']! as Map<String, Object?>;
    final familySeed = hardware['productType'] as String?;
    final deviceTypeProvenance = familySeed == null ? null : deviceTypeProvenanceByProductType[familySeed];
    final isSquare = radii.every((radius) => radius == 0);
    return _record(
      platform: 'ios',
      sourceKind: 'ios26_connected_public_uikit_concentric_corner',
      physicalWidth: width,
      physicalHeight: height,
      viewPhysicalWidth: viewWidth,
      viewPhysicalHeight: viewHeight,
      devicePixelRatio: density,
      viewPaddingLeftPhysical: payload['viewPaddingLeftPhysical']! as num,
      viewPaddingTopPhysical: payload['viewPaddingTopPhysical']! as num,
      viewPaddingRightPhysical: payload['viewPaddingRightPhysical']! as num,
      viewPaddingBottomPhysical: payload['viewPaddingBottomPhysical']! as num,
      topRadiusPhysical: (radii[0] + radii[1]) / 2,
      bottomRadiusPhysical: (radii[2] + radii[3]) / 2,
      provenance: <String, Object?>{
        if (familySeed != null)
          'familyGroupHash': DeviceDisplayModelEncoding.groupFingerprint(
            'family-product:$familySeed',
          ),
        if (deviceTypeProvenance != null) ...<String, Object?>{
          'generationGroupHash': deviceTypeProvenance.generationGroupHash,
          'chronologyRank': deviceTypeProvenance.chronologyRank,
        },
        'oemGroupHash': DeviceDisplayModelEncoding.groupFingerprint(
          'oem:apple',
        ),
      },
      labelAuthority: 'ios26_connected_public_uikit_concentric_corner',
      cornerClassification: isSquare ? 'square' : 'rounded',
    );
  }

  Future<String?> _runXcrun(List<String> arguments) async {
    final configured = Platform.environment['OMF_DEVICE_DISPLAY_XCRUN'];
    final testCollectorAllowed = Platform.environment['OMF_DEVICE_DISPLAY_ALLOW_TEST_COLLECTOR'] == '1';
    final configuredFile = configured == null ? null : File(configured);
    final executable =
        testCollectorAllowed && configuredFile != null && configuredFile.isAbsolute && configuredFile.existsSync()
        ? configuredFile.path
        : 'xcrun';
    final result = await _runBounded(
      executable,
      arguments,
      timeout: const Duration(seconds: 30),
    );
    return result?.exitCode == 0 ? result!.stdout : null;
  }

  Future<Map<String, Object?>?> _readPlist(String path) async {
    if (!File(path).existsSync()) {
      return null;
    }
    final result = await _runBounded(
      'plutil',
      ['-convert', 'json', '-o', '-', path],
    );
    if (result == null || result.exitCode != 0) {
      return null;
    }
    return jsonDecode(result.stdout) as Map<String, Object?>;
  }

  Map<String, Object?> _record({
    required String sourceKind,
    required num physicalWidth,
    required num physicalHeight,
    required num? devicePixelRatio,
    required num? viewPaddingTopPhysical,
    required num? viewPaddingBottomPhysical,
    required num topRadiusPhysical,
    required num bottomRadiusPhysical,
    String platform = 'android',
    Map<String, Object?> provenance = const <String, Object?>{},
    int? sourceApiLevel,
    String? labelAuthority,
    String? cornerClassification,
    num? viewPhysicalWidth,
    num? viewPhysicalHeight,
    num? viewPaddingLeftPhysical,
    num? viewPaddingRightPhysical,
    num? systemGestureInsetLeftPhysical,
    num? systemGestureInsetTopPhysical,
    num? systemGestureInsetRightPhysical,
    num? systemGestureInsetBottomPhysical,
    num? displayCutoutWidthPhysical,
    num? displayCutoutHeightPhysical,
    num? displayCutoutCount,
  }) {
    final geometry = <String, Object?>{
      'physicalWidth': physicalWidth,
      'physicalHeight': physicalHeight,
    };
    final geometryHash = DeviceDisplayModelEncoding.fingerprint(geometry);
    final record = <String, Object?>{
      'platform': platform,
      'sourceKind': sourceKind,
      'validationGroup': geometryHash,
      'geometryCollisionGroupHash': geometryHash,
      ...geometry,
      'viewPhysicalWidth': viewPhysicalWidth,
      'viewPhysicalHeight': viewPhysicalHeight,
      'devicePixelRatio': devicePixelRatio,
      'viewPaddingLeftPhysical': viewPaddingLeftPhysical,
      'viewPaddingTopPhysical': viewPaddingTopPhysical,
      'viewPaddingRightPhysical': viewPaddingRightPhysical,
      'viewPaddingBottomPhysical': viewPaddingBottomPhysical,
      'systemGestureInsetLeftPhysical': systemGestureInsetLeftPhysical,
      'systemGestureInsetTopPhysical': systemGestureInsetTopPhysical,
      'systemGestureInsetRightPhysical': systemGestureInsetRightPhysical,
      'systemGestureInsetBottomPhysical': systemGestureInsetBottomPhysical,
      'displayCutoutWidthPhysical': displayCutoutWidthPhysical,
      'displayCutoutHeightPhysical': displayCutoutHeightPhysical,
      'displayCutoutCount': displayCutoutCount,
      'topRadiusPhysical': topRadiusPhysical,
      'bottomRadiusPhysical': bottomRadiusPhysical,
      'sourceApiLevel': sourceApiLevel,
      'labelAuthority': labelAuthority,
      'cornerClassification': cornerClassification,
      ...provenance,
    };
    record['observableCollisionGroupHash'] = DeviceDisplayModelEncoding.fingerprint(<String, Object?>{
      'platform': platform,
      'features': _DeviceDisplayModelAlgorithms().features(record),
    });
    record['familyGroupHash'] ??= geometryHash;
    record.putIfAbsent('chronologyRank', () => null);
    _updateSourceObservationHash(record);
    return record;
  }

  void _updateSourceObservationHash(Map<String, Object?> record) {
    record['sourceObservationHash'] = DeviceDisplayModelEncoding.fingerprint(
      <String, Object?>{
        for (final entry in record.entries)
          if (entry.key != 'maskCollisionGroupHash' && entry.key != 'sourceObservationHash') entry.key: entry.value,
      },
    );
  }

  Map<String, Object?> _anonymousProvenance(String rawValue) {
    return <String, Object?>{
      'familyGroupHash': _hashGroup(
        'family',
        rawValue.trim().toLowerCase(),
      ),
    };
  }

  Future<Map<String, Object?>> _connectedAndroidProvenance(
    String adbPath,
    String serial,
  ) async {
    final values = <String>[];
    for (final property in const [
      'ro.product.manufacturer',
      'ro.product.model',
      'ro.product.device',
    ]) {
      final result = await _runBounded(adbPath, <String>[
        '-s',
        serial,
        'shell',
        'getprop',
        property,
      ]);
      values.add(result?.exitCode == 0 ? result!.stdout.trim() : '');
    }
    final family = values.skip(1).where((value) => value.isNotEmpty).join('-');
    final manufacturer = values.first.toLowerCase();
    return <String, Object?>{
      if (family.isNotEmpty) 'familyGroupHash': _hashGroup('family', family.toLowerCase()),
      if (manufacturer.isNotEmpty) 'oemGroupHash': _hashGroup('oem', manufacturer),
    };
  }

  String _hashGroup(String category, String value) => DeviceDisplayModelEncoding.groupFingerprint('$category:$value');

  int? _integer(String text, String key) {
    final match = RegExp('$key\\s+(\\d+)').firstMatch(text);
    return match == null ? null : int.parse(match.group(1)!);
  }

  static int _compareRecords(
    Map<String, Object?> left,
    Map<String, Object?> right,
  ) => DeviceDisplayModelEncoding.canonicalJson(
    left,
  ).compareTo(DeviceDisplayModelEncoding.canonicalJson(right));
}
