name: oh_my_flutter
description: Empower Flutter with utilities that make development 10x faster.
version: 0.15.0
homepage: https://github.com/Ventairy/oh_my_flutter
repository: https://github.com/Ventairy/oh_my_flutter
issue_tracker: https://github.com/Ventairy/oh_my_flutter/issues
documentation: https://pub.dev/documentation/oh_my_flutter/latest/
topics:
  - flutter
  - utilities
  - extensions
  - widgets

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  clock: ^1.1.2
  code_assets: ^2.0.0
  dio: ^5.10.0
  flutter:
    sdk: flutter
  hooks: ^2.2.0
  internet_connection_checker_plus: ^3.1.0
  meta: ^1.18.0
  native_toolchain_c: ^0.19.4
  platform: ^3.1.6
  record_use: ^1.1.1
  url_launcher: ^6.3.1

dev_dependencies:
  alchemist: ^0.14.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  pigeon: 28.0.0
  very_good_analysis: ">=7.0.0 <11.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
  plugin:
    platforms:
      android:
        package: dev.ventairy.oh_my_flutter
        pluginClass: OhMyFlutterPlugin
      ios:
        pluginClass: OhMyFlutterPlugin
  uses-material-design: true
