// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length && a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Identifies the Flutter view geometry requesting platform display evidence.
class DeviceDisplayGeometryMessage {
  DeviceDisplayGeometryMessage({
    required this.displayWidth,
    required this.displayHeight,
    required this.viewWidth,
    required this.viewHeight,
  });

  /// The full Flutter display width in physical pixels.
  double displayWidth;

  /// The full Flutter display height in physical pixels.
  double displayHeight;

  /// The requesting Flutter view width in physical pixels.
  double viewWidth;

  /// The requesting Flutter view height in physical pixels.
  double viewHeight;

  List<Object?> _toList() {
    return <Object?>[
      displayWidth,
      displayHeight,
      viewWidth,
      viewHeight,
    ];
  }

  Object encode() {
    return _toList();
  }

  static DeviceDisplayGeometryMessage decode(Object result) {
    result as List<Object?>;
    return DeviceDisplayGeometryMessage(
      displayWidth: result[0]! as double,
      displayHeight: result[1]! as double,
      viewWidth: result[2]! as double,
      viewHeight: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeviceDisplayGeometryMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(displayWidth, other.displayWidth) &&
        _deepEquals(displayHeight, other.displayHeight) &&
        _deepEquals(viewWidth, other.viewWidth) &&
        _deepEquals(viewHeight, other.viewHeight);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DeviceDisplayGeometryMessage(displayWidth: $displayWidth, displayHeight: $displayHeight, viewWidth: $viewWidth, viewHeight: $viewHeight)';
  }
}

/// Carries platform display corner radii across the platform channel.
class DeviceDisplayCornerRadiiMessage {
  DeviceDisplayCornerRadiiMessage({
    required this.topLeft,
    required this.topRight,
    required this.bottomRight,
    required this.bottomLeft,
  });

  /// The top-left corner radius in physical pixels.
  double topLeft;

  /// The top-right corner radius in physical pixels.
  double topRight;

  /// The bottom-right corner radius in physical pixels.
  double bottomRight;

  /// The bottom-left corner radius in physical pixels.
  double bottomLeft;

  List<Object?> _toList() {
    return <Object?>[
      topLeft,
      topRight,
      bottomRight,
      bottomLeft,
    ];
  }

  Object encode() {
    return _toList();
  }

  static DeviceDisplayCornerRadiiMessage decode(Object result) {
    result as List<Object?>;
    return DeviceDisplayCornerRadiiMessage(
      topLeft: result[0]! as double,
      topRight: result[1]! as double,
      bottomRight: result[2]! as double,
      bottomLeft: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeviceDisplayCornerRadiiMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(topLeft, other.topLeft) &&
        _deepEquals(topRight, other.topRight) &&
        _deepEquals(bottomRight, other.bottomRight) &&
        _deepEquals(bottomLeft, other.bottomLeft);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DeviceDisplayCornerRadiiMessage(topLeft: $topLeft, topRight: $topRight, bottomRight: $bottomRight, bottomLeft: $bottomLeft)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is DeviceDisplayGeometryMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is DeviceDisplayCornerRadiiMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return DeviceDisplayGeometryMessage.decode(readValue(buffer)!);
      case 130:
        return DeviceDisplayCornerRadiiMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Defines the host operations used by the display implementation.
class DeviceDisplayHostApi {
  /// Constructor for [DeviceDisplayHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DeviceDisplayHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Returns the current display corner radii in physical pixels.
  Future<DeviceDisplayCornerRadiiMessage?> getCornerRadii(DeviceDisplayGeometryMessage geometry) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.oh_my_flutter.DeviceDisplayHostApi.getCornerRadii$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[geometry]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as DeviceDisplayCornerRadiiMessage?;
  }
}
