// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum DeviceDisplayPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Identifies the Flutter view geometry requesting platform display evidence.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DeviceDisplayGeometryMessage: Hashable, CustomStringConvertible {
  /// The full Flutter display width in physical pixels.
  var displayWidth: Double
  /// The full Flutter display height in physical pixels.
  var displayHeight: Double
  /// The requesting Flutter view width in physical pixels.
  var viewWidth: Double
  /// The requesting Flutter view height in physical pixels.
  var viewHeight: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeviceDisplayGeometryMessage? {
    let displayWidth = pigeonVar_list[0] as! Double
    let displayHeight = pigeonVar_list[1] as! Double
    let viewWidth = pigeonVar_list[2] as! Double
    let viewHeight = pigeonVar_list[3] as! Double

    return DeviceDisplayGeometryMessage(
      displayWidth: displayWidth,
      displayHeight: displayHeight,
      viewWidth: viewWidth,
      viewHeight: viewHeight
    )
  }
  func toList() -> [Any?] {
    return [
      displayWidth,
      displayHeight,
      viewWidth,
      viewHeight,
    ]
  }
  static func == (lhs: DeviceDisplayGeometryMessage, rhs: DeviceDisplayGeometryMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DeviceDisplayPigeonInternal.deepEquals(lhs.displayWidth, rhs.displayWidth) && DeviceDisplayPigeonInternal.deepEquals(lhs.displayHeight, rhs.displayHeight) && DeviceDisplayPigeonInternal.deepEquals(lhs.viewWidth, rhs.viewWidth) && DeviceDisplayPigeonInternal.deepEquals(lhs.viewHeight, rhs.viewHeight)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DeviceDisplayGeometryMessage")
    DeviceDisplayPigeonInternal.deepHash(value: displayWidth, hasher: &hasher)
    DeviceDisplayPigeonInternal.deepHash(value: displayHeight, hasher: &hasher)
    DeviceDisplayPigeonInternal.deepHash(value: viewWidth, hasher: &hasher)
    DeviceDisplayPigeonInternal.deepHash(value: viewHeight, hasher: &hasher)
  }

  public var description: String {
    return "DeviceDisplayGeometryMessage(displayWidth: \(String(describing: displayWidth)), displayHeight: \(String(describing: displayHeight)), viewWidth: \(String(describing: viewWidth)), viewHeight: \(String(describing: viewHeight)))"
  }
}

/// Carries platform display corner radii across the platform channel.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DeviceDisplayCornerRadiiMessage: Hashable, CustomStringConvertible {
  /// The top-left corner radius in physical pixels.
  var topLeft: Double
  /// The top-right corner radius in physical pixels.
  var topRight: Double
  /// The bottom-right corner radius in physical pixels.
  var bottomRight: Double
  /// The bottom-left corner radius in physical pixels.
  var bottomLeft: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeviceDisplayCornerRadiiMessage? {
    let topLeft = pigeonVar_list[0] as! Double
    let topRight = pigeonVar_list[1] as! Double
    let bottomRight = pigeonVar_list[2] as! Double
    let bottomLeft = pigeonVar_list[3] as! Double

    return DeviceDisplayCornerRadiiMessage(
      topLeft: topLeft,
      topRight: topRight,
      bottomRight: bottomRight,
      bottomLeft: bottomLeft
    )
  }
  func toList() -> [Any?] {
    return [
      topLeft,
      topRight,
      bottomRight,
      bottomLeft,
    ]
  }
  static func == (lhs: DeviceDisplayCornerRadiiMessage, rhs: DeviceDisplayCornerRadiiMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DeviceDisplayPigeonInternal.deepEquals(lhs.topLeft, rhs.topLeft) && DeviceDisplayPigeonInternal.deepEquals(lhs.topRight, rhs.topRight) && DeviceDisplayPigeonInternal.deepEquals(lhs.bottomRight, rhs.bottomRight) && DeviceDisplayPigeonInternal.deepEquals(lhs.bottomLeft, rhs.bottomLeft)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DeviceDisplayCornerRadiiMessage")
    DeviceDisplayPigeonInternal.deepHash(value: topLeft, hasher: &hasher)
    DeviceDisplayPigeonInternal.deepHash(value: topRight, hasher: &hasher)
    DeviceDisplayPigeonInternal.deepHash(value: bottomRight, hasher: &hasher)
    DeviceDisplayPigeonInternal.deepHash(value: bottomLeft, hasher: &hasher)
  }

  public var description: String {
    return "DeviceDisplayCornerRadiiMessage(topLeft: \(String(describing: topLeft)), topRight: \(String(describing: topRight)), bottomRight: \(String(describing: bottomRight)), bottomLeft: \(String(describing: bottomLeft)))"
  }
}

private class DeviceDisplayPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return DeviceDisplayGeometryMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return DeviceDisplayCornerRadiiMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class DeviceDisplayPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DeviceDisplayGeometryMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? DeviceDisplayCornerRadiiMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class DeviceDisplayPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return DeviceDisplayPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return DeviceDisplayPigeonCodecWriter(data: data)
  }
}

class DeviceDisplayPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = DeviceDisplayPigeonCodec(readerWriter: DeviceDisplayPigeonCodecReaderWriter())
}

/// Defines the host operations used by the display implementation.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DeviceDisplayHostApi {
  /// Returns the current display corner radii in physical pixels.
  func getCornerRadii(geometry: DeviceDisplayGeometryMessage) throws -> DeviceDisplayCornerRadiiMessage?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DeviceDisplayHostApiSetup {
  static var codec: FlutterStandardMessageCodec { DeviceDisplayPigeonCodec.shared }
  /// Sets up an instance of `DeviceDisplayHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DeviceDisplayHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Returns the current display corner radii in physical pixels.
    let getCornerRadiiChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.oh_my_flutter.DeviceDisplayHostApi.getCornerRadii\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCornerRadiiChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let geometryArg = args[0] as! DeviceDisplayGeometryMessage
        do {
          let result = try api.getCornerRadii(geometry: geometryArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCornerRadiiChannel.setMessageHandler(nil)
    }
  }
}
