// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class NativeSelectableTextPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "NativeSelectableTextPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? NativeSelectableTextPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> NativeSelectableTextPigeonError {
  return NativeSelectableTextPigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum NativeSelectableTextPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Carries a Flutter logical-pixel rectangle to a native menu host.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeSelectableTextRectangleMessage: Hashable, CustomStringConvertible {
  /// The horizontal coordinate of the leading edge.
  var left: Double
  /// The vertical coordinate of the upper edge.
  var top: Double
  /// The horizontal coordinate of the trailing edge.
  var right: Double
  /// The vertical coordinate of the lower edge.
  var bottom: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeSelectableTextRectangleMessage? {
    let left = pigeonVar_list[0] as! Double
    let top = pigeonVar_list[1] as! Double
    let right = pigeonVar_list[2] as! Double
    let bottom = pigeonVar_list[3] as! Double

    return NativeSelectableTextRectangleMessage(
      left: left,
      top: top,
      right: right,
      bottom: bottom
    )
  }
  func toList() -> [Any?] {
    return [
      left,
      top,
      right,
      bottom,
    ]
  }
  static func == (lhs: NativeSelectableTextRectangleMessage, rhs: NativeSelectableTextRectangleMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeSelectableTextPigeonInternal.deepEquals(lhs.left, rhs.left) && NativeSelectableTextPigeonInternal.deepEquals(lhs.top, rhs.top) && NativeSelectableTextPigeonInternal.deepEquals(lhs.right, rhs.right) && NativeSelectableTextPigeonInternal.deepEquals(lhs.bottom, rhs.bottom)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeSelectableTextRectangleMessage")
    NativeSelectableTextPigeonInternal.deepHash(value: left, hasher: &hasher)
    NativeSelectableTextPigeonInternal.deepHash(value: top, hasher: &hasher)
    NativeSelectableTextPigeonInternal.deepHash(value: right, hasher: &hasher)
    NativeSelectableTextPigeonInternal.deepHash(value: bottom, hasher: &hasher)
  }

  public var description: String {
    return "NativeSelectableTextRectangleMessage(left: \(String(describing: left)), top: \(String(describing: top)), right: \(String(describing: right)), bottom: \(String(describing: bottom)))"
  }
}

/// Carries a Flutter logical-pixel point to a native menu host.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeSelectableTextPointMessage: Hashable, CustomStringConvertible {
  /// The horizontal coordinate.
  var dx: Double
  /// The vertical coordinate.
  var dy: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeSelectableTextPointMessage? {
    let dx = pigeonVar_list[0] as! Double
    let dy = pigeonVar_list[1] as! Double

    return NativeSelectableTextPointMessage(
      dx: dx,
      dy: dy
    )
  }
  func toList() -> [Any?] {
    return [
      dx,
      dy,
    ]
  }
  static func == (lhs: NativeSelectableTextPointMessage, rhs: NativeSelectableTextPointMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeSelectableTextPigeonInternal.deepEquals(lhs.dx, rhs.dx) && NativeSelectableTextPigeonInternal.deepEquals(lhs.dy, rhs.dy)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeSelectableTextPointMessage")
    NativeSelectableTextPigeonInternal.deepHash(value: dx, hasher: &hasher)
    NativeSelectableTextPigeonInternal.deepHash(value: dy, hasher: &hasher)
  }

  public var description: String {
    return "NativeSelectableTextPointMessage(dx: \(String(describing: dx)), dy: \(String(describing: dy)))"
  }
}

/// Describes one labeled native selection-menu command.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeSelectableTextMenuItemMessage: Hashable, CustomStringConvertible {
  /// The identifier returned when the person chooses this item.
  var identifier: Int64
  /// The localized label displayed by the platform menu.
  var label: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeSelectableTextMenuItemMessage? {
    let identifier = pigeonVar_list[0] as! Int64
    let label = pigeonVar_list[1] as! String

    return NativeSelectableTextMenuItemMessage(
      identifier: identifier,
      label: label
    )
  }
  func toList() -> [Any?] {
    return [
      identifier,
      label,
    ]
  }
  static func == (lhs: NativeSelectableTextMenuItemMessage, rhs: NativeSelectableTextMenuItemMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeSelectableTextPigeonInternal.deepEquals(lhs.identifier, rhs.identifier) && NativeSelectableTextPigeonInternal.deepEquals(lhs.label, rhs.label)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeSelectableTextMenuItemMessage")
    NativeSelectableTextPigeonInternal.deepHash(value: identifier, hasher: &hasher)
    NativeSelectableTextPigeonInternal.deepHash(value: label, hasher: &hasher)
  }

  public var description: String {
    return "NativeSelectableTextMenuItemMessage(identifier: \(String(describing: identifier)), label: \(String(describing: label)))"
  }
}

/// Describes one native selection-menu presentation.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeSelectableTextMenuRequestMessage: Hashable, CustomStringConvertible {
  /// Identifies this presentation and rejects callbacks from older menus.
  var sessionIdentifier: Int64
  /// The selected glyph bounds in Flutter global logical pixels.
  var selectionRectangle: NativeSelectableTextRectangleMessage
  /// The preferred pointer or keyboard anchor in global logical pixels.
  var primaryAnchor: NativeSelectableTextPointMessage
  /// The ordered commands shown by the menu.
  var items: [NativeSelectableTextMenuItemMessage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeSelectableTextMenuRequestMessage? {
    let sessionIdentifier = pigeonVar_list[0] as! Int64
    let selectionRectangle = pigeonVar_list[1] as! NativeSelectableTextRectangleMessage
    let primaryAnchor = pigeonVar_list[2] as! NativeSelectableTextPointMessage
    let items = pigeonVar_list[3] as! [NativeSelectableTextMenuItemMessage]

    return NativeSelectableTextMenuRequestMessage(
      sessionIdentifier: sessionIdentifier,
      selectionRectangle: selectionRectangle,
      primaryAnchor: primaryAnchor,
      items: items
    )
  }
  func toList() -> [Any?] {
    return [
      sessionIdentifier,
      selectionRectangle,
      primaryAnchor,
      items,
    ]
  }
  static func == (lhs: NativeSelectableTextMenuRequestMessage, rhs: NativeSelectableTextMenuRequestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeSelectableTextPigeonInternal.deepEquals(lhs.sessionIdentifier, rhs.sessionIdentifier) && NativeSelectableTextPigeonInternal.deepEquals(lhs.selectionRectangle, rhs.selectionRectangle) && NativeSelectableTextPigeonInternal.deepEquals(lhs.primaryAnchor, rhs.primaryAnchor) && NativeSelectableTextPigeonInternal.deepEquals(lhs.items, rhs.items)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeSelectableTextMenuRequestMessage")
    NativeSelectableTextPigeonInternal.deepHash(value: sessionIdentifier, hasher: &hasher)
    NativeSelectableTextPigeonInternal.deepHash(value: selectionRectangle, hasher: &hasher)
    NativeSelectableTextPigeonInternal.deepHash(value: primaryAnchor, hasher: &hasher)
    NativeSelectableTextPigeonInternal.deepHash(value: items, hasher: &hasher)
  }

  public var description: String {
    return "NativeSelectableTextMenuRequestMessage(sessionIdentifier: \(String(describing: sessionIdentifier)), selectionRectangle: \(String(describing: selectionRectangle)), primaryAnchor: \(String(describing: primaryAnchor)), items: \(String(describing: items)))"
  }
}

private class NativeSelectableTextPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeSelectableTextRectangleMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return NativeSelectableTextPointMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return NativeSelectableTextMenuItemMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeSelectableTextMenuRequestMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NativeSelectableTextPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeSelectableTextRectangleMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NativeSelectableTextPointMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativeSelectableTextMenuItemMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeSelectableTextMenuRequestMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NativeSelectableTextPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeSelectableTextPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeSelectableTextPigeonCodecWriter(data: data)
  }
}

class NativeSelectableTextPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NativeSelectableTextPigeonCodec(readerWriter: NativeSelectableTextPigeonCodecReaderWriter())
}

/// Presents selection commands through the current native host.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeSelectableTextMenuHostApi {
  /// Shows a native menu and reports whether presentation was accepted.
  func show(request: NativeSelectableTextMenuRequestMessage) throws -> Bool
  /// Updates an already visible native menu.
  func update(request: NativeSelectableTextMenuRequestMessage) throws -> Bool
  /// Updates only the current selection rectangle and primary anchor.
  ///
  /// [geometry] contains left, top, right, bottom, anchor dx, and anchor dy in
  /// Flutter global logical pixels, in that order.
  func updateGeometry(sessionIdentifier: Int64, geometry: FlutterStandardTypedData) throws -> Bool
  /// Hides the menu for [sessionIdentifier] when it is still current.
  func hide(sessionIdentifier: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeSelectableTextMenuHostApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeSelectableTextPigeonCodec.shared }
  /// Sets up an instance of `NativeSelectableTextMenuHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeSelectableTextMenuHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Shows a native menu and reports whether presentation was accepted.
    let showChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.show\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! NativeSelectableTextMenuRequestMessage
        do {
          let result = try api.show(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showChannel.setMessageHandler(nil)
    }
    /// Updates an already visible native menu.
    let updateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.update\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! NativeSelectableTextMenuRequestMessage
        do {
          let result = try api.update(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateChannel.setMessageHandler(nil)
    }
    /// Updates only the current selection rectangle and primary anchor.
    ///
    /// [geometry] contains left, top, right, bottom, anchor dx, and anchor dy in
    /// Flutter global logical pixels, in that order.
    let updateGeometryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.updateGeometry\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateGeometryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! Int64
        let geometryArg = args[1] as! FlutterStandardTypedData
        do {
          let result = try api.updateGeometry(sessionIdentifier: sessionIdentifierArg, geometry: geometryArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateGeometryChannel.setMessageHandler(nil)
    }
    /// Hides the menu for [sessionIdentifier] when it is still current.
    let hideChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.hide\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hideChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! Int64
        do {
          try api.hide(sessionIdentifier: sessionIdentifierArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hideChannel.setMessageHandler(nil)
    }
  }
}

/// Delivers native selection-menu events to Flutter.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol NativeSelectableTextMenuFlutterApiProtocol {
  /// Invokes a command previously sent for [sessionIdentifier].
  func onAction(sessionIdentifier sessionIdentifierArg: Int64, actionIdentifier actionIdentifierArg: Int64, completion: @escaping (Result<Void, NativeSelectableTextPigeonError>) -> Void)
  /// Reports that a menu closed and whether a command caused the dismissal.
  func onDismissed(sessionIdentifier sessionIdentifierArg: Int64, actionInvoked actionInvokedArg: Bool, completion: @escaping (Result<Void, NativeSelectableTextPigeonError>) -> Void)
}
class NativeSelectableTextMenuFlutterApi: NativeSelectableTextMenuFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: NativeSelectableTextPigeonCodec {
    return NativeSelectableTextPigeonCodec.shared
  }
  /// Invokes a command previously sent for [sessionIdentifier].
  func onAction(sessionIdentifier sessionIdentifierArg: Int64, actionIdentifier actionIdentifierArg: Int64, completion: @escaping (Result<Void, NativeSelectableTextPigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuFlutterApi.onAction\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sessionIdentifierArg, actionIdentifierArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(NativeSelectableTextPigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Reports that a menu closed and whether a command caused the dismissal.
  func onDismissed(sessionIdentifier sessionIdentifierArg: Int64, actionInvoked actionInvokedArg: Bool, completion: @escaping (Result<Void, NativeSelectableTextPigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuFlutterApi.onDismissed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sessionIdentifierArg, actionInvokedArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(NativeSelectableTextPigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
