// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length && a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Carries a Flutter logical-pixel rectangle to a native menu host.
class NativeSelectableTextRectangleMessage {
  NativeSelectableTextRectangleMessage({
    required this.left,
    required this.top,
    required this.right,
    required this.bottom,
  });

  /// The horizontal coordinate of the leading edge.
  double left;

  /// The vertical coordinate of the upper edge.
  double top;

  /// The horizontal coordinate of the trailing edge.
  double right;

  /// The vertical coordinate of the lower edge.
  double bottom;

  List<Object?> _toList() {
    return <Object?>[
      left,
      top,
      right,
      bottom,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeSelectableTextRectangleMessage decode(Object result) {
    result as List<Object?>;
    return NativeSelectableTextRectangleMessage(
      left: result[0]! as double,
      top: result[1]! as double,
      right: result[2]! as double,
      bottom: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeSelectableTextRectangleMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(left, other.left) &&
        _deepEquals(top, other.top) &&
        _deepEquals(right, other.right) &&
        _deepEquals(bottom, other.bottom);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeSelectableTextRectangleMessage(left: $left, top: $top, right: $right, bottom: $bottom)';
  }
}

/// Carries a Flutter logical-pixel point to a native menu host.
class NativeSelectableTextPointMessage {
  NativeSelectableTextPointMessage({
    required this.dx,
    required this.dy,
  });

  /// The horizontal coordinate.
  double dx;

  /// The vertical coordinate.
  double dy;

  List<Object?> _toList() {
    return <Object?>[
      dx,
      dy,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeSelectableTextPointMessage decode(Object result) {
    result as List<Object?>;
    return NativeSelectableTextPointMessage(
      dx: result[0]! as double,
      dy: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeSelectableTextPointMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(dx, other.dx) && _deepEquals(dy, other.dy);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeSelectableTextPointMessage(dx: $dx, dy: $dy)';
  }
}

/// Describes one labeled native selection-menu command.
class NativeSelectableTextMenuItemMessage {
  NativeSelectableTextMenuItemMessage({
    required this.identifier,
    required this.label,
  });

  /// The identifier returned when the person chooses this item.
  int identifier;

  /// The localized label displayed by the platform menu.
  String label;

  List<Object?> _toList() {
    return <Object?>[
      identifier,
      label,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeSelectableTextMenuItemMessage decode(Object result) {
    result as List<Object?>;
    return NativeSelectableTextMenuItemMessage(
      identifier: result[0]! as int,
      label: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeSelectableTextMenuItemMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(identifier, other.identifier) && _deepEquals(label, other.label);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeSelectableTextMenuItemMessage(identifier: $identifier, label: $label)';
  }
}

/// Describes one native selection-menu presentation.
class NativeSelectableTextMenuRequestMessage {
  NativeSelectableTextMenuRequestMessage({
    required this.sessionIdentifier,
    required this.selectionRectangle,
    required this.primaryAnchor,
    required this.items,
  });

  /// Identifies this presentation and rejects callbacks from older menus.
  int sessionIdentifier;

  /// The selected glyph bounds in Flutter global logical pixels.
  NativeSelectableTextRectangleMessage selectionRectangle;

  /// The preferred pointer or keyboard anchor in global logical pixels.
  NativeSelectableTextPointMessage primaryAnchor;

  /// The ordered commands shown by the menu.
  List<NativeSelectableTextMenuItemMessage> items;

  List<Object?> _toList() {
    return <Object?>[
      sessionIdentifier,
      selectionRectangle,
      primaryAnchor,
      items,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeSelectableTextMenuRequestMessage decode(Object result) {
    result as List<Object?>;
    return NativeSelectableTextMenuRequestMessage(
      sessionIdentifier: result[0]! as int,
      selectionRectangle: result[1]! as NativeSelectableTextRectangleMessage,
      primaryAnchor: result[2]! as NativeSelectableTextPointMessage,
      items: (result[3]! as List<Object?>).cast<NativeSelectableTextMenuItemMessage>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeSelectableTextMenuRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionIdentifier, other.sessionIdentifier) &&
        _deepEquals(selectionRectangle, other.selectionRectangle) &&
        _deepEquals(primaryAnchor, other.primaryAnchor) &&
        _deepEquals(items, other.items);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeSelectableTextMenuRequestMessage(sessionIdentifier: $sessionIdentifier, selectionRectangle: $selectionRectangle, primaryAnchor: $primaryAnchor, items: $items)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is NativeSelectableTextRectangleMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is NativeSelectableTextPointMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is NativeSelectableTextMenuItemMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is NativeSelectableTextMenuRequestMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NativeSelectableTextRectangleMessage.decode(readValue(buffer)!);
      case 130:
        return NativeSelectableTextPointMessage.decode(readValue(buffer)!);
      case 131:
        return NativeSelectableTextMenuItemMessage.decode(readValue(buffer)!);
      case 132:
        return NativeSelectableTextMenuRequestMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Presents selection commands through the current native host.
class NativeSelectableTextMenuHostApi {
  /// Constructor for [NativeSelectableTextMenuHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeSelectableTextMenuHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Shows a native menu and reports whether presentation was accepted.
  Future<bool> show(NativeSelectableTextMenuRequestMessage request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.show$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Updates an already visible native menu.
  Future<bool> update(NativeSelectableTextMenuRequestMessage request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.update$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Updates only the current selection rectangle and primary anchor.
  ///
  /// [geometry] contains left, top, right, bottom, anchor dx, and anchor dy in
  /// Flutter global logical pixels, in that order.
  Future<bool> updateGeometry(int sessionIdentifier, Float64List geometry) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.updateGeometry$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionIdentifier, geometry]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Hides the menu for [sessionIdentifier] when it is still current.
  Future<void> hide(int sessionIdentifier) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.hide$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionIdentifier]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

/// Delivers native selection-menu events to Flutter.
abstract class NativeSelectableTextMenuFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Invokes a command previously sent for [sessionIdentifier].
  Future<void> onAction(int sessionIdentifier, int actionIdentifier);

  /// Reports that a menu closed and whether a command caused the dismissal.
  Future<void> onDismissed(int sessionIdentifier, bool actionInvoked);

  static void setUp(
    NativeSelectableTextMenuFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuFlutterApi.onAction$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_sessionIdentifier = args[0]! as int;
          final int arg_actionIdentifier = args[1]! as int;
          try {
            await api.onAction(arg_sessionIdentifier, arg_actionIdentifier);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuFlutterApi.onDismissed$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_sessionIdentifier = args[0]! as int;
          final bool arg_actionInvoked = args[1]! as bool;
          try {
            await api.onDismissed(arg_sessionIdentifier, arg_actionInvoked);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
