// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length && a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Describes a failure returned by the Android location implementation.
enum AndroidDeviceLocationFailure {
  /// Android's system location service is disabled.
  servicesDisabled,

  /// Foreground location permission is not granted.
  permissionDenied,

  /// Foreground location permission must be changed in system settings.
  permissionPermanentlyDenied,

  /// Required Android host configuration is missing.
  configurationMissing,

  /// Android could not complete a native operation.
  operationUnavailable,

  /// Android could not provide usable coordinates.
  coordinatesUnavailable,
}

/// Describes Android's foreground-location permission state.
enum AndroidDeviceLocationPermissionStatus {
  /// Foreground location permission can be requested.
  denied,

  /// Foreground location permission must be changed in system settings.
  deniedForever,

  /// Location access is available while the application is in use.
  whileInUse,
}

/// Carries Android coordinates across the package's platform channel.
class AndroidDeviceCoordinates {
  AndroidDeviceCoordinates({
    required this.latitude,
    required this.longitude,
    required this.accuracy,
  });

  /// The latitude in degrees.
  double latitude;

  /// The longitude in degrees.
  double longitude;

  /// The estimated horizontal uncertainty in meters.
  double accuracy;

  List<Object?> _toList() {
    return <Object?>[
      latitude,
      longitude,
      accuracy,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AndroidDeviceCoordinates decode(Object result) {
    result as List<Object?>;
    return AndroidDeviceCoordinates(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
      accuracy: result[2]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidDeviceCoordinates || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(latitude, other.latitude) &&
        _deepEquals(longitude, other.longitude) &&
        _deepEquals(accuracy, other.accuracy);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidDeviceCoordinates(latitude: $latitude, longitude: $longitude, accuracy: $accuracy)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is AndroidDeviceLocationFailure) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is AndroidDeviceLocationPermissionStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is AndroidDeviceCoordinates) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidDeviceLocationFailure.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidDeviceLocationPermissionStatus.values[value];
      case 131:
        return AndroidDeviceCoordinates.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Defines the Android host operations used by the location implementation.
class AndroidDeviceLocationApi {
  /// Constructor for [AndroidDeviceLocationApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AndroidDeviceLocationApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Reports whether Android's system location service is enabled.
  Future<bool> isServiceEnabled() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.oh_my_flutter.AndroidDeviceLocationApi.isServiceEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Reports the current Android foreground-location permission.
  Future<AndroidDeviceLocationPermissionStatus> checkPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.oh_my_flutter.AndroidDeviceLocationApi.checkPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AndroidDeviceLocationPermissionStatus;
  }

  /// Requests Android foreground-location permission.
  Future<AndroidDeviceLocationPermissionStatus> requestPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.oh_my_flutter.AndroidDeviceLocationApi.requestPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AndroidDeviceLocationPermissionStatus;
  }

  /// Retrieves the current Android device coordinates.
  Future<AndroidDeviceCoordinates> getCurrentCoordinates() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.oh_my_flutter.AndroidDeviceLocationApi.getCurrentCoordinates$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AndroidDeviceCoordinates;
  }

  /// Opens Android's application-details settings page.
  Future<bool> openLocationSettings() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.oh_my_flutter.AndroidDeviceLocationApi.openLocationSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}
