#!/bin/zsh

set -euo pipefail

script_directory="${0:A:h}"
source_directory="$script_directory/ios_device_collector"
source_manifest="$source_directory/source_manifest.txt"
header="$source_directory/collector_source_hash.h"
check=false
if [[ ${1:-} == "--check" ]]; then
  check=true
  shift
fi
if [[ $# -ne 0 ]]; then
  print -u2 "usage: $0 [--check]"
  exit 64
fi

if [[ ! -f "$source_manifest" ]] ||
    ! LC_ALL=C sort -c "$source_manifest" 2>/dev/null ||
    [[ "$(LC_ALL=C sort -u "$source_manifest" | wc -l | tr -d ' ')" != \
      "$(wc -l < "$source_manifest" | tr -d ' ')" ]] ||
    rg -n '(^/|^\.\.?/|/\.\.?/|^\.\.?$|//|\\)' "$source_manifest" >/dev/null; then
  print -u2 "The connected-iOS source manifest is invalid."
  exit 1
fi
while IFS= read -r relative; do
  if [[ -z "$relative" || ! -f "$source_directory/$relative" ]]; then
    print -u2 "The connected-iOS source manifest references a missing file."
    exit 1
  fi
done < "$source_manifest"
if ! diff -u \
    <(
      {
        print -r -- source_manifest.txt
        command cat "$source_manifest"
      } | LC_ALL=C sort
    ) \
    <(
      find "$source_directory" -type f \
        ! -name collector_source_hash.h \
        -print |
        sed "s#^$source_directory/##" |
        LC_ALL=C sort
    ) >/dev/null; then
  print -u2 "The connected-iOS source manifest is incomplete."
  exit 1
fi

source_hash="$({
  for source_file in "$source_manifest"; do
    relative="${source_file#$source_directory/}"
    printf '%s\0' "$relative"
    command cat "$source_file"
    printf '\0'
  done
  while IFS= read -r relative; do
    [[ -z "$relative" ]] && continue
    source_file="$source_directory/$relative"
    printf '%s\0' "$relative"
    command cat "$source_file"
    printf '\0'
  done < "$source_manifest"
} | shasum -a 256 | awk '{print "sha256:" $1}')"
expected="// Generated by generate_ios_device_collector_provenance.sh.
#define OMF_DEVICE_DISPLAY_COLLECTOR_SOURCE_HASH @\"$source_hash\""

if $check; then
  if [[ ! -f "$header" || "$(<"$header")" != "$expected" ]]; then
    print -u2 "The connected-iOS collector source hash is stale."
    exit 1
  fi
  print -r -- "$source_hash"
  exit 0
fi

temporary_header="$(mktemp "$source_directory/collector-source-hash.XXXXXX")"
print -r -- "$expected" > "$temporary_header"
mv "$temporary_header" "$header"
print -r -- "$source_hash"
