// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.ventairy.oh_my_flutter.device_display

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AndroidDeviceDisplayPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Identifies the Flutter view geometry requesting Android display evidence.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AndroidDeviceDisplayGeometry (
  /** The full Flutter display width in physical pixels. */
  val displayWidth: Double,
  /** The full Flutter display height in physical pixels. */
  val displayHeight: Double,
  /** The requesting Flutter view width in physical pixels. */
  val viewWidth: Double,
  /** The requesting Flutter view height in physical pixels. */
  val viewHeight: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidDeviceDisplayGeometry {
      val displayWidth = pigeonVar_list[0] as Double
      val displayHeight = pigeonVar_list[1] as Double
      val viewWidth = pigeonVar_list[2] as Double
      val viewHeight = pigeonVar_list[3] as Double
      return AndroidDeviceDisplayGeometry(displayWidth, displayHeight, viewWidth, viewHeight)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      displayWidth,
      displayHeight,
      viewWidth,
      viewHeight,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidDeviceDisplayGeometry
    return AndroidDeviceDisplayPigeonUtils.deepEquals(this.displayWidth, other.displayWidth) && AndroidDeviceDisplayPigeonUtils.deepEquals(this.displayHeight, other.displayHeight) && AndroidDeviceDisplayPigeonUtils.deepEquals(this.viewWidth, other.viewWidth) && AndroidDeviceDisplayPigeonUtils.deepEquals(this.viewHeight, other.viewHeight)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidDeviceDisplayPigeonUtils.deepHash(this.displayWidth)
    result = 31 * result + AndroidDeviceDisplayPigeonUtils.deepHash(this.displayHeight)
    result = 31 * result + AndroidDeviceDisplayPigeonUtils.deepHash(this.viewWidth)
    result = 31 * result + AndroidDeviceDisplayPigeonUtils.deepHash(this.viewHeight)
    return result
  }
  override fun toString(): String {
    return "AndroidDeviceDisplayGeometry(displayWidth=$displayWidth, displayHeight=$displayHeight, viewWidth=$viewWidth, viewHeight=$viewHeight)"
  }
}

/**
 * Carries Android display corner radii across the platform channel.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AndroidDeviceDisplayCornerRadii (
  /** The top-left corner radius in physical pixels. */
  val topLeft: Double,
  /** The top-right corner radius in physical pixels. */
  val topRight: Double,
  /** The bottom-right corner radius in physical pixels. */
  val bottomRight: Double,
  /** The bottom-left corner radius in physical pixels. */
  val bottomLeft: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidDeviceDisplayCornerRadii {
      val topLeft = pigeonVar_list[0] as Double
      val topRight = pigeonVar_list[1] as Double
      val bottomRight = pigeonVar_list[2] as Double
      val bottomLeft = pigeonVar_list[3] as Double
      return AndroidDeviceDisplayCornerRadii(topLeft, topRight, bottomRight, bottomLeft)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      topLeft,
      topRight,
      bottomRight,
      bottomLeft,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidDeviceDisplayCornerRadii
    return AndroidDeviceDisplayPigeonUtils.deepEquals(this.topLeft, other.topLeft) && AndroidDeviceDisplayPigeonUtils.deepEquals(this.topRight, other.topRight) && AndroidDeviceDisplayPigeonUtils.deepEquals(this.bottomRight, other.bottomRight) && AndroidDeviceDisplayPigeonUtils.deepEquals(this.bottomLeft, other.bottomLeft)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidDeviceDisplayPigeonUtils.deepHash(this.topLeft)
    result = 31 * result + AndroidDeviceDisplayPigeonUtils.deepHash(this.topRight)
    result = 31 * result + AndroidDeviceDisplayPigeonUtils.deepHash(this.bottomRight)
    result = 31 * result + AndroidDeviceDisplayPigeonUtils.deepHash(this.bottomLeft)
    return result
  }
  override fun toString(): String {
    return "AndroidDeviceDisplayCornerRadii(topLeft=$topLeft, topRight=$topRight, bottomRight=$bottomRight, bottomLeft=$bottomLeft)"
  }
}
private open class AndroidDeviceDisplayPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidDeviceDisplayGeometry.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidDeviceDisplayCornerRadii.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AndroidDeviceDisplayGeometry -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AndroidDeviceDisplayCornerRadii -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Defines the Android host operations used by the display implementation.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface AndroidDeviceDisplayApi {
  /** Returns the current display corner radii in physical pixels. */
  fun getCornerRadii(geometry: AndroidDeviceDisplayGeometry): AndroidDeviceDisplayCornerRadii?

  companion object {
    /** The codec used by AndroidDeviceDisplayApi. */
    val codec: MessageCodec<Any?> by lazy {
      AndroidDeviceDisplayPigeonCodec()
    }
    /** Sets up an instance of `AndroidDeviceDisplayApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AndroidDeviceDisplayApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oh_my_flutter.AndroidDeviceDisplayApi.getCornerRadii$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val geometryArg = args[0] as AndroidDeviceDisplayGeometry
            val wrapped: List<Any?> = try {
              listOf(api.getCornerRadii(geometryArg))
            } catch (exception: Throwable) {
              AndroidDeviceDisplayPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
