// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.ventairy.oh_my_flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AndroidDeviceLocationPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Describes a failure returned by the Android location implementation. */
enum class AndroidDeviceLocationFailure(val raw: Int) {
  /** Android's system location service is disabled. */
  SERVICES_DISABLED(0),
  /** Foreground location permission is not granted. */
  PERMISSION_DENIED(1),
  /** Foreground location permission must be changed in system settings. */
  PERMISSION_PERMANENTLY_DENIED(2),
  /** Required Android host configuration is missing. */
  CONFIGURATION_MISSING(3),
  /** Android could not complete a native operation. */
  OPERATION_UNAVAILABLE(4),
  /** Android could not provide usable coordinates. */
  COORDINATES_UNAVAILABLE(5);

  companion object {
    fun ofRaw(raw: Int): AndroidDeviceLocationFailure? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Describes Android's foreground-location permission state. */
enum class AndroidDeviceLocationPermissionStatus(val raw: Int) {
  /** Foreground location permission can be requested. */
  DENIED(0),
  /** Foreground location permission must be changed in system settings. */
  DENIED_FOREVER(1),
  /** Location access is available while the application is in use. */
  WHILE_IN_USE(2);

  companion object {
    fun ofRaw(raw: Int): AndroidDeviceLocationPermissionStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Carries Android coordinates across the package's platform channel.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AndroidDeviceCoordinates (
  /** The latitude in degrees. */
  val latitude: Double,
  /** The longitude in degrees. */
  val longitude: Double,
  /** The estimated horizontal uncertainty in meters. */
  val accuracy: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidDeviceCoordinates {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      val accuracy = pigeonVar_list[2] as Double
      return AndroidDeviceCoordinates(latitude, longitude, accuracy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
      accuracy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidDeviceCoordinates
    return AndroidDeviceLocationPigeonUtils.deepEquals(this.latitude, other.latitude) && AndroidDeviceLocationPigeonUtils.deepEquals(this.longitude, other.longitude) && AndroidDeviceLocationPigeonUtils.deepEquals(this.accuracy, other.accuracy)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidDeviceLocationPigeonUtils.deepHash(this.latitude)
    result = 31 * result + AndroidDeviceLocationPigeonUtils.deepHash(this.longitude)
    result = 31 * result + AndroidDeviceLocationPigeonUtils.deepHash(this.accuracy)
    return result
  }
  override fun toString(): String {
    return "AndroidDeviceCoordinates(latitude=$latitude, longitude=$longitude, accuracy=$accuracy)"
  }
}
private open class AndroidDeviceLocationPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AndroidDeviceLocationFailure.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AndroidDeviceLocationPermissionStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidDeviceCoordinates.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AndroidDeviceLocationFailure -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is AndroidDeviceLocationPermissionStatus -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is AndroidDeviceCoordinates -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Defines the Android host operations used by the location implementation.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface AndroidDeviceLocationApi {
  /** Reports whether Android's system location service is enabled. */
  fun isServiceEnabled(): Boolean
  /** Reports the current Android foreground-location permission. */
  fun checkPermission(): AndroidDeviceLocationPermissionStatus
  /** Requests Android foreground-location permission. */
  fun requestPermission(callback: (Result<AndroidDeviceLocationPermissionStatus>) -> Unit)
  /** Retrieves the current Android device coordinates. */
  fun getCurrentCoordinates(callback: (Result<AndroidDeviceCoordinates>) -> Unit)
  /** Opens Android's application-details settings page. */
  fun openLocationSettings(): Boolean

  companion object {
    /** The codec used by AndroidDeviceLocationApi. */
    val codec: MessageCodec<Any?> by lazy {
      AndroidDeviceLocationPigeonCodec()
    }
    /** Sets up an instance of `AndroidDeviceLocationApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AndroidDeviceLocationApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oh_my_flutter.AndroidDeviceLocationApi.isServiceEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isServiceEnabled())
            } catch (exception: Throwable) {
              AndroidDeviceLocationPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oh_my_flutter.AndroidDeviceLocationApi.checkPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.checkPermission())
            } catch (exception: Throwable) {
              AndroidDeviceLocationPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oh_my_flutter.AndroidDeviceLocationApi.requestPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestPermission{ result: Result<AndroidDeviceLocationPermissionStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AndroidDeviceLocationPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AndroidDeviceLocationPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oh_my_flutter.AndroidDeviceLocationApi.getCurrentCoordinates$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getCurrentCoordinates{ result: Result<AndroidDeviceCoordinates> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AndroidDeviceLocationPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AndroidDeviceLocationPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oh_my_flutter.AndroidDeviceLocationApi.openLocationSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.openLocationSettings())
            } catch (exception: Throwable) {
              AndroidDeviceLocationPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
