// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.ventairy.oh_my_flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NativeSelectableTextPigeonUtils {

  fun createConnectionError(channelName: String): NativeSelectableTextPigeonError {
    return NativeSelectableTextPigeonError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is NativeSelectableTextPigeonError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class NativeSelectableTextPigeonError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Carries a Flutter logical-pixel rectangle to a native menu host.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeSelectableTextRectangleMessage (
  /** The horizontal coordinate of the leading edge. */
  val left: Double,
  /** The vertical coordinate of the upper edge. */
  val top: Double,
  /** The horizontal coordinate of the trailing edge. */
  val right: Double,
  /** The vertical coordinate of the lower edge. */
  val bottom: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeSelectableTextRectangleMessage {
      val left = pigeonVar_list[0] as Double
      val top = pigeonVar_list[1] as Double
      val right = pigeonVar_list[2] as Double
      val bottom = pigeonVar_list[3] as Double
      return NativeSelectableTextRectangleMessage(left, top, right, bottom)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      left,
      top,
      right,
      bottom,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeSelectableTextRectangleMessage
    return NativeSelectableTextPigeonUtils.deepEquals(this.left, other.left) && NativeSelectableTextPigeonUtils.deepEquals(this.top, other.top) && NativeSelectableTextPigeonUtils.deepEquals(this.right, other.right) && NativeSelectableTextPigeonUtils.deepEquals(this.bottom, other.bottom)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeSelectableTextPigeonUtils.deepHash(this.left)
    result = 31 * result + NativeSelectableTextPigeonUtils.deepHash(this.top)
    result = 31 * result + NativeSelectableTextPigeonUtils.deepHash(this.right)
    result = 31 * result + NativeSelectableTextPigeonUtils.deepHash(this.bottom)
    return result
  }
  override fun toString(): String {
    return "NativeSelectableTextRectangleMessage(left=$left, top=$top, right=$right, bottom=$bottom)"
  }
}

/**
 * Carries a Flutter logical-pixel point to a native menu host.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeSelectableTextPointMessage (
  /** The horizontal coordinate. */
  val dx: Double,
  /** The vertical coordinate. */
  val dy: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeSelectableTextPointMessage {
      val dx = pigeonVar_list[0] as Double
      val dy = pigeonVar_list[1] as Double
      return NativeSelectableTextPointMessage(dx, dy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      dx,
      dy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeSelectableTextPointMessage
    return NativeSelectableTextPigeonUtils.deepEquals(this.dx, other.dx) && NativeSelectableTextPigeonUtils.deepEquals(this.dy, other.dy)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeSelectableTextPigeonUtils.deepHash(this.dx)
    result = 31 * result + NativeSelectableTextPigeonUtils.deepHash(this.dy)
    return result
  }
  override fun toString(): String {
    return "NativeSelectableTextPointMessage(dx=$dx, dy=$dy)"
  }
}

/**
 * Describes one labeled native selection-menu command.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeSelectableTextMenuItemMessage (
  /** The identifier returned when the person chooses this item. */
  val identifier: Long,
  /** The localized label displayed by the platform menu. */
  val label: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeSelectableTextMenuItemMessage {
      val identifier = pigeonVar_list[0] as Long
      val label = pigeonVar_list[1] as String
      return NativeSelectableTextMenuItemMessage(identifier, label)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      identifier,
      label,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeSelectableTextMenuItemMessage
    return NativeSelectableTextPigeonUtils.deepEquals(this.identifier, other.identifier) && NativeSelectableTextPigeonUtils.deepEquals(this.label, other.label)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeSelectableTextPigeonUtils.deepHash(this.identifier)
    result = 31 * result + NativeSelectableTextPigeonUtils.deepHash(this.label)
    return result
  }
  override fun toString(): String {
    return "NativeSelectableTextMenuItemMessage(identifier=$identifier, label=$label)"
  }
}

/**
 * Describes one native selection-menu presentation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeSelectableTextMenuRequestMessage (
  /** Identifies this presentation and rejects callbacks from older menus. */
  val sessionIdentifier: Long,
  /** The selected glyph bounds in Flutter global logical pixels. */
  val selectionRectangle: NativeSelectableTextRectangleMessage,
  /** The preferred pointer or keyboard anchor in global logical pixels. */
  val primaryAnchor: NativeSelectableTextPointMessage,
  /** The ordered commands shown by the menu. */
  val items: List<NativeSelectableTextMenuItemMessage>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeSelectableTextMenuRequestMessage {
      val sessionIdentifier = pigeonVar_list[0] as Long
      val selectionRectangle = pigeonVar_list[1] as NativeSelectableTextRectangleMessage
      val primaryAnchor = pigeonVar_list[2] as NativeSelectableTextPointMessage
      val items = pigeonVar_list[3] as List<NativeSelectableTextMenuItemMessage>
      return NativeSelectableTextMenuRequestMessage(sessionIdentifier, selectionRectangle, primaryAnchor, items)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionIdentifier,
      selectionRectangle,
      primaryAnchor,
      items,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeSelectableTextMenuRequestMessage
    return NativeSelectableTextPigeonUtils.deepEquals(this.sessionIdentifier, other.sessionIdentifier) && NativeSelectableTextPigeonUtils.deepEquals(this.selectionRectangle, other.selectionRectangle) && NativeSelectableTextPigeonUtils.deepEquals(this.primaryAnchor, other.primaryAnchor) && NativeSelectableTextPigeonUtils.deepEquals(this.items, other.items)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeSelectableTextPigeonUtils.deepHash(this.sessionIdentifier)
    result = 31 * result + NativeSelectableTextPigeonUtils.deepHash(this.selectionRectangle)
    result = 31 * result + NativeSelectableTextPigeonUtils.deepHash(this.primaryAnchor)
    result = 31 * result + NativeSelectableTextPigeonUtils.deepHash(this.items)
    return result
  }
  override fun toString(): String {
    return "NativeSelectableTextMenuRequestMessage(sessionIdentifier=$sessionIdentifier, selectionRectangle=$selectionRectangle, primaryAnchor=$primaryAnchor, items=$items)"
  }
}
private open class NativeSelectableTextPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeSelectableTextRectangleMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeSelectableTextPointMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeSelectableTextMenuItemMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeSelectableTextMenuRequestMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeSelectableTextRectangleMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeSelectableTextPointMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativeSelectableTextMenuItemMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeSelectableTextMenuRequestMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Presents selection commands through the current native host.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface NativeSelectableTextMenuHostApi {
  /** Shows a native menu and reports whether presentation was accepted. */
  fun show(request: NativeSelectableTextMenuRequestMessage): Boolean
  /** Updates an already visible native menu. */
  fun update(request: NativeSelectableTextMenuRequestMessage): Boolean
  /**
   * Updates only the current selection rectangle and primary anchor.
   *
   * [geometry] contains left, top, right, bottom, anchor dx, and anchor dy in
   * Flutter global logical pixels, in that order.
   */
  fun updateGeometry(sessionIdentifier: Long, geometry: DoubleArray): Boolean
  /** Hides the menu for [sessionIdentifier] when it is still current. */
  fun hide(sessionIdentifier: Long)

  companion object {
    /** The codec used by NativeSelectableTextMenuHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeSelectableTextPigeonCodec()
    }
    /** Sets up an instance of `NativeSelectableTextMenuHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeSelectableTextMenuHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.show$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as NativeSelectableTextMenuRequestMessage
            val wrapped: List<Any?> = try {
              listOf(api.show(requestArg))
            } catch (exception: Throwable) {
              NativeSelectableTextPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.update$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as NativeSelectableTextMenuRequestMessage
            val wrapped: List<Any?> = try {
              listOf(api.update(requestArg))
            } catch (exception: Throwable) {
              NativeSelectableTextPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.updateGeometry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdentifierArg = args[0] as Long
            val geometryArg = args[1] as DoubleArray
            val wrapped: List<Any?> = try {
              listOf(api.updateGeometry(sessionIdentifierArg, geometryArg))
            } catch (exception: Throwable) {
              NativeSelectableTextPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.hide$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdentifierArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.hide(sessionIdentifierArg)
              listOf(null)
            } catch (exception: Throwable) {
              NativeSelectableTextPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Delivers native selection-menu events to Flutter.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class NativeSelectableTextMenuFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by NativeSelectableTextMenuFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeSelectableTextPigeonCodec()
    }
  }
  /** Invokes a command previously sent for [sessionIdentifier]. */
  fun onAction(sessionIdentifierArg: Long, actionIdentifierArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuFlutterApi.onAction$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sessionIdentifierArg, actionIdentifierArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(NativeSelectableTextPigeonError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NativeSelectableTextPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Reports that a menu closed and whether a command caused the dismissal. */
  fun onDismissed(sessionIdentifierArg: Long, actionInvokedArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuFlutterApi.onDismissed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sessionIdentifierArg, actionInvokedArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(NativeSelectableTextPigeonError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NativeSelectableTextPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
