// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#include <cmath>

#include <string.h>
#include "native_selectable_text.g.h"
static guint G_GNUC_UNUSED flpigeon_hash_double(double v) {
  if (std::isnan(v)) {
    return static_cast<guint>(0x7FF80000);
  }
  if (v == 0.0) {
    v = 0.0;
  }
  union { double d; uint64_t u; } u;
  u.d = v;
  return static_cast<guint>(u.u ^ (u.u >> 32));
}
static gboolean G_GNUC_UNUSED flpigeon_equals_double(double a, double b) {
  return (a == b) || (std::isnan(a) && std::isnan(b));
}
static gboolean G_GNUC_UNUSED flpigeon_deep_equals(FlValue* a, FlValue* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (fl_value_get_type(a) != fl_value_get_type(b)) {
    return FALSE;
  }
  switch (fl_value_get_type(a)) {
    case FL_VALUE_TYPE_NULL:
      return TRUE;
    case FL_VALUE_TYPE_BOOL:
      return fl_value_get_bool(a) == fl_value_get_bool(b);
    case FL_VALUE_TYPE_INT:
      return fl_value_get_int(a) == fl_value_get_int(b);
    case FL_VALUE_TYPE_FLOAT: {
      return flpigeon_equals_double(fl_value_get_float(a), fl_value_get_float(b));
    }
    case FL_VALUE_TYPE_STRING:
      return g_strcmp0(fl_value_get_string(a), fl_value_get_string(b)) == 0;
    case FL_VALUE_TYPE_UINT8_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_uint8_list(a), fl_value_get_uint8_list(b), fl_value_get_length(a)) == 0;
    case FL_VALUE_TYPE_INT32_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_int32_list(a), fl_value_get_int32_list(b), fl_value_get_length(a) * sizeof(int32_t)) == 0;
    case FL_VALUE_TYPE_INT64_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_int64_list(a), fl_value_get_int64_list(b), fl_value_get_length(a) * sizeof(int64_t)) == 0;
    case FL_VALUE_TYPE_FLOAT_LIST: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      const double* a_data = fl_value_get_float_list(a);
      const double* b_data = fl_value_get_float_list(b);
      for (size_t i = 0; i < len; i++) {
      if (!flpigeon_equals_double(a_data[i], b_data[i])) {
        return FALSE;
      }
    }
      return TRUE;
    }
    case FL_VALUE_TYPE_LIST: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      for (size_t i = 0; i < len; i++) {
      if (!flpigeon_deep_equals(fl_value_get_list_value(a, i), fl_value_get_list_value(b, i))) {
        return FALSE;
      }
    }
      return TRUE;
    }
    case FL_VALUE_TYPE_MAP: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      for (size_t i = 0; i < len; i++) {
      FlValue* key = fl_value_get_map_key(a, i);
      FlValue* val = fl_value_get_map_value(a, i);
      gboolean found = FALSE;
      for (size_t j = 0; j < len; j++) {
        FlValue* b_key = fl_value_get_map_key(b, j);
        if (flpigeon_deep_equals(key, b_key)) {
          FlValue* b_val = fl_value_get_map_value(b, j);
          if (flpigeon_deep_equals(val, b_val)) {
            found = TRUE;
            break;
          } else {
            return FALSE;
          }
        }
      }
      if (!found) {
        return FALSE;
      }
    }
      return TRUE;
    }
    default:
      return FALSE;
  }
  return FALSE;
}
static guint G_GNUC_UNUSED flpigeon_deep_hash(FlValue* value) {
  if (value == nullptr) {
    return 0;
  }
  switch (fl_value_get_type(value)) {
    case FL_VALUE_TYPE_NULL:
      return 0;
    case FL_VALUE_TYPE_BOOL:
      return fl_value_get_bool(value) ? 1231 : 1237;
    case FL_VALUE_TYPE_INT: {
      int64_t v = fl_value_get_int(value);
      return static_cast<guint>(v ^ (v >> 32));
    }
    case FL_VALUE_TYPE_FLOAT:
      return flpigeon_hash_double(fl_value_get_float(value));
    case FL_VALUE_TYPE_STRING:
      return g_str_hash(fl_value_get_string(value));
    case FL_VALUE_TYPE_UINT8_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const uint8_t* data = fl_value_get_uint8_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + data[i];
      }
      return result;
    }
    case FL_VALUE_TYPE_INT32_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const int32_t* data = fl_value_get_int32_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + static_cast<guint>(data[i]);
      }
      return result;
    }
    case FL_VALUE_TYPE_INT64_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const int64_t* data = fl_value_get_int64_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + static_cast<guint>(data[i] ^ (data[i] >> 32));
      }
      return result;
    }
    case FL_VALUE_TYPE_FLOAT_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const double* data = fl_value_get_float_list(value);
      for (size_t i = 0; i < len; i++) {
      result = result * 31 + flpigeon_hash_double(data[i]);
    }
      return result;
    }
    case FL_VALUE_TYPE_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
      result = result * 31 + flpigeon_deep_hash(fl_value_get_list_value(value, i));
    }
      return result;
    }
    case FL_VALUE_TYPE_MAP: {
      guint result = 0;
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
      result += ((flpigeon_deep_hash(fl_value_get_map_key(value, i)) * 31) ^ flpigeon_deep_hash(fl_value_get_map_value(value, i)));
    }
      return result;
    }
    default:
      return static_cast<guint>(fl_value_get_type(value));
  }
  return 0;
}
static gchar* G_GNUC_UNUSED flpigeon_to_string(FlValue* value) {
  if (value == nullptr) {
    return g_strdup("null");
  }
  switch (fl_value_get_type(value)) {
    case FL_VALUE_TYPE_NULL:
      return g_strdup("null");
    case FL_VALUE_TYPE_BOOL:
      return g_strdup(fl_value_get_bool(value) ? "true" : "false");
    case FL_VALUE_TYPE_INT:
      return g_strdup_printf("%" G_GINT64_FORMAT, fl_value_get_int(value));
    case FL_VALUE_TYPE_FLOAT:
      return g_strdup_printf("%g", fl_value_get_float(value));
    case FL_VALUE_TYPE_STRING:
      return g_strdup_printf("\"%s\"", fl_value_get_string(value));
    case FL_VALUE_TYPE_UINT8_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const uint8_t* data = fl_value_get_uint8_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%d", data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_INT32_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const int32_t* data = fl_value_get_int32_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%d", data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_INT64_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const int64_t* data = fl_value_get_int64_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%" G_GINT64_FORMAT, data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_FLOAT_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const double* data = fl_value_get_float_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%g", data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        gchar* item_str = flpigeon_to_string(fl_value_get_list_value(value, i));
        g_string_append(str, item_str);
        g_free(item_str);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_MAP: {
      GString* str = g_string_new("{");
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        gchar* key_str = flpigeon_to_string(fl_value_get_map_key(value, i));
        gchar* val_str = flpigeon_to_string(fl_value_get_map_value(value, i));
        g_string_append_printf(str, "%s: %s", key_str, val_str);
        g_free(key_str);
        g_free(val_str);
      }
      g_string_append(str, "}");
      return g_string_free(str, FALSE);
    }
    default:
      return g_strdup("[custom]");
  }
  return g_strdup("null");
}


struct _OhMyFlutterNativeSelectableTextRectangleMessage {
  GObject parent_instance;

  double left;
  double top;
  double right;
  double bottom;
};

G_DEFINE_TYPE(OhMyFlutterNativeSelectableTextRectangleMessage, oh_my_flutter_native_selectable_text_rectangle_message, G_TYPE_OBJECT)

static void oh_my_flutter_native_selectable_text_rectangle_message_dispose(GObject* object) {
  G_OBJECT_CLASS(oh_my_flutter_native_selectable_text_rectangle_message_parent_class)->dispose(object);
}

static void oh_my_flutter_native_selectable_text_rectangle_message_init(OhMyFlutterNativeSelectableTextRectangleMessage* self) {
}

static void oh_my_flutter_native_selectable_text_rectangle_message_class_init(OhMyFlutterNativeSelectableTextRectangleMessageClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = oh_my_flutter_native_selectable_text_rectangle_message_dispose;
}

OhMyFlutterNativeSelectableTextRectangleMessage* oh_my_flutter_native_selectable_text_rectangle_message_new(double left, double top, double right, double bottom) {
  OhMyFlutterNativeSelectableTextRectangleMessage* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_RECTANGLE_MESSAGE(g_object_new(oh_my_flutter_native_selectable_text_rectangle_message_get_type(), nullptr));
  self->left = left;
  self->top = top;
  self->right = right;
  self->bottom = bottom;
  return self;
}

double oh_my_flutter_native_selectable_text_rectangle_message_get_left(OhMyFlutterNativeSelectableTextRectangleMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_RECTANGLE_MESSAGE(self), 0.0);
  return self->left;
}

double oh_my_flutter_native_selectable_text_rectangle_message_get_top(OhMyFlutterNativeSelectableTextRectangleMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_RECTANGLE_MESSAGE(self), 0.0);
  return self->top;
}

double oh_my_flutter_native_selectable_text_rectangle_message_get_right(OhMyFlutterNativeSelectableTextRectangleMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_RECTANGLE_MESSAGE(self), 0.0);
  return self->right;
}

double oh_my_flutter_native_selectable_text_rectangle_message_get_bottom(OhMyFlutterNativeSelectableTextRectangleMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_RECTANGLE_MESSAGE(self), 0.0);
  return self->bottom;
}

static FlValue* oh_my_flutter_native_selectable_text_rectangle_message_to_list(OhMyFlutterNativeSelectableTextRectangleMessage* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_float(self->left));
  fl_value_append_take(values, fl_value_new_float(self->top));
  fl_value_append_take(values, fl_value_new_float(self->right));
  fl_value_append_take(values, fl_value_new_float(self->bottom));
  return values;
}

static OhMyFlutterNativeSelectableTextRectangleMessage* oh_my_flutter_native_selectable_text_rectangle_message_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  double left = fl_value_get_float(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  double top = fl_value_get_float(value1);
  FlValue* value2 = fl_value_get_list_value(values, 2);
  double right = fl_value_get_float(value2);
  FlValue* value3 = fl_value_get_list_value(values, 3);
  double bottom = fl_value_get_float(value3);
  return oh_my_flutter_native_selectable_text_rectangle_message_new(left, top, right, bottom);
}

gboolean oh_my_flutter_native_selectable_text_rectangle_message_equals(OhMyFlutterNativeSelectableTextRectangleMessage* a, OhMyFlutterNativeSelectableTextRectangleMessage* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (!flpigeon_equals_double(a->left, b->left)) {
    return FALSE;
  }
  if (!flpigeon_equals_double(a->top, b->top)) {
    return FALSE;
  }
  if (!flpigeon_equals_double(a->right, b->right)) {
    return FALSE;
  }
  if (!flpigeon_equals_double(a->bottom, b->bottom)) {
    return FALSE;
  }
  return TRUE;
}

guint oh_my_flutter_native_selectable_text_rectangle_message_hash(OhMyFlutterNativeSelectableTextRectangleMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_RECTANGLE_MESSAGE(self), 0);
  guint result = 0;
  result = result * 31 + flpigeon_hash_double(self->left);
  result = result * 31 + flpigeon_hash_double(self->top);
  result = result * 31 + flpigeon_hash_double(self->right);
  result = result * 31 + flpigeon_hash_double(self->bottom);
  return result;
}

gchar* oh_my_flutter_native_selectable_text_rectangle_message_to_string(OhMyFlutterNativeSelectableTextRectangleMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_RECTANGLE_MESSAGE(self), NULL);
  GString* str = g_string_new("NativeSelectableTextRectangleMessage(");
  g_string_append(str, "left: ");
  g_string_append_printf(str, "%g", self->left);
  g_string_append(str, ", top: ");
  g_string_append_printf(str, "%g", self->top);
  g_string_append(str, ", right: ");
  g_string_append_printf(str, "%g", self->right);
  g_string_append(str, ", bottom: ");
  g_string_append_printf(str, "%g", self->bottom);
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _OhMyFlutterNativeSelectableTextPointMessage {
  GObject parent_instance;

  double dx;
  double dy;
};

G_DEFINE_TYPE(OhMyFlutterNativeSelectableTextPointMessage, oh_my_flutter_native_selectable_text_point_message, G_TYPE_OBJECT)

static void oh_my_flutter_native_selectable_text_point_message_dispose(GObject* object) {
  G_OBJECT_CLASS(oh_my_flutter_native_selectable_text_point_message_parent_class)->dispose(object);
}

static void oh_my_flutter_native_selectable_text_point_message_init(OhMyFlutterNativeSelectableTextPointMessage* self) {
}

static void oh_my_flutter_native_selectable_text_point_message_class_init(OhMyFlutterNativeSelectableTextPointMessageClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = oh_my_flutter_native_selectable_text_point_message_dispose;
}

OhMyFlutterNativeSelectableTextPointMessage* oh_my_flutter_native_selectable_text_point_message_new(double dx, double dy) {
  OhMyFlutterNativeSelectableTextPointMessage* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_POINT_MESSAGE(g_object_new(oh_my_flutter_native_selectable_text_point_message_get_type(), nullptr));
  self->dx = dx;
  self->dy = dy;
  return self;
}

double oh_my_flutter_native_selectable_text_point_message_get_dx(OhMyFlutterNativeSelectableTextPointMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_POINT_MESSAGE(self), 0.0);
  return self->dx;
}

double oh_my_flutter_native_selectable_text_point_message_get_dy(OhMyFlutterNativeSelectableTextPointMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_POINT_MESSAGE(self), 0.0);
  return self->dy;
}

static FlValue* oh_my_flutter_native_selectable_text_point_message_to_list(OhMyFlutterNativeSelectableTextPointMessage* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_float(self->dx));
  fl_value_append_take(values, fl_value_new_float(self->dy));
  return values;
}

static OhMyFlutterNativeSelectableTextPointMessage* oh_my_flutter_native_selectable_text_point_message_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  double dx = fl_value_get_float(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  double dy = fl_value_get_float(value1);
  return oh_my_flutter_native_selectable_text_point_message_new(dx, dy);
}

gboolean oh_my_flutter_native_selectable_text_point_message_equals(OhMyFlutterNativeSelectableTextPointMessage* a, OhMyFlutterNativeSelectableTextPointMessage* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (!flpigeon_equals_double(a->dx, b->dx)) {
    return FALSE;
  }
  if (!flpigeon_equals_double(a->dy, b->dy)) {
    return FALSE;
  }
  return TRUE;
}

guint oh_my_flutter_native_selectable_text_point_message_hash(OhMyFlutterNativeSelectableTextPointMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_POINT_MESSAGE(self), 0);
  guint result = 0;
  result = result * 31 + flpigeon_hash_double(self->dx);
  result = result * 31 + flpigeon_hash_double(self->dy);
  return result;
}

gchar* oh_my_flutter_native_selectable_text_point_message_to_string(OhMyFlutterNativeSelectableTextPointMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_POINT_MESSAGE(self), NULL);
  GString* str = g_string_new("NativeSelectableTextPointMessage(");
  g_string_append(str, "dx: ");
  g_string_append_printf(str, "%g", self->dx);
  g_string_append(str, ", dy: ");
  g_string_append_printf(str, "%g", self->dy);
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _OhMyFlutterNativeSelectableTextMenuItemMessage {
  GObject parent_instance;

  int64_t identifier;
  gchar* label;
};

G_DEFINE_TYPE(OhMyFlutterNativeSelectableTextMenuItemMessage, oh_my_flutter_native_selectable_text_menu_item_message, G_TYPE_OBJECT)

static void oh_my_flutter_native_selectable_text_menu_item_message_dispose(GObject* object) {
  OhMyFlutterNativeSelectableTextMenuItemMessage* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_ITEM_MESSAGE(object);
  g_clear_pointer(&self->label, g_free);
  G_OBJECT_CLASS(oh_my_flutter_native_selectable_text_menu_item_message_parent_class)->dispose(object);
}

static void oh_my_flutter_native_selectable_text_menu_item_message_init(OhMyFlutterNativeSelectableTextMenuItemMessage* self) {
}

static void oh_my_flutter_native_selectable_text_menu_item_message_class_init(OhMyFlutterNativeSelectableTextMenuItemMessageClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = oh_my_flutter_native_selectable_text_menu_item_message_dispose;
}

OhMyFlutterNativeSelectableTextMenuItemMessage* oh_my_flutter_native_selectable_text_menu_item_message_new(int64_t identifier, const gchar* label) {
  OhMyFlutterNativeSelectableTextMenuItemMessage* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_ITEM_MESSAGE(g_object_new(oh_my_flutter_native_selectable_text_menu_item_message_get_type(), nullptr));
  self->identifier = identifier;
  self->label = g_strdup(label);
  return self;
}

int64_t oh_my_flutter_native_selectable_text_menu_item_message_get_identifier(OhMyFlutterNativeSelectableTextMenuItemMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_ITEM_MESSAGE(self), 0);
  return self->identifier;
}

const gchar* oh_my_flutter_native_selectable_text_menu_item_message_get_label(OhMyFlutterNativeSelectableTextMenuItemMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_ITEM_MESSAGE(self), nullptr);
  return self->label;
}

static FlValue* oh_my_flutter_native_selectable_text_menu_item_message_to_list(OhMyFlutterNativeSelectableTextMenuItemMessage* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_int(self->identifier));
  fl_value_append_take(values, fl_value_new_string(self->label));
  return values;
}

static OhMyFlutterNativeSelectableTextMenuItemMessage* oh_my_flutter_native_selectable_text_menu_item_message_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  int64_t identifier = fl_value_get_int(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  const gchar* label = fl_value_get_string(value1);
  return oh_my_flutter_native_selectable_text_menu_item_message_new(identifier, label);
}

gboolean oh_my_flutter_native_selectable_text_menu_item_message_equals(OhMyFlutterNativeSelectableTextMenuItemMessage* a, OhMyFlutterNativeSelectableTextMenuItemMessage* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (a->identifier != b->identifier) {
    return FALSE;
  }
  if (g_strcmp0(a->label, b->label) != 0) {
    return FALSE;
  }
  return TRUE;
}

guint oh_my_flutter_native_selectable_text_menu_item_message_hash(OhMyFlutterNativeSelectableTextMenuItemMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_ITEM_MESSAGE(self), 0);
  guint result = 0;
  result = result * 31 + static_cast<guint>(self->identifier);
  result = result * 31 + (self->label != nullptr ? g_str_hash(self->label) : 0);
  return result;
}

gchar* oh_my_flutter_native_selectable_text_menu_item_message_to_string(OhMyFlutterNativeSelectableTextMenuItemMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_ITEM_MESSAGE(self), NULL);
  GString* str = g_string_new("NativeSelectableTextMenuItemMessage(");
  g_string_append(str, "identifier: ");
  g_string_append_printf(str, "%" G_GINT64_FORMAT, self->identifier);
  g_string_append(str, ", label: ");
  if (self->label != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->label);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _OhMyFlutterNativeSelectableTextMenuRequestMessage {
  GObject parent_instance;

  int64_t session_identifier;
  OhMyFlutterNativeSelectableTextRectangleMessage* selection_rectangle;
  OhMyFlutterNativeSelectableTextPointMessage* primary_anchor;
  FlValue* items;
};

G_DEFINE_TYPE(OhMyFlutterNativeSelectableTextMenuRequestMessage, oh_my_flutter_native_selectable_text_menu_request_message, G_TYPE_OBJECT)

static void oh_my_flutter_native_selectable_text_menu_request_message_dispose(GObject* object) {
  OhMyFlutterNativeSelectableTextMenuRequestMessage* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_REQUEST_MESSAGE(object);
  g_clear_object(&self->selection_rectangle);
  g_clear_object(&self->primary_anchor);
  g_clear_pointer(&self->items, fl_value_unref);
  G_OBJECT_CLASS(oh_my_flutter_native_selectable_text_menu_request_message_parent_class)->dispose(object);
}

static void oh_my_flutter_native_selectable_text_menu_request_message_init(OhMyFlutterNativeSelectableTextMenuRequestMessage* self) {
}

static void oh_my_flutter_native_selectable_text_menu_request_message_class_init(OhMyFlutterNativeSelectableTextMenuRequestMessageClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = oh_my_flutter_native_selectable_text_menu_request_message_dispose;
}

OhMyFlutterNativeSelectableTextMenuRequestMessage* oh_my_flutter_native_selectable_text_menu_request_message_new(int64_t session_identifier, OhMyFlutterNativeSelectableTextRectangleMessage* selection_rectangle, OhMyFlutterNativeSelectableTextPointMessage* primary_anchor, FlValue* items) {
  OhMyFlutterNativeSelectableTextMenuRequestMessage* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_REQUEST_MESSAGE(g_object_new(oh_my_flutter_native_selectable_text_menu_request_message_get_type(), nullptr));
  self->session_identifier = session_identifier;
  self->selection_rectangle = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_RECTANGLE_MESSAGE(g_object_ref(selection_rectangle));
  self->primary_anchor = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_POINT_MESSAGE(g_object_ref(primary_anchor));
  self->items = fl_value_ref(items);
  return self;
}

int64_t oh_my_flutter_native_selectable_text_menu_request_message_get_session_identifier(OhMyFlutterNativeSelectableTextMenuRequestMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_REQUEST_MESSAGE(self), 0);
  return self->session_identifier;
}

OhMyFlutterNativeSelectableTextRectangleMessage* oh_my_flutter_native_selectable_text_menu_request_message_get_selection_rectangle(OhMyFlutterNativeSelectableTextMenuRequestMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_REQUEST_MESSAGE(self), nullptr);
  return self->selection_rectangle;
}

OhMyFlutterNativeSelectableTextPointMessage* oh_my_flutter_native_selectable_text_menu_request_message_get_primary_anchor(OhMyFlutterNativeSelectableTextMenuRequestMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_REQUEST_MESSAGE(self), nullptr);
  return self->primary_anchor;
}

FlValue* oh_my_flutter_native_selectable_text_menu_request_message_get_items(OhMyFlutterNativeSelectableTextMenuRequestMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_REQUEST_MESSAGE(self), nullptr);
  return self->items;
}

static FlValue* oh_my_flutter_native_selectable_text_menu_request_message_to_list(OhMyFlutterNativeSelectableTextMenuRequestMessage* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_int(self->session_identifier));
  fl_value_append_take(values, fl_value_new_custom_object(oh_my_flutter_native_selectable_text_rectangle_message_type_id, G_OBJECT(self->selection_rectangle)));
  fl_value_append_take(values, fl_value_new_custom_object(oh_my_flutter_native_selectable_text_point_message_type_id, G_OBJECT(self->primary_anchor)));
  fl_value_append_take(values, fl_value_ref(self->items));
  return values;
}

static OhMyFlutterNativeSelectableTextMenuRequestMessage* oh_my_flutter_native_selectable_text_menu_request_message_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  int64_t session_identifier = fl_value_get_int(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  OhMyFlutterNativeSelectableTextRectangleMessage* selection_rectangle = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_RECTANGLE_MESSAGE(fl_value_get_custom_value_object(value1));
  FlValue* value2 = fl_value_get_list_value(values, 2);
  OhMyFlutterNativeSelectableTextPointMessage* primary_anchor = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_POINT_MESSAGE(fl_value_get_custom_value_object(value2));
  FlValue* value3 = fl_value_get_list_value(values, 3);
  FlValue* items = value3;
  return oh_my_flutter_native_selectable_text_menu_request_message_new(session_identifier, selection_rectangle, primary_anchor, items);
}

gboolean oh_my_flutter_native_selectable_text_menu_request_message_equals(OhMyFlutterNativeSelectableTextMenuRequestMessage* a, OhMyFlutterNativeSelectableTextMenuRequestMessage* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (a->session_identifier != b->session_identifier) {
    return FALSE;
  }
  if (!oh_my_flutter_native_selectable_text_rectangle_message_equals(a->selection_rectangle, b->selection_rectangle)) {
    return FALSE;
  }
  if (!oh_my_flutter_native_selectable_text_point_message_equals(a->primary_anchor, b->primary_anchor)) {
    return FALSE;
  }
  if (!flpigeon_deep_equals(a->items, b->items)) {
    return FALSE;
  }
  return TRUE;
}

guint oh_my_flutter_native_selectable_text_menu_request_message_hash(OhMyFlutterNativeSelectableTextMenuRequestMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_REQUEST_MESSAGE(self), 0);
  guint result = 0;
  result = result * 31 + static_cast<guint>(self->session_identifier);
  result = result * 31 + oh_my_flutter_native_selectable_text_rectangle_message_hash(self->selection_rectangle);
  result = result * 31 + oh_my_flutter_native_selectable_text_point_message_hash(self->primary_anchor);
  result = result * 31 + flpigeon_deep_hash(self->items);
  return result;
}

gchar* oh_my_flutter_native_selectable_text_menu_request_message_to_string(OhMyFlutterNativeSelectableTextMenuRequestMessage* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_REQUEST_MESSAGE(self), NULL);
  GString* str = g_string_new("NativeSelectableTextMenuRequestMessage(");
  g_string_append(str, "session_identifier: ");
  g_string_append_printf(str, "%" G_GINT64_FORMAT, self->session_identifier);
  g_string_append(str, ", selection_rectangle: ");
  if (self->selection_rectangle != nullptr) {
    gchar* field_str = oh_my_flutter_native_selectable_text_rectangle_message_to_string(self->selection_rectangle);
    g_string_append(str, field_str);
    g_free(field_str);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", primary_anchor: ");
  if (self->primary_anchor != nullptr) {
    gchar* field_str = oh_my_flutter_native_selectable_text_point_message_to_string(self->primary_anchor);
    g_string_append(str, field_str);
    g_free(field_str);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", items: ");
  if (self->items != nullptr) {
    gchar* val_str = flpigeon_to_string(self->items);
    g_string_append(str, val_str);
    g_free(val_str);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _OhMyFlutterMessageCodec {
  FlStandardMessageCodec parent_instance;

};

G_DEFINE_TYPE(OhMyFlutterMessageCodec, oh_my_flutter_message_codec, fl_standard_message_codec_get_type())

const int oh_my_flutter_native_selectable_text_rectangle_message_type_id = 129;
const int oh_my_flutter_native_selectable_text_point_message_type_id = 130;
const int oh_my_flutter_native_selectable_text_menu_item_message_type_id = 131;
const int oh_my_flutter_native_selectable_text_menu_request_message_type_id = 132;

static gboolean oh_my_flutter_message_codec_write_oh_my_flutter_native_selectable_text_rectangle_message(FlStandardMessageCodec* codec, GByteArray* buffer, OhMyFlutterNativeSelectableTextRectangleMessage* value, GError** error) {
  uint8_t type = oh_my_flutter_native_selectable_text_rectangle_message_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = oh_my_flutter_native_selectable_text_rectangle_message_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean oh_my_flutter_message_codec_write_oh_my_flutter_native_selectable_text_point_message(FlStandardMessageCodec* codec, GByteArray* buffer, OhMyFlutterNativeSelectableTextPointMessage* value, GError** error) {
  uint8_t type = oh_my_flutter_native_selectable_text_point_message_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = oh_my_flutter_native_selectable_text_point_message_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean oh_my_flutter_message_codec_write_oh_my_flutter_native_selectable_text_menu_item_message(FlStandardMessageCodec* codec, GByteArray* buffer, OhMyFlutterNativeSelectableTextMenuItemMessage* value, GError** error) {
  uint8_t type = oh_my_flutter_native_selectable_text_menu_item_message_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = oh_my_flutter_native_selectable_text_menu_item_message_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean oh_my_flutter_message_codec_write_oh_my_flutter_native_selectable_text_menu_request_message(FlStandardMessageCodec* codec, GByteArray* buffer, OhMyFlutterNativeSelectableTextMenuRequestMessage* value, GError** error) {
  uint8_t type = oh_my_flutter_native_selectable_text_menu_request_message_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = oh_my_flutter_native_selectable_text_menu_request_message_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean oh_my_flutter_message_codec_write_value(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  if (fl_value_get_type(value) == FL_VALUE_TYPE_CUSTOM) {
    switch (fl_value_get_custom_type(value)) {
      case oh_my_flutter_native_selectable_text_rectangle_message_type_id:
        return oh_my_flutter_message_codec_write_oh_my_flutter_native_selectable_text_rectangle_message(codec, buffer, OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_RECTANGLE_MESSAGE(fl_value_get_custom_value_object(value)), error);
      case oh_my_flutter_native_selectable_text_point_message_type_id:
        return oh_my_flutter_message_codec_write_oh_my_flutter_native_selectable_text_point_message(codec, buffer, OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_POINT_MESSAGE(fl_value_get_custom_value_object(value)), error);
      case oh_my_flutter_native_selectable_text_menu_item_message_type_id:
        return oh_my_flutter_message_codec_write_oh_my_flutter_native_selectable_text_menu_item_message(codec, buffer, OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_ITEM_MESSAGE(fl_value_get_custom_value_object(value)), error);
      case oh_my_flutter_native_selectable_text_menu_request_message_type_id:
        return oh_my_flutter_message_codec_write_oh_my_flutter_native_selectable_text_menu_request_message(codec, buffer, OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_REQUEST_MESSAGE(fl_value_get_custom_value_object(value)), error);
    }
  }

  return FL_STANDARD_MESSAGE_CODEC_CLASS(oh_my_flutter_message_codec_parent_class)->write_value(codec, buffer, value, error);
}

static FlValue* oh_my_flutter_message_codec_read_oh_my_flutter_native_selectable_text_rectangle_message(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(OhMyFlutterNativeSelectableTextRectangleMessage) value = oh_my_flutter_native_selectable_text_rectangle_message_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(oh_my_flutter_native_selectable_text_rectangle_message_type_id, G_OBJECT(value));
}

static FlValue* oh_my_flutter_message_codec_read_oh_my_flutter_native_selectable_text_point_message(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(OhMyFlutterNativeSelectableTextPointMessage) value = oh_my_flutter_native_selectable_text_point_message_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(oh_my_flutter_native_selectable_text_point_message_type_id, G_OBJECT(value));
}

static FlValue* oh_my_flutter_message_codec_read_oh_my_flutter_native_selectable_text_menu_item_message(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(OhMyFlutterNativeSelectableTextMenuItemMessage) value = oh_my_flutter_native_selectable_text_menu_item_message_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(oh_my_flutter_native_selectable_text_menu_item_message_type_id, G_OBJECT(value));
}

static FlValue* oh_my_flutter_message_codec_read_oh_my_flutter_native_selectable_text_menu_request_message(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(OhMyFlutterNativeSelectableTextMenuRequestMessage) value = oh_my_flutter_native_selectable_text_menu_request_message_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(oh_my_flutter_native_selectable_text_menu_request_message_type_id, G_OBJECT(value));
}

static FlValue* oh_my_flutter_message_codec_read_value_of_type(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, int type, GError** error) {
  switch (type) {
    case oh_my_flutter_native_selectable_text_rectangle_message_type_id:
      return oh_my_flutter_message_codec_read_oh_my_flutter_native_selectable_text_rectangle_message(codec, buffer, offset, error);
    case oh_my_flutter_native_selectable_text_point_message_type_id:
      return oh_my_flutter_message_codec_read_oh_my_flutter_native_selectable_text_point_message(codec, buffer, offset, error);
    case oh_my_flutter_native_selectable_text_menu_item_message_type_id:
      return oh_my_flutter_message_codec_read_oh_my_flutter_native_selectable_text_menu_item_message(codec, buffer, offset, error);
    case oh_my_flutter_native_selectable_text_menu_request_message_type_id:
      return oh_my_flutter_message_codec_read_oh_my_flutter_native_selectable_text_menu_request_message(codec, buffer, offset, error);
    default:
      return FL_STANDARD_MESSAGE_CODEC_CLASS(oh_my_flutter_message_codec_parent_class)->read_value_of_type(codec, buffer, offset, type, error);
  }
}

static void oh_my_flutter_message_codec_init(OhMyFlutterMessageCodec* self) {
}

static void oh_my_flutter_message_codec_class_init(OhMyFlutterMessageCodecClass* klass) {
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->write_value = oh_my_flutter_message_codec_write_value;
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->read_value_of_type = oh_my_flutter_message_codec_read_value_of_type;
}

static OhMyFlutterMessageCodec* oh_my_flutter_message_codec_new() {
  OhMyFlutterMessageCodec* self = OH_MY_FLUTTER_MESSAGE_CODEC(g_object_new(oh_my_flutter_message_codec_get_type(), nullptr));
  return self;
}

struct _OhMyFlutterNativeSelectableTextMenuHostApiShowResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(OhMyFlutterNativeSelectableTextMenuHostApiShowResponse, oh_my_flutter_native_selectable_text_menu_host_api_show_response, G_TYPE_OBJECT)

static void oh_my_flutter_native_selectable_text_menu_host_api_show_response_dispose(GObject* object) {
  OhMyFlutterNativeSelectableTextMenuHostApiShowResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API_SHOW_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(oh_my_flutter_native_selectable_text_menu_host_api_show_response_parent_class)->dispose(object);
}

static void oh_my_flutter_native_selectable_text_menu_host_api_show_response_init(OhMyFlutterNativeSelectableTextMenuHostApiShowResponse* self) {
}

static void oh_my_flutter_native_selectable_text_menu_host_api_show_response_class_init(OhMyFlutterNativeSelectableTextMenuHostApiShowResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = oh_my_flutter_native_selectable_text_menu_host_api_show_response_dispose;
}

OhMyFlutterNativeSelectableTextMenuHostApiShowResponse* oh_my_flutter_native_selectable_text_menu_host_api_show_response_new(gboolean return_value) {
  OhMyFlutterNativeSelectableTextMenuHostApiShowResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API_SHOW_RESPONSE(g_object_new(oh_my_flutter_native_selectable_text_menu_host_api_show_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_bool(return_value));
  return self;
}

OhMyFlutterNativeSelectableTextMenuHostApiShowResponse* oh_my_flutter_native_selectable_text_menu_host_api_show_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  OhMyFlutterNativeSelectableTextMenuHostApiShowResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API_SHOW_RESPONSE(g_object_new(oh_my_flutter_native_selectable_text_menu_host_api_show_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponse, oh_my_flutter_native_selectable_text_menu_host_api_update_response, G_TYPE_OBJECT)

static void oh_my_flutter_native_selectable_text_menu_host_api_update_response_dispose(GObject* object) {
  OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API_UPDATE_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(oh_my_flutter_native_selectable_text_menu_host_api_update_response_parent_class)->dispose(object);
}

static void oh_my_flutter_native_selectable_text_menu_host_api_update_response_init(OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponse* self) {
}

static void oh_my_flutter_native_selectable_text_menu_host_api_update_response_class_init(OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = oh_my_flutter_native_selectable_text_menu_host_api_update_response_dispose;
}

OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponse* oh_my_flutter_native_selectable_text_menu_host_api_update_response_new(gboolean return_value) {
  OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API_UPDATE_RESPONSE(g_object_new(oh_my_flutter_native_selectable_text_menu_host_api_update_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_bool(return_value));
  return self;
}

OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponse* oh_my_flutter_native_selectable_text_menu_host_api_update_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API_UPDATE_RESPONSE(g_object_new(oh_my_flutter_native_selectable_text_menu_host_api_update_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponse, oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_response, G_TYPE_OBJECT)

static void oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_response_dispose(GObject* object) {
  OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API_UPDATE_GEOMETRY_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_response_parent_class)->dispose(object);
}

static void oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_response_init(OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponse* self) {
}

static void oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_response_class_init(OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_response_dispose;
}

OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponse* oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_response_new(gboolean return_value) {
  OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API_UPDATE_GEOMETRY_RESPONSE(g_object_new(oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_bool(return_value));
  return self;
}

OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponse* oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API_UPDATE_GEOMETRY_RESPONSE(g_object_new(oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _OhMyFlutterNativeSelectableTextMenuHostApiHideResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(OhMyFlutterNativeSelectableTextMenuHostApiHideResponse, oh_my_flutter_native_selectable_text_menu_host_api_hide_response, G_TYPE_OBJECT)

static void oh_my_flutter_native_selectable_text_menu_host_api_hide_response_dispose(GObject* object) {
  OhMyFlutterNativeSelectableTextMenuHostApiHideResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API_HIDE_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(oh_my_flutter_native_selectable_text_menu_host_api_hide_response_parent_class)->dispose(object);
}

static void oh_my_flutter_native_selectable_text_menu_host_api_hide_response_init(OhMyFlutterNativeSelectableTextMenuHostApiHideResponse* self) {
}

static void oh_my_flutter_native_selectable_text_menu_host_api_hide_response_class_init(OhMyFlutterNativeSelectableTextMenuHostApiHideResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = oh_my_flutter_native_selectable_text_menu_host_api_hide_response_dispose;
}

OhMyFlutterNativeSelectableTextMenuHostApiHideResponse* oh_my_flutter_native_selectable_text_menu_host_api_hide_response_new() {
  OhMyFlutterNativeSelectableTextMenuHostApiHideResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API_HIDE_RESPONSE(g_object_new(oh_my_flutter_native_selectable_text_menu_host_api_hide_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

OhMyFlutterNativeSelectableTextMenuHostApiHideResponse* oh_my_flutter_native_selectable_text_menu_host_api_hide_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  OhMyFlutterNativeSelectableTextMenuHostApiHideResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API_HIDE_RESPONSE(g_object_new(oh_my_flutter_native_selectable_text_menu_host_api_hide_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _OhMyFlutterNativeSelectableTextMenuHostApi {
  GObject parent_instance;

  const OhMyFlutterNativeSelectableTextMenuHostApiVTable* vtable;
  gpointer user_data;
  GDestroyNotify user_data_free_func;
};

G_DEFINE_TYPE(OhMyFlutterNativeSelectableTextMenuHostApi, oh_my_flutter_native_selectable_text_menu_host_api, G_TYPE_OBJECT)

static void oh_my_flutter_native_selectable_text_menu_host_api_dispose(GObject* object) {
  OhMyFlutterNativeSelectableTextMenuHostApi* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API(object);
  if (self->user_data != nullptr) {
    self->user_data_free_func(self->user_data);
  }
  self->user_data = nullptr;
  G_OBJECT_CLASS(oh_my_flutter_native_selectable_text_menu_host_api_parent_class)->dispose(object);
}

static void oh_my_flutter_native_selectable_text_menu_host_api_init(OhMyFlutterNativeSelectableTextMenuHostApi* self) {
}

static void oh_my_flutter_native_selectable_text_menu_host_api_class_init(OhMyFlutterNativeSelectableTextMenuHostApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = oh_my_flutter_native_selectable_text_menu_host_api_dispose;
}

static OhMyFlutterNativeSelectableTextMenuHostApi* oh_my_flutter_native_selectable_text_menu_host_api_new(const OhMyFlutterNativeSelectableTextMenuHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  OhMyFlutterNativeSelectableTextMenuHostApi* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API(g_object_new(oh_my_flutter_native_selectable_text_menu_host_api_get_type(), nullptr));
  self->vtable = vtable;
  self->user_data = user_data;
  self->user_data_free_func = user_data_free_func;
  return self;
}

static void oh_my_flutter_native_selectable_text_menu_host_api_show_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  OhMyFlutterNativeSelectableTextMenuHostApi* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->show == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  OhMyFlutterNativeSelectableTextMenuRequestMessage* request = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_REQUEST_MESSAGE(fl_value_get_custom_value_object(value0));
  g_autoptr(OhMyFlutterNativeSelectableTextMenuHostApiShowResponse) response = self->vtable->show(request, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "NativeSelectableTextMenuHostApi", "show");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "NativeSelectableTextMenuHostApi", "show", error->message);
  }
}

static void oh_my_flutter_native_selectable_text_menu_host_api_update_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  OhMyFlutterNativeSelectableTextMenuHostApi* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->update == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  OhMyFlutterNativeSelectableTextMenuRequestMessage* request = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_REQUEST_MESSAGE(fl_value_get_custom_value_object(value0));
  g_autoptr(OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponse) response = self->vtable->update(request, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "NativeSelectableTextMenuHostApi", "update");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "NativeSelectableTextMenuHostApi", "update", error->message);
  }
}

static void oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  OhMyFlutterNativeSelectableTextMenuHostApi* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->update_geometry == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  int64_t session_identifier = fl_value_get_int(value0);
  FlValue* value1 = fl_value_get_list_value(message_, 1);
  const double* geometry = fl_value_get_float_list(value1);
  size_t geometry_length = fl_value_get_length(value1);
  g_autoptr(OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponse) response = self->vtable->update_geometry(session_identifier, geometry, geometry_length, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "NativeSelectableTextMenuHostApi", "updateGeometry");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "NativeSelectableTextMenuHostApi", "updateGeometry", error->message);
  }
}

static void oh_my_flutter_native_selectable_text_menu_host_api_hide_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  OhMyFlutterNativeSelectableTextMenuHostApi* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->hide == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  int64_t session_identifier = fl_value_get_int(value0);
  g_autoptr(OhMyFlutterNativeSelectableTextMenuHostApiHideResponse) response = self->vtable->hide(session_identifier, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "NativeSelectableTextMenuHostApi", "hide");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "NativeSelectableTextMenuHostApi", "hide", error->message);
  }
}

void oh_my_flutter_native_selectable_text_menu_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const OhMyFlutterNativeSelectableTextMenuHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  g_autoptr(OhMyFlutterNativeSelectableTextMenuHostApi) api_data = oh_my_flutter_native_selectable_text_menu_host_api_new(vtable, user_data, user_data_free_func);

  g_autoptr(OhMyFlutterMessageCodec) codec = oh_my_flutter_message_codec_new();
  g_autofree gchar* show_channel_name = g_strdup_printf("dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.show%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) show_channel = fl_basic_message_channel_new(messenger, show_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(show_channel, oh_my_flutter_native_selectable_text_menu_host_api_show_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* update_channel_name = g_strdup_printf("dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.update%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) update_channel = fl_basic_message_channel_new(messenger, update_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(update_channel, oh_my_flutter_native_selectable_text_menu_host_api_update_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* update_geometry_channel_name = g_strdup_printf("dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.updateGeometry%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) update_geometry_channel = fl_basic_message_channel_new(messenger, update_geometry_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(update_geometry_channel, oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* hide_channel_name = g_strdup_printf("dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.hide%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) hide_channel = fl_basic_message_channel_new(messenger, hide_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(hide_channel, oh_my_flutter_native_selectable_text_menu_host_api_hide_cb, g_object_ref(api_data), g_object_unref);
}

void oh_my_flutter_native_selectable_text_menu_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");

  g_autoptr(OhMyFlutterMessageCodec) codec = oh_my_flutter_message_codec_new();
  g_autofree gchar* show_channel_name = g_strdup_printf("dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.show%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) show_channel = fl_basic_message_channel_new(messenger, show_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(show_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* update_channel_name = g_strdup_printf("dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.update%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) update_channel = fl_basic_message_channel_new(messenger, update_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(update_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* update_geometry_channel_name = g_strdup_printf("dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.updateGeometry%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) update_geometry_channel = fl_basic_message_channel_new(messenger, update_geometry_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(update_geometry_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* hide_channel_name = g_strdup_printf("dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuHostApi.hide%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) hide_channel = fl_basic_message_channel_new(messenger, hide_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(hide_channel, nullptr, nullptr, nullptr);
}

struct _OhMyFlutterNativeSelectableTextMenuFlutterApi {
  GObject parent_instance;

  FlBinaryMessenger* messenger;
  gchar *suffix;
};

G_DEFINE_TYPE(OhMyFlutterNativeSelectableTextMenuFlutterApi, oh_my_flutter_native_selectable_text_menu_flutter_api, G_TYPE_OBJECT)

static void oh_my_flutter_native_selectable_text_menu_flutter_api_dispose(GObject* object) {
  OhMyFlutterNativeSelectableTextMenuFlutterApi* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API(object);
  g_clear_object(&self->messenger);
  g_clear_pointer(&self->suffix, g_free);
  G_OBJECT_CLASS(oh_my_flutter_native_selectable_text_menu_flutter_api_parent_class)->dispose(object);
}

static void oh_my_flutter_native_selectable_text_menu_flutter_api_init(OhMyFlutterNativeSelectableTextMenuFlutterApi* self) {
}

static void oh_my_flutter_native_selectable_text_menu_flutter_api_class_init(OhMyFlutterNativeSelectableTextMenuFlutterApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = oh_my_flutter_native_selectable_text_menu_flutter_api_dispose;
}

OhMyFlutterNativeSelectableTextMenuFlutterApi* oh_my_flutter_native_selectable_text_menu_flutter_api_new(FlBinaryMessenger* messenger, const gchar* suffix) {
  OhMyFlutterNativeSelectableTextMenuFlutterApi* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API(g_object_new(oh_my_flutter_native_selectable_text_menu_flutter_api_get_type(), nullptr));
  self->messenger = FL_BINARY_MESSENGER(g_object_ref(messenger));
  self->suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  return self;
}

struct _OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse {
  GObject parent_instance;

  FlValue* error;
};

G_DEFINE_TYPE(OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse, oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response, G_TYPE_OBJECT)

static void oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_dispose(GObject* object) {
  OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API_ON_ACTION_RESPONSE(object);
  g_clear_pointer(&self->error, fl_value_unref);
  G_OBJECT_CLASS(oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_parent_class)->dispose(object);
}

static void oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_init(OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse* self) {
}

static void oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_class_init(OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_dispose;
}

static OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse* oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_new(FlValue* response) {
  OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API_ON_ACTION_RESPONSE(g_object_new(oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_get_type(), nullptr));
  if (fl_value_get_length(response) > 1) {
    self->error = fl_value_ref(response);
  }
  return self;
}

gboolean oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_is_error(OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API_ON_ACTION_RESPONSE(self), FALSE);
  return self->error != nullptr;
}

const gchar* oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_get_error_code(OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API_ON_ACTION_RESPONSE(self), nullptr);
  g_assert(oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 0));
}

const gchar* oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_get_error_message(OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API_ON_ACTION_RESPONSE(self), nullptr);
  g_assert(oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 1));
}

FlValue* oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_get_error_details(OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API_ON_ACTION_RESPONSE(self), nullptr);
  g_assert(oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_is_error(self));
  return fl_value_get_list_value(self->error, 2);
}

static void oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_cb(GObject* object, GAsyncResult* result, gpointer user_data) {
  GTask* task = G_TASK(user_data);
  // Retain the borrowed result until the deferred finish callback consumes it.
  g_task_return_pointer(task, g_object_ref(result), g_object_unref);
}

void oh_my_flutter_native_selectable_text_menu_flutter_api_on_action(OhMyFlutterNativeSelectableTextMenuFlutterApi* self, int64_t session_identifier, int64_t action_identifier, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data) {
  g_autoptr(FlValue) args = fl_value_new_list();
  fl_value_append_take(args, fl_value_new_int(session_identifier));
  fl_value_append_take(args, fl_value_new_int(action_identifier));
  g_autofree gchar* channel_name = g_strdup_printf("dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuFlutterApi.onAction%s", self->suffix);
  g_autoptr(OhMyFlutterMessageCodec) codec = oh_my_flutter_message_codec_new();
  FlBasicMessageChannel* channel = fl_basic_message_channel_new(self->messenger, channel_name, FL_MESSAGE_CODEC(codec));
  GTask* task = g_task_new(self, cancellable, callback, user_data);
  // Preserve the lower channel's cancellation result for the generated finish helper.
  g_task_set_check_cancellable(task, FALSE);
  g_task_set_task_data(task, channel, g_object_unref);
  fl_basic_message_channel_send(channel, args, cancellable, oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_cb, task);
}

OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse* oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_finish(OhMyFlutterNativeSelectableTextMenuFlutterApi* self, GAsyncResult* result, GError** error) {
  g_autoptr(GTask) task = G_TASK(result);
  // Release the retained nested result after the message-channel finish call.
  g_autoptr(GAsyncResult) r = G_ASYNC_RESULT(g_task_propagate_pointer(task, nullptr));
  FlBasicMessageChannel* channel = FL_BASIC_MESSAGE_CHANNEL(g_task_get_task_data(task));
  g_autoptr(FlValue) response = fl_basic_message_channel_send_finish(channel, r, error);
  if (response == nullptr) { 
    return nullptr;
  }
  return oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_new(response);
}

struct _OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse {
  GObject parent_instance;

  FlValue* error;
};

G_DEFINE_TYPE(OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse, oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response, G_TYPE_OBJECT)

static void oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_dispose(GObject* object) {
  OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API_ON_DISMISSED_RESPONSE(object);
  g_clear_pointer(&self->error, fl_value_unref);
  G_OBJECT_CLASS(oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_parent_class)->dispose(object);
}

static void oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_init(OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse* self) {
}

static void oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_class_init(OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_dispose;
}

static OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse* oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_new(FlValue* response) {
  OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse* self = OH_MY_FLUTTER_NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API_ON_DISMISSED_RESPONSE(g_object_new(oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_get_type(), nullptr));
  if (fl_value_get_length(response) > 1) {
    self->error = fl_value_ref(response);
  }
  return self;
}

gboolean oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_is_error(OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API_ON_DISMISSED_RESPONSE(self), FALSE);
  return self->error != nullptr;
}

const gchar* oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_get_error_code(OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API_ON_DISMISSED_RESPONSE(self), nullptr);
  g_assert(oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 0));
}

const gchar* oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_get_error_message(OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API_ON_DISMISSED_RESPONSE(self), nullptr);
  g_assert(oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 1));
}

FlValue* oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_get_error_details(OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse* self) {
  g_return_val_if_fail(OH_MY_FLUTTER_IS_NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API_ON_DISMISSED_RESPONSE(self), nullptr);
  g_assert(oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_is_error(self));
  return fl_value_get_list_value(self->error, 2);
}

static void oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_cb(GObject* object, GAsyncResult* result, gpointer user_data) {
  GTask* task = G_TASK(user_data);
  // Retain the borrowed result until the deferred finish callback consumes it.
  g_task_return_pointer(task, g_object_ref(result), g_object_unref);
}

void oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed(OhMyFlutterNativeSelectableTextMenuFlutterApi* self, int64_t session_identifier, gboolean action_invoked, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data) {
  g_autoptr(FlValue) args = fl_value_new_list();
  fl_value_append_take(args, fl_value_new_int(session_identifier));
  fl_value_append_take(args, fl_value_new_bool(action_invoked));
  g_autofree gchar* channel_name = g_strdup_printf("dev.flutter.pigeon.oh_my_flutter.NativeSelectableTextMenuFlutterApi.onDismissed%s", self->suffix);
  g_autoptr(OhMyFlutterMessageCodec) codec = oh_my_flutter_message_codec_new();
  FlBasicMessageChannel* channel = fl_basic_message_channel_new(self->messenger, channel_name, FL_MESSAGE_CODEC(codec));
  GTask* task = g_task_new(self, cancellable, callback, user_data);
  // Preserve the lower channel's cancellation result for the generated finish helper.
  g_task_set_check_cancellable(task, FALSE);
  g_task_set_task_data(task, channel, g_object_unref);
  fl_basic_message_channel_send(channel, args, cancellable, oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_cb, task);
}

OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse* oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_finish(OhMyFlutterNativeSelectableTextMenuFlutterApi* self, GAsyncResult* result, GError** error) {
  g_autoptr(GTask) task = G_TASK(result);
  // Release the retained nested result after the message-channel finish call.
  g_autoptr(GAsyncResult) r = G_ASYNC_RESULT(g_task_propagate_pointer(task, nullptr));
  FlBasicMessageChannel* channel = FL_BASIC_MESSAGE_CHANNEL(g_task_get_task_data(task));
  g_autoptr(FlValue) response = fl_basic_message_channel_send_finish(channel, r, error);
  if (response == nullptr) { 
    return nullptr;
  }
  return oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_new(response);
}
