// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_NATIVE_SELECTABLE_TEXT_G_H_
#define PIGEON_NATIVE_SELECTABLE_TEXT_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * OhMyFlutterNativeSelectableTextRectangleMessage:
 *
 * Carries a Flutter logical-pixel rectangle to a native menu host.
 */

G_DECLARE_FINAL_TYPE(OhMyFlutterNativeSelectableTextRectangleMessage, oh_my_flutter_native_selectable_text_rectangle_message, OH_MY_FLUTTER, NATIVE_SELECTABLE_TEXT_RECTANGLE_MESSAGE, GObject)

/**
 * oh_my_flutter_native_selectable_text_rectangle_message_new:
 * left: field in this object.
 * top: field in this object.
 * right: field in this object.
 * bottom: field in this object.
 *
 * Creates a new #NativeSelectableTextRectangleMessage object.
 *
 * Returns: a new #OhMyFlutterNativeSelectableTextRectangleMessage
 */
OhMyFlutterNativeSelectableTextRectangleMessage* oh_my_flutter_native_selectable_text_rectangle_message_new(double left, double top, double right, double bottom);

/**
 * oh_my_flutter_native_selectable_text_rectangle_message_get_left
 * @object: a #OhMyFlutterNativeSelectableTextRectangleMessage.
 *
 * The horizontal coordinate of the leading edge.
 *
 * Returns: the field value.
 */
double oh_my_flutter_native_selectable_text_rectangle_message_get_left(OhMyFlutterNativeSelectableTextRectangleMessage* object);

/**
 * oh_my_flutter_native_selectable_text_rectangle_message_get_top
 * @object: a #OhMyFlutterNativeSelectableTextRectangleMessage.
 *
 * The vertical coordinate of the upper edge.
 *
 * Returns: the field value.
 */
double oh_my_flutter_native_selectable_text_rectangle_message_get_top(OhMyFlutterNativeSelectableTextRectangleMessage* object);

/**
 * oh_my_flutter_native_selectable_text_rectangle_message_get_right
 * @object: a #OhMyFlutterNativeSelectableTextRectangleMessage.
 *
 * The horizontal coordinate of the trailing edge.
 *
 * Returns: the field value.
 */
double oh_my_flutter_native_selectable_text_rectangle_message_get_right(OhMyFlutterNativeSelectableTextRectangleMessage* object);

/**
 * oh_my_flutter_native_selectable_text_rectangle_message_get_bottom
 * @object: a #OhMyFlutterNativeSelectableTextRectangleMessage.
 *
 * The vertical coordinate of the lower edge.
 *
 * Returns: the field value.
 */
double oh_my_flutter_native_selectable_text_rectangle_message_get_bottom(OhMyFlutterNativeSelectableTextRectangleMessage* object);

/**
 * oh_my_flutter_native_selectable_text_rectangle_message_equals:
 * @a: a #OhMyFlutterNativeSelectableTextRectangleMessage.
 * @b: another #OhMyFlutterNativeSelectableTextRectangleMessage.
 *
 * Checks if two #OhMyFlutterNativeSelectableTextRectangleMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean oh_my_flutter_native_selectable_text_rectangle_message_equals(OhMyFlutterNativeSelectableTextRectangleMessage* a, OhMyFlutterNativeSelectableTextRectangleMessage* b);

/**
 * oh_my_flutter_native_selectable_text_rectangle_message_hash:
 * @object: a #OhMyFlutterNativeSelectableTextRectangleMessage.
 *
 * Calculates a hash code for a #OhMyFlutterNativeSelectableTextRectangleMessage object.
 *
 * Returns: the hash code.
 */
guint oh_my_flutter_native_selectable_text_rectangle_message_hash(OhMyFlutterNativeSelectableTextRectangleMessage* object);

/**
 * oh_my_flutter_native_selectable_text_rectangle_message_to_string:
 * @object: a #OhMyFlutterNativeSelectableTextRectangleMessage.
 *
 * Returns a string representation of a #OhMyFlutterNativeSelectableTextRectangleMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* oh_my_flutter_native_selectable_text_rectangle_message_to_string(OhMyFlutterNativeSelectableTextRectangleMessage* object);

/**
 * OhMyFlutterNativeSelectableTextPointMessage:
 *
 * Carries a Flutter logical-pixel point to a native menu host.
 */

G_DECLARE_FINAL_TYPE(OhMyFlutterNativeSelectableTextPointMessage, oh_my_flutter_native_selectable_text_point_message, OH_MY_FLUTTER, NATIVE_SELECTABLE_TEXT_POINT_MESSAGE, GObject)

/**
 * oh_my_flutter_native_selectable_text_point_message_new:
 * dx: field in this object.
 * dy: field in this object.
 *
 * Creates a new #NativeSelectableTextPointMessage object.
 *
 * Returns: a new #OhMyFlutterNativeSelectableTextPointMessage
 */
OhMyFlutterNativeSelectableTextPointMessage* oh_my_flutter_native_selectable_text_point_message_new(double dx, double dy);

/**
 * oh_my_flutter_native_selectable_text_point_message_get_dx
 * @object: a #OhMyFlutterNativeSelectableTextPointMessage.
 *
 * The horizontal coordinate.
 *
 * Returns: the field value.
 */
double oh_my_flutter_native_selectable_text_point_message_get_dx(OhMyFlutterNativeSelectableTextPointMessage* object);

/**
 * oh_my_flutter_native_selectable_text_point_message_get_dy
 * @object: a #OhMyFlutterNativeSelectableTextPointMessage.
 *
 * The vertical coordinate.
 *
 * Returns: the field value.
 */
double oh_my_flutter_native_selectable_text_point_message_get_dy(OhMyFlutterNativeSelectableTextPointMessage* object);

/**
 * oh_my_flutter_native_selectable_text_point_message_equals:
 * @a: a #OhMyFlutterNativeSelectableTextPointMessage.
 * @b: another #OhMyFlutterNativeSelectableTextPointMessage.
 *
 * Checks if two #OhMyFlutterNativeSelectableTextPointMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean oh_my_flutter_native_selectable_text_point_message_equals(OhMyFlutterNativeSelectableTextPointMessage* a, OhMyFlutterNativeSelectableTextPointMessage* b);

/**
 * oh_my_flutter_native_selectable_text_point_message_hash:
 * @object: a #OhMyFlutterNativeSelectableTextPointMessage.
 *
 * Calculates a hash code for a #OhMyFlutterNativeSelectableTextPointMessage object.
 *
 * Returns: the hash code.
 */
guint oh_my_flutter_native_selectable_text_point_message_hash(OhMyFlutterNativeSelectableTextPointMessage* object);

/**
 * oh_my_flutter_native_selectable_text_point_message_to_string:
 * @object: a #OhMyFlutterNativeSelectableTextPointMessage.
 *
 * Returns a string representation of a #OhMyFlutterNativeSelectableTextPointMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* oh_my_flutter_native_selectable_text_point_message_to_string(OhMyFlutterNativeSelectableTextPointMessage* object);

/**
 * OhMyFlutterNativeSelectableTextMenuItemMessage:
 *
 * Describes one labeled native selection-menu command.
 */

G_DECLARE_FINAL_TYPE(OhMyFlutterNativeSelectableTextMenuItemMessage, oh_my_flutter_native_selectable_text_menu_item_message, OH_MY_FLUTTER, NATIVE_SELECTABLE_TEXT_MENU_ITEM_MESSAGE, GObject)

/**
 * oh_my_flutter_native_selectable_text_menu_item_message_new:
 * identifier: field in this object.
 * label: field in this object.
 *
 * Creates a new #NativeSelectableTextMenuItemMessage object.
 *
 * Returns: a new #OhMyFlutterNativeSelectableTextMenuItemMessage
 */
OhMyFlutterNativeSelectableTextMenuItemMessage* oh_my_flutter_native_selectable_text_menu_item_message_new(int64_t identifier, const gchar* label);

/**
 * oh_my_flutter_native_selectable_text_menu_item_message_get_identifier
 * @object: a #OhMyFlutterNativeSelectableTextMenuItemMessage.
 *
 * The identifier returned when the person chooses this item.
 *
 * Returns: the field value.
 */
int64_t oh_my_flutter_native_selectable_text_menu_item_message_get_identifier(OhMyFlutterNativeSelectableTextMenuItemMessage* object);

/**
 * oh_my_flutter_native_selectable_text_menu_item_message_get_label
 * @object: a #OhMyFlutterNativeSelectableTextMenuItemMessage.
 *
 * The localized label displayed by the platform menu.
 *
 * Returns: the field value.
 */
const gchar* oh_my_flutter_native_selectable_text_menu_item_message_get_label(OhMyFlutterNativeSelectableTextMenuItemMessage* object);

/**
 * oh_my_flutter_native_selectable_text_menu_item_message_equals:
 * @a: a #OhMyFlutterNativeSelectableTextMenuItemMessage.
 * @b: another #OhMyFlutterNativeSelectableTextMenuItemMessage.
 *
 * Checks if two #OhMyFlutterNativeSelectableTextMenuItemMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean oh_my_flutter_native_selectable_text_menu_item_message_equals(OhMyFlutterNativeSelectableTextMenuItemMessage* a, OhMyFlutterNativeSelectableTextMenuItemMessage* b);

/**
 * oh_my_flutter_native_selectable_text_menu_item_message_hash:
 * @object: a #OhMyFlutterNativeSelectableTextMenuItemMessage.
 *
 * Calculates a hash code for a #OhMyFlutterNativeSelectableTextMenuItemMessage object.
 *
 * Returns: the hash code.
 */
guint oh_my_flutter_native_selectable_text_menu_item_message_hash(OhMyFlutterNativeSelectableTextMenuItemMessage* object);

/**
 * oh_my_flutter_native_selectable_text_menu_item_message_to_string:
 * @object: a #OhMyFlutterNativeSelectableTextMenuItemMessage.
 *
 * Returns a string representation of a #OhMyFlutterNativeSelectableTextMenuItemMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* oh_my_flutter_native_selectable_text_menu_item_message_to_string(OhMyFlutterNativeSelectableTextMenuItemMessage* object);

/**
 * OhMyFlutterNativeSelectableTextMenuRequestMessage:
 *
 * Describes one native selection-menu presentation.
 */

G_DECLARE_FINAL_TYPE(OhMyFlutterNativeSelectableTextMenuRequestMessage, oh_my_flutter_native_selectable_text_menu_request_message, OH_MY_FLUTTER, NATIVE_SELECTABLE_TEXT_MENU_REQUEST_MESSAGE, GObject)

/**
 * oh_my_flutter_native_selectable_text_menu_request_message_new:
 * session_identifier: field in this object.
 * selection_rectangle: field in this object.
 * primary_anchor: field in this object.
 * items: field in this object.
 *
 * Creates a new #NativeSelectableTextMenuRequestMessage object.
 *
 * Returns: a new #OhMyFlutterNativeSelectableTextMenuRequestMessage
 */
OhMyFlutterNativeSelectableTextMenuRequestMessage* oh_my_flutter_native_selectable_text_menu_request_message_new(int64_t session_identifier, OhMyFlutterNativeSelectableTextRectangleMessage* selection_rectangle, OhMyFlutterNativeSelectableTextPointMessage* primary_anchor, FlValue* items);

/**
 * oh_my_flutter_native_selectable_text_menu_request_message_get_session_identifier
 * @object: a #OhMyFlutterNativeSelectableTextMenuRequestMessage.
 *
 * Identifies this presentation and rejects callbacks from older menus.
 *
 * Returns: the field value.
 */
int64_t oh_my_flutter_native_selectable_text_menu_request_message_get_session_identifier(OhMyFlutterNativeSelectableTextMenuRequestMessage* object);

/**
 * oh_my_flutter_native_selectable_text_menu_request_message_get_selection_rectangle
 * @object: a #OhMyFlutterNativeSelectableTextMenuRequestMessage.
 *
 * The selected glyph bounds in Flutter global logical pixels.
 *
 * Returns: the field value.
 */
OhMyFlutterNativeSelectableTextRectangleMessage* oh_my_flutter_native_selectable_text_menu_request_message_get_selection_rectangle(OhMyFlutterNativeSelectableTextMenuRequestMessage* object);

/**
 * oh_my_flutter_native_selectable_text_menu_request_message_get_primary_anchor
 * @object: a #OhMyFlutterNativeSelectableTextMenuRequestMessage.
 *
 * The preferred pointer or keyboard anchor in global logical pixels.
 *
 * Returns: the field value.
 */
OhMyFlutterNativeSelectableTextPointMessage* oh_my_flutter_native_selectable_text_menu_request_message_get_primary_anchor(OhMyFlutterNativeSelectableTextMenuRequestMessage* object);

/**
 * oh_my_flutter_native_selectable_text_menu_request_message_get_items
 * @object: a #OhMyFlutterNativeSelectableTextMenuRequestMessage.
 *
 * The ordered commands shown by the menu.
 *
 * Returns: the field value.
 */
FlValue* oh_my_flutter_native_selectable_text_menu_request_message_get_items(OhMyFlutterNativeSelectableTextMenuRequestMessage* object);

/**
 * oh_my_flutter_native_selectable_text_menu_request_message_equals:
 * @a: a #OhMyFlutterNativeSelectableTextMenuRequestMessage.
 * @b: another #OhMyFlutterNativeSelectableTextMenuRequestMessage.
 *
 * Checks if two #OhMyFlutterNativeSelectableTextMenuRequestMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean oh_my_flutter_native_selectable_text_menu_request_message_equals(OhMyFlutterNativeSelectableTextMenuRequestMessage* a, OhMyFlutterNativeSelectableTextMenuRequestMessage* b);

/**
 * oh_my_flutter_native_selectable_text_menu_request_message_hash:
 * @object: a #OhMyFlutterNativeSelectableTextMenuRequestMessage.
 *
 * Calculates a hash code for a #OhMyFlutterNativeSelectableTextMenuRequestMessage object.
 *
 * Returns: the hash code.
 */
guint oh_my_flutter_native_selectable_text_menu_request_message_hash(OhMyFlutterNativeSelectableTextMenuRequestMessage* object);

/**
 * oh_my_flutter_native_selectable_text_menu_request_message_to_string:
 * @object: a #OhMyFlutterNativeSelectableTextMenuRequestMessage.
 *
 * Returns a string representation of a #OhMyFlutterNativeSelectableTextMenuRequestMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* oh_my_flutter_native_selectable_text_menu_request_message_to_string(OhMyFlutterNativeSelectableTextMenuRequestMessage* object);

G_DECLARE_FINAL_TYPE(OhMyFlutterMessageCodec, oh_my_flutter_message_codec, OH_MY_FLUTTER, MESSAGE_CODEC, FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int oh_my_flutter_native_selectable_text_rectangle_message_type_id;
extern const int oh_my_flutter_native_selectable_text_point_message_type_id;
extern const int oh_my_flutter_native_selectable_text_menu_item_message_type_id;
extern const int oh_my_flutter_native_selectable_text_menu_request_message_type_id;

G_DECLARE_FINAL_TYPE(OhMyFlutterNativeSelectableTextMenuHostApi, oh_my_flutter_native_selectable_text_menu_host_api, OH_MY_FLUTTER, NATIVE_SELECTABLE_TEXT_MENU_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(OhMyFlutterNativeSelectableTextMenuHostApiShowResponse, oh_my_flutter_native_selectable_text_menu_host_api_show_response, OH_MY_FLUTTER, NATIVE_SELECTABLE_TEXT_MENU_HOST_API_SHOW_RESPONSE, GObject)

/**
 * oh_my_flutter_native_selectable_text_menu_host_api_show_response_new:
 *
 * Creates a new response to NativeSelectableTextMenuHostApi.show.
 *
 * Returns: a new #OhMyFlutterNativeSelectableTextMenuHostApiShowResponse
 */
OhMyFlutterNativeSelectableTextMenuHostApiShowResponse* oh_my_flutter_native_selectable_text_menu_host_api_show_response_new(gboolean return_value);

/**
 * oh_my_flutter_native_selectable_text_menu_host_api_show_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeSelectableTextMenuHostApi.show.
 *
 * Returns: a new #OhMyFlutterNativeSelectableTextMenuHostApiShowResponse
 */
OhMyFlutterNativeSelectableTextMenuHostApiShowResponse* oh_my_flutter_native_selectable_text_menu_host_api_show_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponse, oh_my_flutter_native_selectable_text_menu_host_api_update_response, OH_MY_FLUTTER, NATIVE_SELECTABLE_TEXT_MENU_HOST_API_UPDATE_RESPONSE, GObject)

/**
 * oh_my_flutter_native_selectable_text_menu_host_api_update_response_new:
 *
 * Creates a new response to NativeSelectableTextMenuHostApi.update.
 *
 * Returns: a new #OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponse
 */
OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponse* oh_my_flutter_native_selectable_text_menu_host_api_update_response_new(gboolean return_value);

/**
 * oh_my_flutter_native_selectable_text_menu_host_api_update_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeSelectableTextMenuHostApi.update.
 *
 * Returns: a new #OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponse
 */
OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponse* oh_my_flutter_native_selectable_text_menu_host_api_update_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponse, oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_response, OH_MY_FLUTTER, NATIVE_SELECTABLE_TEXT_MENU_HOST_API_UPDATE_GEOMETRY_RESPONSE, GObject)

/**
 * oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_response_new:
 *
 * Creates a new response to NativeSelectableTextMenuHostApi.updateGeometry.
 *
 * Returns: a new #OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponse
 */
OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponse* oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_response_new(gboolean return_value);

/**
 * oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeSelectableTextMenuHostApi.updateGeometry.
 *
 * Returns: a new #OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponse
 */
OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponse* oh_my_flutter_native_selectable_text_menu_host_api_update_geometry_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(OhMyFlutterNativeSelectableTextMenuHostApiHideResponse, oh_my_flutter_native_selectable_text_menu_host_api_hide_response, OH_MY_FLUTTER, NATIVE_SELECTABLE_TEXT_MENU_HOST_API_HIDE_RESPONSE, GObject)

/**
 * oh_my_flutter_native_selectable_text_menu_host_api_hide_response_new:
 *
 * Creates a new response to NativeSelectableTextMenuHostApi.hide.
 *
 * Returns: a new #OhMyFlutterNativeSelectableTextMenuHostApiHideResponse
 */
OhMyFlutterNativeSelectableTextMenuHostApiHideResponse* oh_my_flutter_native_selectable_text_menu_host_api_hide_response_new();

/**
 * oh_my_flutter_native_selectable_text_menu_host_api_hide_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeSelectableTextMenuHostApi.hide.
 *
 * Returns: a new #OhMyFlutterNativeSelectableTextMenuHostApiHideResponse
 */
OhMyFlutterNativeSelectableTextMenuHostApiHideResponse* oh_my_flutter_native_selectable_text_menu_host_api_hide_response_new_error(const gchar* code, const gchar* message, FlValue* details);

/**
 * OhMyFlutterNativeSelectableTextMenuHostApiVTable:
 *
 * Table of functions exposed by NativeSelectableTextMenuHostApi to be implemented by the API provider.
 */
typedef struct {
  OhMyFlutterNativeSelectableTextMenuHostApiShowResponse* (*show)(OhMyFlutterNativeSelectableTextMenuRequestMessage* request, gpointer user_data);
  OhMyFlutterNativeSelectableTextMenuHostApiUpdateResponse* (*update)(OhMyFlutterNativeSelectableTextMenuRequestMessage* request, gpointer user_data);
  OhMyFlutterNativeSelectableTextMenuHostApiUpdateGeometryResponse* (*update_geometry)(int64_t session_identifier, const double* geometry, size_t geometry_length, gpointer user_data);
  OhMyFlutterNativeSelectableTextMenuHostApiHideResponse* (*hide)(int64_t session_identifier, gpointer user_data);
} OhMyFlutterNativeSelectableTextMenuHostApiVTable;

/**
 * oh_my_flutter_native_selectable_text_menu_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the NativeSelectableTextMenuHostApi API.
 */
void oh_my_flutter_native_selectable_text_menu_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const OhMyFlutterNativeSelectableTextMenuHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * oh_my_flutter_native_selectable_text_menu_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the NativeSelectableTextMenuHostApi API.
 */
void oh_my_flutter_native_selectable_text_menu_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

G_DECLARE_FINAL_TYPE(OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse, oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response, OH_MY_FLUTTER, NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API_ON_ACTION_RESPONSE, GObject)

/**
 * oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_is_error:
 * @response: a #OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse.
 *
 * Checks if a response to NativeSelectableTextMenuFlutterApi.onAction is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_is_error(OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse* response);

/**
 * oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_get_error_code:
 * @response: a #OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_get_error_code(OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse* response);

/**
 * oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_get_error_message:
 * @response: a #OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_get_error_message(OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse* response);

/**
 * oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_get_error_details:
 * @response: a #OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_response_get_error_details(OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse* response);

G_DECLARE_FINAL_TYPE(OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse, oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response, OH_MY_FLUTTER, NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API_ON_DISMISSED_RESPONSE, GObject)

/**
 * oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_is_error:
 * @response: a #OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse.
 *
 * Checks if a response to NativeSelectableTextMenuFlutterApi.onDismissed is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_is_error(OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse* response);

/**
 * oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_get_error_code:
 * @response: a #OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_get_error_code(OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse* response);

/**
 * oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_get_error_message:
 * @response: a #OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_get_error_message(OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse* response);

/**
 * oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_get_error_details:
 * @response: a #OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_response_get_error_details(OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse* response);

/**
 * OhMyFlutterNativeSelectableTextMenuFlutterApi:
 *
 * Delivers native selection-menu events to Flutter.
 */

G_DECLARE_FINAL_TYPE(OhMyFlutterNativeSelectableTextMenuFlutterApi, oh_my_flutter_native_selectable_text_menu_flutter_api, OH_MY_FLUTTER, NATIVE_SELECTABLE_TEXT_MENU_FLUTTER_API, GObject)

/**
 * oh_my_flutter_native_selectable_text_menu_flutter_api_new:
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Creates a new object to access the NativeSelectableTextMenuFlutterApi API.
 *
 * Returns: a new #OhMyFlutterNativeSelectableTextMenuFlutterApi
 */
OhMyFlutterNativeSelectableTextMenuFlutterApi* oh_my_flutter_native_selectable_text_menu_flutter_api_new(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * oh_my_flutter_native_selectable_text_menu_flutter_api_on_action:
 * @api: a #OhMyFlutterNativeSelectableTextMenuFlutterApi.
 * @session_identifier: parameter for this method.
 * @action_identifier: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Invokes a command previously sent for [sessionIdentifier].
 */
void oh_my_flutter_native_selectable_text_menu_flutter_api_on_action(OhMyFlutterNativeSelectableTextMenuFlutterApi* api, int64_t session_identifier, int64_t action_identifier, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_finish:
 * @api: a #OhMyFlutterNativeSelectableTextMenuFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a oh_my_flutter_native_selectable_text_menu_flutter_api_on_action() call.
 *
 * Returns: a #OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse or %NULL on error.
 */
OhMyFlutterNativeSelectableTextMenuFlutterApiOnActionResponse* oh_my_flutter_native_selectable_text_menu_flutter_api_on_action_finish(OhMyFlutterNativeSelectableTextMenuFlutterApi* api, GAsyncResult* result, GError** error);

/**
 * oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed:
 * @api: a #OhMyFlutterNativeSelectableTextMenuFlutterApi.
 * @session_identifier: parameter for this method.
 * @action_invoked: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Reports that a menu closed and whether a command caused the dismissal.
 */
void oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed(OhMyFlutterNativeSelectableTextMenuFlutterApi* api, int64_t session_identifier, gboolean action_invoked, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_finish:
 * @api: a #OhMyFlutterNativeSelectableTextMenuFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed() call.
 *
 * Returns: a #OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse or %NULL on error.
 */
OhMyFlutterNativeSelectableTextMenuFlutterApiOnDismissedResponse* oh_my_flutter_native_selectable_text_menu_flutter_api_on_dismissed_finish(OhMyFlutterNativeSelectableTextMenuFlutterApi* api, GAsyncResult* result, GError** error);

G_END_DECLS

#endif  // PIGEON_NATIVE_SELECTABLE_TEXT_G_H_
